import {
  ask,
  cue,
  gap,
  intro,
  mcq,
  outro,
  say,
  script,
  speaker,
  speakingQuestions,
  tfng,
  writingTasks,
} from '../builders';
import type { TestContent } from '../types';

export const content: TestContent = {
  listening: [
    {
      id: 'l1',
      index: 1,
      instruction: 'You will hear some short conversations. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          1,
          'What will the man do this evening?',
          ['Watch a match', 'Visit his parents', 'Study for a test'],
          'C',
        ),
        mcq('l', 2, 'Which floor is the office on?', ['The second', 'The fourth', 'The fifth'], 'B'),
        mcq('l', 3, 'What does the woman order?', ['Green tea', 'Black coffee', 'Orange juice'], 'A'),
        mcq(
          'l',
          4,
          'Why can’t the man come to the meeting?',
          ['He is ill', 'He has another meeting', 'His car broke down'],
          'A',
        ),
        mcq('l', 5, 'What present will they buy for Kamola?', ['A book', 'A scarf', 'A watch'], 'B'),
        mcq(
          'l',
          6,
          'When does the library close today?',
          ['At 6 pm', 'At 8 pm', 'At 9 pm'],
          'A',
          'Odatda 8 da yopiladi, lekin bugun bayram oldidan 6 da.',
        ),
        mcq('l', 7, 'What sport does the girl play?', ['Tennis', 'Volleyball', 'Basketball'], 'C'),
        mcq(
          'l',
          8,
          'How much does the man pay?',
          ['12,000 sum', '15,000 sum', '18,000 sum'],
          'B',
          '18 ming emas: 3 ming chegirma bilan 15 ming.',
        ),
      ],
    },
    {
      id: 'l2',
      index: 2,
      title: 'Evergreen Hotel — Room Booking',
      instruction: 'Complete the notes. Write',
      emphasis: 'no more than two words',
      durationSec: 0,
      questions: [
        gap('l', 9, 'Type of room:', 'double room|double'),
        gap('l', 10, 'Arrival date: 14', 'October'),
        gap('l', 11, 'Number of nights:', 'three|3'),
        gap('l', 12, 'Price per night: $', '70', 'Avval 85 dollar deyiladi, keyin haftalik chegirma bilan 70.'),
        gap('l', 13, 'Breakfast is served in the', 'garden'),
        gap('l', 14, 'Guest wants a room with a', 'balcony'),
        gap('l', 15, 'Airport pick-up costs $', '20|twenty'),
        gap('l', 16, 'Confirmation will be sent by', 'text message|text'),
      ],
    },
    {
      id: 'l3',
      index: 3,
      instruction: 'You will hear six people talking about how they learn English. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          17,
          'Speaker 1 improves her English mainly by',
          ['reading novels', 'watching films', 'using apps'],
          'B',
        ),
        mcq(
          'l',
          18,
          'Speaker 2 finds it hardest to',
          ['understand native speakers', 'write essays', 'remember new words'],
          'A',
        ),
        mcq(
          'l',
          19,
          'Speaker 3 practises speaking with',
          ['a private teacher', 'online partners', 'his colleagues'],
          'B',
        ),
        mcq('l', 20, 'Speaker 4 needs English for', ['university', 'her job', 'travelling'], 'B'),
        mcq('l', 21, 'Speaker 5 says grammar books are', ['boring', 'very useful', 'too expensive'], 'B'),
        mcq('l', 22, 'Speaker 6 plans to', ['take an exam', 'study abroad', 'become a teacher'], 'A'),
      ],
    },
    {
      id: 'l4',
      index: 4,
      instruction: 'Listen to a radio interview with a chef. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          23,
          'The chef decided to cook professionally',
          ['after school', 'after working in a bank', 'after a trip abroad'],
          'B',
        ),
        mcq('l', 24, 'Her restaurant is famous for', ['national dishes', 'seafood', 'desserts'], 'A'),
        mcq('l', 25, 'Most of her vegetables come from', ['the market', 'local farmers', 'her own garden'], 'B'),
        mcq('l', 26, 'She says the most important skill for a chef is', ['creativity', 'speed', 'organisation'], 'C'),
        mcq(
          'l',
          27,
          'Next year she plans to',
          ['open a second restaurant', 'write a cookbook', 'start a cooking school'],
          'B',
        ),
      ],
    },
    {
      id: 'l5',
      index: 5,
      title: 'Science Centre — School Visit',
      instruction: 'Complete the notes. Write',
      emphasis: 'one word or a number',
      durationSec: 0,
      questions: [
        gap('l', 28, 'Students leave their bags in the', 'cloakroom'),
        gap('l', 29, 'The planetarium show lasts (minutes):', '40|forty'),
        gap('l', 30, 'Lunch is in the', 'canteen'),
      ],
    },
    {
      id: 'l6',
      index: 6,
      instruction: 'Listen to a talk about saving money. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          31,
          'According to the speaker, most people fail to save because they',
          ['earn too little', 'do not plan', 'spend on travel'],
          'B',
        ),
        mcq('l', 32, 'The speaker suggests saving', ['10% of income', '25% of income', 'whatever is left'], 'A'),
        mcq('l', 33, 'The best time to save is', ['at the end of the month', 'on payday', 'every Friday'], 'B'),
        mcq(
          'l',
          34,
          'Small daily purchases are described as',
          ['harmless', 'surprisingly expensive', 'necessary'],
          'B',
        ),
        mcq(
          'l',
          35,
          'The speaker’s final advice is to',
          ['use cash only', 'track spending', 'open several accounts'],
          'B',
        ),
      ],
    },
  ],
  reading: [
    {
      id: 'r1',
      index: 1,
      title: 'Notice: Green City Cleaning Day',
      instruction: 'Read the text and fill in the gaps. Write one word only.',
      passage: [
        {
          label: 'A',
          text: 'Join us for Green City Cleaning Day on Sunday, 22 April! Volunteers will meet at 9 am outside the town hall and work until lunchtime.',
        },
        {
          label: 'B',
          text: 'Gloves and rubbish bags will be provided, but please wear old clothes and comfortable shoes. Bring a bottle of water, as it may be hot.',
        },
        {
          label: 'C',
          text: 'After the event, all volunteers are invited to a free lunch in the town hall garden. Children must come with a parent.',
        },
      ],
      questions: [
        gap('r', 1, 'Volunteers meet outside the town', 'hall'),
        gap('r', 2, 'The work continues until', 'lunchtime|lunch'),
        gap('r', 3, 'Organisers will give volunteers gloves and', 'bags'),
        gap('r', 4, 'Volunteers should wear old', 'clothes'),
        gap('r', 5, 'Everyone should bring some', 'water'),
        gap('r', 6, 'Lunch will be in the town hall', 'garden'),
        gap('r', 7, 'Children need to be with a', 'parent'),
      ],
    },
    {
      id: 'r2',
      index: 2,
      title: 'Short Messages',
      instruction: 'Read the messages and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Hi Timur, I can’t make football practice tonight — I’ve got a job interview. Could you tell the coach? Thanks!',
        },
        {
          label: 'B',
          text: 'Special offer: buy two pizzas and get a third one free. Valid only on Mondays and Tuesdays until the end of March.',
        },
        {
          label: 'C',
          text: 'Dear parents, the school trip to the zoo is postponed until next Friday because of the rain forecast. Please keep the permission forms.',
        },
      ],
      questions: [
        mcq(
          'r',
          8,
          'Why will the writer miss practice?',
          ['He is ill', 'He has a job interview', 'He is travelling'],
          'B',
        ),
        mcq('r', 9, 'What does the writer ask Timur to do?', ['Tell the coach', 'Pick him up', 'Bring his kit'], 'A'),
        mcq('r', 10, 'How many pizzas must you buy to get one free?', ['One', 'Two', 'Three'], 'B'),
        mcq('r', 11, 'On which days is the offer valid?', ['At weekends', 'Mondays and Tuesdays', 'Every day'], 'B'),
        mcq(
          'r',
          12,
          'Why is the school trip postponed?',
          ['The bus is broken', 'The weather', 'The zoo is closed'],
          'B',
        ),
        mcq(
          'r',
          13,
          'What should parents do with the forms?',
          ['Sign them again', 'Keep them', 'Return them today'],
          'B',
        ),
        mcq('r', 14, 'Which message is an advertisement?', ['A', 'B', 'C'], 'B'),
      ],
    },
    {
      id: 'r3',
      index: 3,
      title: 'Robots in the Kitchen',
      instruction: 'Read the article and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Restaurants in several countries have started using robots to cook simple dishes such as burgers, noodles and salads.',
        },
        {
          label: 'B',
          text: 'Owners say robots never get tired and always follow the recipe exactly, which keeps the quality the same every day.',
        },
        {
          label: 'C',
          text: 'However, many customers still prefer food made by people. They say that cooking is an art, and that robots cannot add a personal touch.',
        },
        {
          label: 'D',
          text: 'For now, most experts agree that robots will help chefs rather than replace them, doing repetitive tasks such as chopping and frying.',
        },
      ],
      questions: [
        mcq('r', 15, 'Robots are currently used to cook', ['complex meals', 'simple dishes', 'desserts only'], 'B'),
        mcq(
          'r',
          16,
          'According to owners, robots',
          ['are cheap to buy', 'never get tired', 'cook faster than people'],
          'B',
        ),
        mcq('r', 17, 'Robots keep the quality', ['the same', 'higher', 'lower'], 'A'),
        mcq(
          'r',
          18,
          'Many customers believe robots cannot',
          ['cook quickly', 'add a personal touch', 'follow recipes'],
          'B',
        ),
        mcq('r', 19, 'Experts think robots will', ['replace chefs', 'help chefs', 'disappear soon'], 'B'),
        mcq('r', 20, 'An example of a repetitive task is', ['creating recipes', 'chopping', 'serving guests'], 'B'),
        mcq(
          'r',
          21,
          'The best title is',
          ['Chefs Out of Work', 'A Helping Hand in the Kitchen', 'The Art of Cooking'],
          'B',
        ),
      ],
    },
    {
      id: 'r4',
      index: 4,
      title: 'The Great Silk Road Today',
      instruction: 'Do the following statements agree with the information in the text?',
      passage: [
        {
          label: 'A',
          text: 'For more than 1,500 years, the Silk Road connected China with the Mediterranean, carrying not only silk but also spices, paper and ideas.',
        },
        {
          label: 'B',
          text: 'Cities such as Samarkand, Bukhara and Khiva grew rich as trading centres, and many of their famous buildings date from this period.',
        },
        {
          label: 'C',
          text: 'Today, the route is being revived through new railways and roads, and tourism along the old caravan routes has grown rapidly in the last ten years.',
          highlight: 'tourism along the old caravan routes has grown rapidly',
        },
        {
          label: 'D',
          text: 'Some historians, however, worry that fast development may damage ancient sites if they are not properly protected.',
        },
      ],
      questions: [
        tfng(22, 'The Silk Road carried only silk.', 'False'),
        tfng(23, 'Samarkand, Bukhara and Khiva became rich through trade.', 'True'),
        tfng(
          24,
          'Tourism along the old routes has increased in recent years.',
          'True',
          'C paragrafi: "has grown rapidly".',
        ),
        tfng(25, 'Most tourists come from Europe.', 'Not given'),
        tfng(26, 'All historians support fast development of the route.', 'False'),
      ],
    },
    {
      id: 'r5',
      index: 5,
      title: 'The Benefits of Boredom',
      instruction: 'Read the text and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Most of us try to avoid boredom. As soon as we have a free minute, we reach for our phones.',
        },
        {
          label: 'B',
          text: 'Yet psychologists say boredom can be useful. When the mind has nothing to do, it starts to wander, and this often leads to new ideas.',
        },
        {
          label: 'C',
          text: 'In one experiment, people who first did a boring task, like copying phone numbers, later produced more creative answers than others.',
        },
        {
          label: 'D',
          text: 'Researchers suggest leaving small gaps in the day without screens, such as a walk or a bus ride, to give the brain time to rest and create.',
        },
      ],
      questions: [
        mcq(
          'r',
          27,
          'What do most people do when they feel bored?',
          ['Go for a walk', 'Use their phones', 'Read a book'],
          'B',
        ),
        mcq(
          'r',
          28,
          'According to psychologists, boredom can',
          ['cause stress', 'lead to new ideas', 'damage memory'],
          'B',
        ),
        mcq(
          'r',
          29,
          'In the experiment, the boring task was',
          ['reading a text', 'copying phone numbers', 'waiting in a queue'],
          'B',
        ),
        mcq('r', 30, 'After the boring task, people were more', ['tired', 'creative', 'relaxed'], 'B'),
        mcq(
          'r',
          31,
          'Researchers recommend',
          ['avoiding boredom', 'short breaks without screens', 'longer working hours'],
          'B',
        ),
        mcq('r', 32, 'The word “wander” is closest to', ['stop', 'move freely', 'focus'], 'B'),
        mcq(
          'r',
          33,
          'A bus ride is given as an example of',
          ['a waste of time', 'a gap without screens', 'a boring job'],
          'B',
        ),
        mcq(
          'r',
          34,
          'The text mainly argues that boredom',
          ['should be avoided', 'has benefits', 'is increasing'],
          'B',
        ),
        mcq(
          'r',
          35,
          'The writer would probably agree that we should',
          ['use phones less often', 'work without breaks', 'avoid free time'],
          'A',
        ),
      ],
    },
  ],
  writing: writingTasks(
    'You attend English evening classes at a language centre. You have received this message from the centre:\n\n"From next week, all evening classes will move from 6 pm to 8 pm, and the group size will increase from 10 to 18 students."',
    'Write a message to a classmate. Tell them about the changes and how you feel about them. Write about 50 words.',
    'Write a letter to the director of the language centre. Explain how the changes affect you and suggest a better solution. Write 120–150 words.',
    'Many people believe that learning online is as effective as learning in a classroom. To what extent do you agree or disagree? Give reasons and examples. Write at least 180 words.',
  ),
  speaking: speakingQuestions({
    personal: [
      'Tell me about your family.',
      'What do you like to do in your free time?',
      'What kind of food do you enjoy most?',
    ],
    pictures:
      'Picture A: people working in a busy open-plan office · Picture B: a person working from home at a kitchen table',
    compare: [
      'Compare the two pictures. What are the similarities and differences?',
      'Where would you prefer to work? Why?',
      'Do you think more people will work from home in the future?',
    ],
    monologue: {
      image: 'A young man celebrating his graduation with his family',
      prompt: 'Describe an important day in your life. Say when it was, what happened and why it was important to you.',
    },
    debate:
      'Tourism is good for a country. For: it creates jobs and brings money. Against: it damages nature and raises prices for local people. Give arguments for and against this statement and say what you think.',
  }),
  scripts: [
    script('l1', [
      intro('Part one. You will hear some short conversations. For each question, choose the correct answer.'),
      ask(1, 'What will the man do this evening?'),
      say('woman', 'Are you coming to watch the match with us tonight? Or are you visiting your parents?'),
      say('man', "Neither, unfortunately. I've got a big test tomorrow, so I'll be at home studying all evening.", 2),
      ask(2, 'Which floor is the office on?'),
      say('man', "Excuse me, is Mr Aliev's office on the second floor?"),
      say(
        'woman',
        "It used to be, but they moved last month. Take the lift to the fourth floor. It's the first door on the left. The fifth floor is the canteen.",
        2,
      ),
      ask(3, 'What does the woman order?'),
      say('man', 'Black coffee as usual?'),
      say('woman', "Not today. I've had too much coffee this week. I'll have a green tea, please. No sugar.", 2),
      ask(4, 'Why can’t the man come to the meeting?'),
      say('woman', 'Are you coming to the meeting this afternoon? Is your car fixed?'),
      say('man', "The car's fine now, but I've got a terrible temperature. I think I'd better stay in bed today.", 2),
      ask(5, 'What present will they buy for Kamola?'),
      say('woman', "Let's buy Kamola a book for her birthday."),
      say(
        'man',
        "She's got hundreds of books. And a watch is too expensive. What about a warm scarf? Winter is coming.",
      ),
      say('woman', 'Good idea. A scarf it is.', 2),
      ask(6, 'When does the library close today?'),
      say('man', 'The library closes at eight, right? I can study there after work.'),
      say('woman', "Normally, yes, but it's a holiday tomorrow, so today it closes early, at six.", 2),
      ask(7, 'What sport does the girl play?'),
      say('man', 'Do you still play tennis, Madina?'),
      say(
        'woman2',
        'I stopped last year. I tried volleyball, but now I play basketball for the school team. We train three times a week.',
        2,
      ),
      ask(8, 'How much does the man pay?'),
      say('man', 'How much are these apples?'),
      say(
        'woman',
        "Eighteen thousand sum for two kilos. But you're a regular customer, so I'll give you three thousand off. Fifteen thousand, please.",
        2,
      ),
      outro('one'),
    ]),
    script('l2', [
      intro('Part two. You will hear a phone call to a hotel. Complete the notes. Write no more than two words.'),
      say('woman', 'Good morning, Evergreen Hotel.'),
      say('man', "Good morning. I'd like to book a room for my wife and me."),
      cue(9, 'woman', "Certainly. So that's a double room for two people."),
      cue(10, 'woman', 'When would you like to arrive?'),
      say('man', 'On the fourteenth of October. Not September, sorry, October.'),
      cue(11, 'woman', 'And for how many nights?'),
      say('man', 'Three nights, please.'),
      cue(12, 'man', 'How much is it per night?'),
      say(
        'woman',
        "The usual price is eighty-five dollars, but in October we have a special offer, so it's seventy dollars a night.",
      ),
      cue(
        13,
        'woman',
        "Breakfast is included. When the weather is good, we serve it in the garden. Otherwise it's in the restaurant.",
      ),
      cue(14, 'man', 'Wonderful. Could we have a room with a balcony? We love the view of the mountains.'),
      say('woman', "No problem. I'll give you a room on the third floor."),
      cue(15, 'man', 'Do you offer an airport pick-up?'),
      say('woman', 'Yes, our driver can meet you. It costs twenty dollars each way.'),
      cue(
        16,
        'woman',
        "I'll send you a confirmation by text message in a few minutes. We don't use email for bookings.",
      ),
      say('man', 'Thank you very much.', 2),
      outro('two'),
    ]),
    script('l3', [
      intro(
        'Part three. You will hear six people talking about how they learn English. For each speaker, choose the correct answer.',
      ),
      speaker(17, 1),
      say(
        'woman',
        "I've tried apps and I sometimes read, but what really works for me is films. I watch one every weekend with English subtitles.",
        2,
      ),
      speaker(18, 2),
      say(
        'man',
        "Writing isn't a problem, and I remember new words quite easily. The hardest thing is understanding native speakers. They talk so fast!",
        2,
      ),
      speaker(19, 3),
      say(
        'man2',
        'A private teacher was too expensive for me, and nobody at work speaks English. So I found conversation partners online. We talk on video every evening.',
        2,
      ),
      speaker(20, 4),
      say(
        'woman2',
        "I finished university years ago and I don't travel much. I need English for my job. I work for an international company and write emails every day.",
        2,
      ),
      speaker(21, 5),
      say(
        'man3',
        "Many people say grammar books are boring, but I disagree. They're very useful. A good grammar book explains things clearly, step by step.",
        2,
      ),
      speaker(22, 6),
      say(
        'woman3',
        "I don't want to study abroad or teach. My plan is to take the CEFR exam in December. I need a B2 certificate.",
        2,
      ),
      outro('three'),
    ]),
    script('l4', [
      intro('Part four. You will hear a radio interview with a chef. Choose the correct answer.'),
      say(
        'man',
        "Today's guest is Nilufar, owner of one of the most popular restaurants in Tashkent. Nilufar, did you always want to be a chef?",
      ),
      cue(
        23,
        'woman',
        'Not at all. After school I studied economics, and then I worked in a bank for six years. I was cooking for friends every weekend, and one day I decided to make it my job.',
      ),
      cue(
        24,
        'woman',
        'We serve some international food, and our desserts are nice, but people really come for our national dishes, especially plov and manti.',
      ),
      say('man', 'Where do your ingredients come from?'),
      cue(
        25,
        'woman',
        "I have a small garden, but it's only for herbs. Most of our vegetables come from local farmers. I know every one of them personally.",
      ),
      say('man', 'What makes a good chef?'),
      cue(
        26,
        'woman',
        "Creativity and speed help, of course. But the most important skill is organisation. In a busy kitchen, if you're not organised, everything goes wrong.",
      ),
      say('man', 'What are your plans?'),
      cue(
        27,
        'woman',
        "People keep asking me to open a second restaurant, but next year I'm going to write a cookbook with my grandmother's recipes.",
        2,
      ),
      outro('four'),
    ]),
    script('l5', [
      intro('Part five. You will hear a guide at a science centre. Complete the notes. Write one word or a number.'),
      cue(
        28,
        'woman',
        'Hello, everyone, and welcome to the Science Centre. Before we start, please leave your bags in the cloakroom, next to the entrance.',
      ),
      cue(
        29,
        'woman',
        'Our first activity is the planetarium show. It lasts forty minutes, so please sit comfortably.',
      ),
      cue(
        30,
        'woman',
        "At one o'clock, we'll have lunch in the canteen on the ground floor. Please don't eat in the exhibition halls.",
        2,
      ),
      outro('five'),
    ]),
    script('l6', [
      intro('Part six. You will hear a talk about saving money. Choose the correct answer.'),
      cue(
        31,
        'man',
        "Hello, everyone. Why do so many people find it hard to save money? Most people think they don't earn enough. But the real reason is that they don't plan.",
      ),
      cue(
        32,
        'man',
        "So how much should you save? Don't wait to see what's left at the end of the month, because nothing will be left. Try to save ten percent of your income.",
      ),
      cue(
        33,
        'man',
        'And timing matters. The best moment to save is on payday. Move the money to a savings account before you start spending.',
      ),
      cue(
        34,
        'man',
        "Watch out for small daily purchases, like coffee or snacks. They seem harmless, but they're surprisingly expensive when you add them up over a year.",
      ),
      cue(
        35,
        'man',
        "My final advice: track your spending. Write down everything you buy for one month. You'll be amazed where your money goes. Thank you.",
        2,
      ),
      say('narrator', 'That is the end of the listening test.'),
    ]),
  ],
};
