import {
  choices,
  cue,
  gap,
  grouped,
  intro,
  letters,
  match,
  mcq,
  outro,
  say,
  script,
  speaker,
  speakingQuestions,
  tfng,
  writingPaper,
} from '../builders';
import type { TestContent } from '../types';

export const content: TestContent = {
  listening: [
    {
      id: 'l1',
      index: 1,
      instruction: 'You will hear some sentences. Choose the correct reply to each sentence.',
      emphasis: 'A, B or C',
      durationSec: 0,
      questions: [
        mcq('l', 1, '', ['Not at all, go ahead.', 'Yes, I opened it.', "It's on the left."], 'A'),
        mcq('l', 2, '', ['Since next year.', 'For about three years.', 'In a language school.'], 'B'),
        mcq(
          'l',
          3,
          '',
          ["Don't worry, I've got another copy.", "Yes, it's a great book.", "I'll lend it to you."],
          'A',
          "Kitob yo'qolgani uchun uzr so'ralmoqda — to'g'ri javob tinchlantiruvchi replika.",
        ),
        mcq('l', 4, '', ['It took an hour.', "I didn't see any.", "Let's walk, it isn't far."], 'C'),
        mcq('l', 5, '', ['Good luck next time.', "Thanks, I can't believe it!", "I'd rather drive."], 'B'),
        mcq(
          'l',
          6,
          '',
          ["It's next to the bank on Park Street.", 'I usually go there on Mondays.', 'Yes, I could.'],
          'A',
          '"Yes, I could" grammatik jihatdan mos, lekin savolga javob bermaydi — joy so\'ralmoqda.',
        ),
        mcq(
          'l',
          7,
          '',
          ['What a great idea!', 'Oh no, I was really looking forward to it.', "I'll bring an umbrella then."],
          'B',
          "Konsert bekor qilingan, shuning uchun soyabon olib kelishning ma'nosi yo'q.",
        ),
        mcq('l', 8, '', ["I'd love to, thanks.", 'No, I had dinner.', "It's on Friday."], 'A'),
      ],
    },
    {
      id: 'l2',
      index: 2,
      title: 'City Sports Centre — information for new members',
      instruction: 'You will hear a guide talking to new members. Fill in the missing information. Write',
      emphasis: 'ONE WORD and / or A NUMBER',
      durationSec: 0,
      questions: [
        gap('l', 9, 'Show your membership card at the', 'reception'),
        gap(
          'l',
          10,
          'On weekdays the pool closes at … pm',
          '9|nine',
          "Avval dam olish kunlari uchun 7 aytiladi, ish kunlari esa 9 da yopiladi.",
        ),
        gap('l', 11, 'Locker deposit: £', '2|two'),
        gap('l', 12, 'Beginners’ yoga class: every', 'Thursday'),
        gap('l', 13, 'In the gym, always use your own', 'towel'),
        gap(
          'l',
          14,
          'Members get … per cent off in the café',
          '10|ten',
          "15 foiz faqat birinchi oy uchun edi va endi amal qilmaydi.",
        ),
      ],
    },
    {
      id: 'l3',
      index: 3,
      instruction: 'You will hear people speaking in different situations. Match each speaker (15–18) to the place where the speaker is (A–F). There are',
      emphasis: 'TWO EXTRA places',
      durationSec: 0,
      choices: choices([
        'at a railway station',
        'in a hospital',
        'at a hotel reception',
        'in a museum',
        'at a football match',
        'in a supermarket',
      ]),
      questions: [
        match('l', 15, 'Speaker 1', 'C'),
        match('l', 16, 'Speaker 2', 'A'),
        match(
          'l',
          17,
          'Speaker 3',
          'D',
          '"Exhibits", "please don\'t touch" va "guided tour" — muzey belgilari.',
        ),
        match('l', 18, 'Speaker 4', 'F'),
      ],
    },
    {
      id: 'l4',
      index: 4,
      instruction: 'You will hear someone giving a talk. Label the places (19–23) on the map (A–H). There are',
      emphasis: 'THREE extra options',
      durationSec: 0,
      choices: letters(8),
      map: {
        width: 320,
        height: 240,
        roads: [
          { points: [[10, 120], [310, 120]] },
          { points: [[160, 10], [160, 120]] },
          { points: [[240, 120], [240, 230]] },
        ],
        blocks: [
          { x: 20, y: 72, w: 52, h: 34, letter: 'A' },
          { x: 92, y: 72, w: 52, h: 34, letter: 'B' },
          { x: 176, y: 36, w: 52, h: 34, letter: 'C' },
          { x: 250, y: 72, w: 52, h: 34, letter: 'D' },
          { x: 20, y: 134, w: 52, h: 34, letter: 'E' },
          { x: 92, y: 134, w: 52, h: 34, letter: 'F' },
          { x: 166, y: 134, w: 60, h: 34, name: 'Town hall' },
          { x: 256, y: 176, w: 52, h: 34, letter: 'G' },
          { x: 170, y: 186, w: 52, h: 34, letter: 'H' },
        ],
        labels: [
          { x: 60, y: 124, text: 'Main Street' },
          { x: 160, y: 20, text: 'North Road' },
          { x: 240, y: 236, text: 'River Lane' },
        ],
      },
      questions: [
        match('l', 19, 'Library', 'B'),
        match(
          'l',
          20,
          'Car park',
          'H',
          '"Directly behind the town hall" — ratusha orqasida, ya\'ni janubida.',
        ),
        match('l', 21, 'Post office', 'C'),
        match('l', 22, 'Sports hall', 'G'),
        match('l', 23, 'Bakery', 'E'),
      ],
    },
    {
      id: 'l5',
      index: 5,
      instruction: 'You will hear three extracts. Choose the correct answer (A, B or C) for each question. There are',
      emphasis: 'TWO questions for each extract',
      durationSec: 0,
      questions: [
        ...grouped('Extract One', [
          mcq(
            'l',
            24,
            'Why did Laura apply for the job at the cinema?',
            ['to meet new people', 'to pay for driving lessons', 'to watch films for free'],
            'B',
            'Bepul filmlar haqida gapiradi, lekin asosiy sabab — haydovchilik darslari uchun pul.',
          ),
          mcq(
            'l',
            25,
            'What does Laura dislike about the job?',
            ['working late at night', 'her manager', 'cleaning the cinema'],
            'A',
          ),
        ]),
        ...grouped('Extract Two', [
          mcq(
            'l',
            26,
            'How did Rustam start keeping bees?',
            ['His grandfather left him some hives.', 'He took a course at college.', 'He read a book about bees.'],
            'A',
          ),
          mcq(
            'l',
            27,
            'According to Rustam, the biggest danger for bees today is',
            ['cold weather.', 'complaints from neighbours.', 'chemicals used on farms.'],
            'C',
            "Ob-havo va qo'shnilar ham tilga olinadi, lekin \"the real danger\" — pestitsidlar.",
          ),
        ]),
        ...grouped('Extract Three', [
          mcq(
            'l',
            28,
            'Why has the school trip been postponed?',
            ['The bus was booked too late.', 'The museum is closed for repairs.', 'Not enough students signed up.'],
            'B',
          ),
          mcq(
            'l',
            29,
            'What must every student bring on the day of the trip?',
            ['a packed lunch', 'a signed letter from parents', 'a notebook'],
            'B',
            'Tushlik ixtiyoriy, daftar esa maktab beradi — majburiysi ota-ona imzolagan xat.',
          ),
        ]),
      ],
    },
    {
      id: 'l6',
      index: 6,
      title: 'The history of tea',
      instruction: 'You will hear a part of a lecture. Fill in the missing information. Write',
      emphasis: 'no more than ONE WORD',
      durationSec: 0,
      questions: [
        gap('l', 30, 'In ancient China, tea was first drunk as a', 'medicine'),
        gap('l', 31, 'Tea reached Europe in the 17th century with Dutch', 'traders|merchants'),
        gap('l', 32, 'At first, tea in Britain was very', 'expensive'),
        gap('l', 33, 'Afternoon tea was made fashionable by a', 'duchess'),
        gap('l', 34, 'Tea bags were invented by accident in', 'America|USA|US'),
        gap(
          'l',
          35,
          'Before drying, black tea leaves are fully',
          'oxidised|oxidized',
          "Yashil choy bargi oksidlanmaydi, qora choy esa to'liq oksidlanadi.",
        ),
      ],
    },
  ],
  reading: [
    {
      id: 'r1',
      index: 1,
      title: 'Why we need sleep',
      instruction: 'Read the text. Fill in each gap with ONE word. You must use a word which is somewhere in the rest of the text.',
      passage: [
        {
          label: '1',
          text: 'Most adults need between seven and nine hours of sleep every night. However, many (1) ______ get much less than this, especially during busy weeks at work. Scientists say that sleep is not a waste of time. While we sleep, the (2) ______ sorts and stores what we have learned during the day. That is why students who sleep well are more likely to remember new information.',
        },
        {
          label: '2',
          text: 'Lack of sleep also affects our mood and makes us more (3) ______ to make careless mistakes. Experts recommend going to bed at the same (4) ______ every evening. It also helps to switch off phones and other (5) ______ an hour before bed, because the light from screens keeps the brain awake.',
        },
        {
          label: '3',
          text: 'Finally, a cool, dark and quiet (6) ______ helps most people fall asleep faster. If your bedroom is noisy, earplugs can make a big difference. Small changes like these can help adults, students and even busy workers feel more rested.',
        },
      ],
      questions: [
        gap('r', 1, 'However, many (1) ______ get much less than this.', 'adults'),
        gap('r', 2, 'While we sleep, the (2) ______ sorts and stores what we have learned.', 'brain'),
        gap(
          'r',
          3,
          'It makes us more (3) ______ to make careless mistakes.',
          'likely',
          'So\'z matnning o\'zida bor: "are more likely to remember".',
        ),
        gap('r', 4, 'Go to bed at the same (4) ______ every evening.', 'time'),
        gap('r', 5, 'Switch off phones and other (5) ______ an hour before bed.', 'screens'),
        gap('r', 6, 'A cool, dark and quiet (6) ______ helps you fall asleep.', 'bedroom'),
      ],
    },
    {
      id: 'r2',
      index: 2,
      title: 'Weekend activities',
      instruction: 'Read the texts 7–14 and the statements A–J. Decide which text matches the situation in each statement. Each statement can be used ONCE only. There are TWO extra statements.',
      passage: [
        {
          label: '7',
          text: 'CHIMGAN HIKING CLUB — Guided mountain walks every Saturday. Beginners welcome. Transport from the city is included in the price. Bring strong shoes and water.',
        },
        {
          label: '8',
          text: 'RIVERSIDE COOKING SCHOOL — Learn to cook plov and other national dishes in a small group. All ingredients provided. Take your dishes home with you.',
        },
        {
          label: '9',
          text: 'CITY PHOTO WALK — Discover the hidden corners of the old town with a professional photographer who will show you how to take better pictures. Bring your camera or phone.',
        },
        {
          label: '10',
          text: 'GREEN VALLEY FARM — Pick your own apples and cherries. Children under seven enter free. Fresh juice and pastries in our café.',
        },
        {
          label: '11',
          text: 'SUNDAY CHESS CAFÉ — Friendly games with players of all levels. Weekly tournaments with prizes for the winners. Coffee is included in the entry price.',
        },
        {
          label: '12',
          text: 'LAKESIDE YOGA — Outdoor classes at 7 am by the water. Mats available to rent. Classes are cancelled in bad weather.',
        },
        {
          label: '13',
          text: 'ART IN THE PARK — Painting workshops for the whole family. All materials provided. The best pictures will be shown in our autumn exhibition at the city gallery.',
        },
        {
          label: '14',
          text: 'NIGHT SKY TOURS — Watch the stars and planets through powerful telescopes, far from the city lights. Warm clothes recommended. Trips start at 10 pm.',
        },
      ],
      choices: choices([
        'You want to cook traditional food.',
        'You would like to compete to win something.',
        'You want to exercise early in the day near water.',
        "You don't want to organise your own travel.",
        'Your work may be seen by the public.',
        'Young children can visit without paying.',
        'You are interested in astronomy.',
        'You want to learn how to take better photos.',
        'You want to learn to swim.',
        'You want to stay overnight in the mountains.',
      ]),
      questions: [
        match('r', 7, 'Text 7', 'D', 'Tog\'da tunab qolish (J) haqida gap yo\'q — "transport is included".'),
        match('r', 8, 'Text 8', 'A'),
        match('r', 9, 'Text 9', 'H'),
        match('r', 10, 'Text 10', 'F'),
        match('r', 11, 'Text 11', 'B'),
        match('r', 12, 'Text 12', 'C'),
        match('r', 13, 'Text 13', 'E'),
        match('r', 14, 'Text 14', 'G'),
      ],
    },
    {
      id: 'r3',
      index: 3,
      title: 'The rise of urban farming',
      instruction: 'Read the text and choose the correct heading for each paragraph from the list of headings. There are more headings than paragraphs, so you will not use all of them.',
      passage: [
        {
          label: 'I',
          text: 'Look up in many modern cities and you may see vegetables growing where you least expect them: on rooftops, balconies and even the walls of car parks. Empty spaces that were once ignored are being turned into small farms, and city planners are starting to see them as a valuable resource rather than wasted land.',
        },
        {
          label: 'II',
          text: 'Supporters say urban farms are good for the environment. Food grown in the city does not need to be transported hundreds of kilometres by lorry, which means less fuel and less pollution. Green roofs also keep buildings cooler in summer and help rainwater drain away more slowly.',
        },
        {
          label: 'III',
          text: 'There are social benefits too. Community gardens give neighbours who have never spoken a reason to meet. Older residents share their knowledge with children, who learn where their food comes from. In some cities, volunteers grow vegetables for local families who cannot afford fresh food.',
        },
        {
          label: 'IV',
          text: 'Some of the most exciting projects use no earth at all. In so-called vertical farms, plants grow in water rich in nutrients, stacked on shelves inside old warehouses. Special lights replace the sun, and computers control the temperature, so crops can be harvested all year round.',
        },
        {
          label: 'V',
          text: 'However, urban farming has its critics. Land and electricity in cities are expensive, and indoor farms use a great deal of energy. So far, they can only grow certain crops, such as salad leaves and herbs, profitably. Wheat, rice and potatoes still need large fields.',
        },
        {
          label: 'VI',
          text: 'Even so, many experts believe urban farms will play a bigger role in the coming decades. Several governments now offer grants for green roofs, and some schools have started their own gardens. As cities continue to grow, finding new ways to feed their residents may become a necessity rather than a hobby.',
        },
      ],
      choices: choices([
        'Growing without soil',
        'Not without difficulties',
        'A new use for city spaces',
        'Bringing people together',
        'Why farmers are leaving the countryside',
        'Good news for the planet',
        'What lies ahead',
        'The most profitable crops',
      ]),
      questions: [
        match('r', 15, 'Paragraph I', 'C'),
        match('r', 16, 'Paragraph II', 'F'),
        match('r', 17, 'Paragraph III', 'D'),
        match('r', 18, 'Paragraph IV', 'A'),
        match(
          'r',
          19,
          'Paragraph V',
          'B',
          "Paragrafda foydali ekinlar tilga olinadi, lekin asosiy fikr — muammolar (H emas).",
        ),
        match('r', 20, 'Paragraph VI', 'G'),
      ],
    },
    {
      id: 'r4',
      index: 4,
      title: 'Two wheels',
      instruction: 'Read the text. For questions 21–24, choose the correct answer A, B, C or D. For questions 25–29, decide if the statements agree with the information in the text.',
      passage: [
        {
          label: '1',
          text: 'I was twelve when I found an old bicycle under a dusty sheet in my grandfather’s garage. It had a heavy black frame, a leather seat and a little bell that still worked. My grandfather laughed when he saw my face and said it had been his pride and joy as a young man. From that day on I wanted to know everything about bicycles, and I have been collecting them for almost thirty years.',
        },
        {
          label: '2',
          text: 'The story of the bicycle begins in 1817 in the German city of Mannheim, where an inventor called Karl Drais built what he called a “running machine”. It had two wooden wheels and handlebars, but no pedals: the rider sat on it and pushed it along with his feet. It was fast on good roads, but the roads of the time were rarely good, and the fashion soon passed.',
        },
        {
          label: '3',
          text: 'Pedals arrived in the 1860s, and soon afterwards came the strange-looking “penny-farthing”, with its enormous front wheel and tiny back one. The large wheel made it fast, but the rider sat so high above the ground that any stone in the road could throw him over the handlebars. It was also expensive, so it remained a toy for young men with money and courage.',
        },
        {
          label: '4',
          text: 'The real revolution came in the 1880s with the “safety bicycle”, which had two wheels of the same size and a chain that turned the back wheel. A few years later, a Scottish vet, John Dunlop, developed air-filled rubber tyres while trying to make his son’s tricycle more comfortable. Cycling suddenly became cheap, safe and pleasant.',
        },
        {
          label: '5',
          text: 'The effect on society was enormous, especially for women. For the first time, many women could travel on their own, without a horse or a companion, and clothing changed to make riding easier. Some historians argue that the bicycle did more for women’s independence than any law of the time. Today, when I ride my grandfather’s old bicycle through the park, I like to think of all the journeys it has made possible.',
        },
      ],
      questions: [
        mcq(
          'r',
          21,
          'The writer became interested in bicycles when she',
          [
            'was given one as a birthday present.',
            'found an old one in a garage.',
            'saw a collection in a museum.',
            'learnt to ride with her grandfather.',
          ],
          'B',
        ),
        mcq(
          'r',
          22,
          'The “running machine” did not have',
          ['wheels.', 'a seat.', 'pedals.', 'handlebars.'],
          'C',
        ),
        mcq(
          'r',
          23,
          'The penny-farthing was dangerous because',
          [
            'its brakes often failed.',
            'the rider sat very high above the ground.',
            'its wheels were made of wood.',
            'it was too heavy to control.',
          ],
          'B',
        ),
        mcq(
          'r',
          24,
          'According to the text, the bicycle changed women’s lives by',
          [
            'creating new jobs in factories.',
            'making horses cheaper.',
            'allowing them to travel independently.',
            'changing the laws of the time.',
          ],
          'C',
          "Matnda qonunlar bilan solishtiriladi, lekin velosiped qonunni o'zgartirgan deyilmaydi.",
        ),
        tfng(
          25,
          'The writer’s grandfather used his bicycle to get to work.',
          'No Information',
          "Bobosi velosipedni yaxshi ko'rgani aytiladi, lekin ishga qanday borgani haqida ma'lumot yo'q.",
        ),
        tfng(26, 'The first bicycle-like machine was built in Germany.', 'True'),
        tfng(27, 'Most people could afford a penny-farthing.', 'False'),
        tfng(28, 'Air-filled tyres were developed by an animal doctor.', 'True', 'Vet — veterinar, ya\'ni hayvonlar shifokori.'),
        tfng(29, 'Today there are more bicycles than cars in the world.', 'No Information'),
      ],
    },
    {
      id: 'r5',
      index: 5,
      title: 'Cities of the Silk Road',
      instruction: 'Read the text. For questions 30–33, fill in the missing information. Write no more than ONE WORD and / or A NUMBER. For questions 34–35, choose the correct answer A, B, C or D.',
      passage: [
        {
          label: '1',
          text: 'For more than fifteen centuries, the network of trade routes known as the Silk Road linked China with the Mediterranean. Silk was only one of many goods carried along it: spices, paper, glass, horses and precious stones all travelled thousands of kilometres from one market to the next. Few merchants made the whole journey themselves; most goods changed hands many times along the way.',
        },
        {
          label: '2',
          text: 'Travel was slow and dangerous. A camel caravan usually covered about thirty kilometres a day, and travellers faced deserts, mountain passes and bandits. To make the journey possible, rulers built caravanserais — large inns with thick walls where people and animals could rest safely for the night. Some of these buildings can still be seen in Uzbekistan today.',
        },
        {
          label: '3',
          text: 'Cities such as Samarkand and Bukhara grew rich from this trade. Their markets were full of languages from across Asia and Europe, and with the goods came new ideas, religions and scientific knowledge. Scholars from these cities made important discoveries in mathematics, astronomy and medicine that later influenced the rest of the world.',
        },
        {
          label: '4',
          text: 'From the fifteenth century onwards, however, European ships found routes to Asia by sea. Ships could carry far more goods than camels, and the journey was cheaper, so the old land routes slowly lost their importance. Today, the great cities of the Silk Road attract a different kind of traveller: tourists who come to admire the blue domes and busy bazaars that tell the story of this remarkable past.',
        },
      ],
      questions: [
        gap('r', 30, 'The Silk Road connected China with the', 'Mediterranean'),
        gap('r', 31, 'A caravan travelled about … kilometres a day.', '30|thirty'),
        gap('r', 32, 'Travellers rested in inns called', 'caravanserais|caravanserai'),
        gap('r', 33, 'Along with goods, people exchanged new', 'ideas'),
        mcq(
          'r',
          34,
          'Why did the land routes become less important?',
          [
            'Wars closed the borders between countries.',
            'Silk went out of fashion in Europe.',
            'Transport by sea was cheaper and carried more.',
            'The cities stopped building caravanserais.',
          ],
          'C',
        ),
        mcq(
          'r',
          35,
          'What is the writer’s main purpose?',
          [
            'to advertise tours to Samarkand and Bukhara',
            'to explain how trade shaped the history of Silk Road cities',
            'to compare land travel with sea travel',
            'to criticise modern tourism in Central Asia',
          ],
          'B',
        ),
      ],
    },
  ],
  writing: writingPaper(
    {
      context:
        'You joined an online English course a month ago, but you have had several problems with the lessons and the website.',
      prompt:
        'Write an email to the course manager. In your email:\n- explain why you joined the course;\n- describe the problems you have had;\n- say what you would like the manager to do.\nWrite about 150 words in an appropriate format and style.',
    },
    'Some people believe that young people should take a year off to work or travel before starting university. Others think they should begin their studies immediately after school.\n\nDiscuss both views and give your opinion. Write at least 250 words in an appropriate style and format.',
  ),
  speaking: speakingQuestions({
    personal: [
      'Tell me about your family.',
      'What do you like to do in your free time?',
      'What kind of food do you enjoy most?',
    ],
    pictures:
      'Picture A: people working in a busy open-plan office · Picture B: a person working from home at a kitchen table',
    compare: [
      'Compare the two pictures. What are the similarities and differences?',
      'Where would you prefer to work? Why?',
      'Do you think more people will work from home in the future?',
    ],
    monologue: {
      image: 'A young man celebrating his graduation with his family',
      prompt: 'Describe an important day in your life. Say when it was, what happened and why it was important to you.',
    },
    debate:
      'Tourism is good for a country. For: it creates jobs and brings money. Against: it damages nature and raises prices for local people. Give arguments for and against this statement and say what you think.',
  }),
  scripts: [
    script('l1', [
      intro('Part one. You will hear some sentences. Choose the correct reply to each sentence.'),
      cue(1, 'woman', 'Would you mind if I opened the window?', 2),
      cue(2, 'man', 'How long have you been learning English?', 2),
      cue(3, 'woman', "I'm so sorry, but I'm afraid I've lost the book you lent me.", 2),
      cue(4, 'man', 'Shall we take a taxi to the station, or walk?', 2),
      cue(5, 'woman', 'Congratulations on passing your driving test!', 2),
      cue(6, 'man', 'Excuse me, could you tell me where the nearest pharmacy is?', 2),
      cue(7, 'woman', "Have you heard? Tonight's concert has been cancelled because of the rain.", 2),
      cue(8, 'man', 'Do you fancy coming round to our place for dinner on Friday?', 2),
      outro('one'),
    ]),
    script('l2', [
      intro('Part two. You will hear a guide talking to new members of a sports centre. Fill in the missing information. Write one word and, or, a number for each answer.'),
      say('woman', "Good morning, everyone, and welcome to City Sports Centre. I'm Nodira, and I'll tell you a few things you need to know before you start."),
      cue(9, 'woman', "First of all, your membership card. Please don't leave it at home, because you need to show it at the reception every time you come in. The security guard at the door can't check it for you."),
      cue(10, 'woman', "Now, the swimming pool. At weekends it closes quite early, at seven in the evening, but from Monday to Friday you can swim until nine p.m."),
      cue(11, 'woman', "There are lockers in both changing rooms. They're free to use, but you pay a deposit of two pounds, which you get back when you return the key."),
      cue(12, 'woman', "Lots of you have asked about yoga. The advanced class is on Tuesday evenings, and the beginners' class is every Thursday, so I'd recommend starting there."),
      cue(13, 'woman', "In the gym, please always use your own towel on the machines. We don't provide them, I'm afraid, but you can buy one in our shop."),
      cue(14, 'woman', "And finally, our café. During your first month there was a special offer of fifteen per cent off, but that's finished now. All members get ten per cent off everything, all year round. Enjoy your training!"),
      outro('two'),
    ]),
    script('l3', [
      intro('Part three. You will hear people speaking in different situations. Match each speaker to the place where the speaker is. There are two extra places which you do not need to use.'),
      speaker(15, 1),
      say('man', "Good evening, and welcome. I can see your booking here: a double room for three nights. Here's your key card. Breakfast is served from seven in the restaurant, and the lift is just behind you."),
      speaker(16, 2),
      say('woman', "Excuse me, is this the right platform for Samarkand? The board says the eight fifteen is delayed. Oh, it's leaving from platform four now? Thanks, I'd better run, it's going in two minutes."),
      speaker(17, 3),
      say('man2', "Ladies and gentlemen, the guided tour of the exhibits will begin in five minutes by the main staircase. Please don't touch any of the objects, and remember that photography with a flash is not allowed in this hall."),
      speaker(18, 4),
      say('woman2', "Right, we've got the milk and the bread. Can you go and get some tomatoes from the vegetable section? I'll queue at the checkout. Oh, and don't forget, the eggs are on special offer today."),
      outro('three'),
    ]),
    script('l4', [
      intro('Part four. You will hear someone giving a talk. Label the places on the map. There are three extra options which you do not need to use.'),
      say('man', "Hello and welcome to our town. I'm going to tell you where some useful places are. We're standing at the entrance of the town hall, on the south side of Main Street."),
      cue(19, 'man', "First, the library. Walk to the crossroads where North Road meets Main Street. The library is on the corner, on the north side of Main Street and just to the west of North Road."),
      cue(20, 'man', "If you come by car, don't park on Main Street. The car park is directly behind the town hall, on its south side, and it's free on Sundays."),
      cue(21, 'man', "The post office is a short walk up North Road. Go north from the crossroads, and you'll see it on your right, about halfway up the road."),
      cue(22, 'man', "For the sports hall, go east along Main Street and turn right into River Lane. Walk down River Lane, and the sports hall is near the end, on your left-hand side."),
      cue(23, 'man', "And finally, the best bakery in town. It's at the western end of Main Street, on the south side, opposite the bank. You'll smell the fresh bread before you see it!"),
      outro('four'),
    ]),
    script('l5', [
      intro('Part five. You will hear three extracts. Choose the correct answer for each question. There are two questions for each extract.'),
      say('narrator', 'Extract one. You will hear two friends talking about a part-time job.'),
      say('man', "So, Laura, how's the new job at the cinema? I bet you watch all the new films for free."),
      cue(24, 'woman', "Well, yes, staff can see films for free, which is nice. But honestly, that's not why I applied. Driving lessons are so expensive, and I want to pass my test before the summer, so I need the money."),
      cue(25, 'woman', "The manager's really kind, and I don't mind cleaning the seats after each show. What I hate is the late shifts. Sometimes I don't finish until after midnight, and I'm exhausted the next day."),
      say('narrator', 'Extract two. You will hear part of a radio interview with a beekeeper.'),
      say('woman2', "Rustam, you've kept bees for twenty years. How did it all start?"),
      cue(26, 'man2', "My grandfather was a beekeeper, and when he died he left me his three hives. I'd never taken a course or read a book about bees, so I learnt everything by making mistakes!"),
      cue(27, 'man2', "People think cold winters are the main problem, but bees cope with weather quite well. And yes, sometimes neighbours complain. But the real danger is the chemicals that farmers spray on their fields. They kill whole colonies."),
      say('narrator', 'Extract three. You will hear a teacher talking to a student about a school trip.'),
      say('woman', "Miss Karimova, are we still going to the history museum on Friday?"),
      cue(28, 'woman3', "I'm afraid not, Aziz. We booked the bus in good time and lots of students signed up, but the museum is closed for repairs until next month. So we've moved the trip to the fourteenth."),
      cue(29, 'woman3', "You can bring a packed lunch if you like, and the school will give everyone a notebook. But you must bring the letter signed by your parents, or you can't come."),
      outro('five'),
    ]),
    script('l6', [
      intro('Part six. You will hear a part of a lecture. Fill in the missing information. Write no more than one word for each answer.'),
      say('man3', "Good afternoon. Today's lecture is about one of the world's favourite drinks: tea."),
      cue(30, 'man3', "According to legend, tea was discovered in China nearly five thousand years ago. At first people didn't drink it for pleasure. It was used as a medicine, to help with tiredness and stomach problems."),
      cue(31, 'man3', "Tea didn't reach Europe until the seventeenth century, when Dutch traders brought it from Asia to Amsterdam."),
      cue(32, 'man3', "When tea arrived in Britain, it was very expensive, so only rich families could afford it. They often kept their tea in locked wooden boxes."),
      cue(33, 'man3', "The famous tradition of afternoon tea started in the eighteen-forties. It was made fashionable by a duchess, who felt hungry in the long hours between lunch and dinner."),
      cue(34, 'man3', "Tea bags, by the way, were invented by accident in America. A tea seller sent samples to his customers in small silk bags, and they put the bags straight into hot water."),
      cue(35, 'man3', "Finally, what makes black tea different from green tea? Green tea leaves are dried quickly, but black tea leaves are fully oxidised before drying, which gives them their dark colour and strong taste."),
      outro('six'),
    ]),
  ],
};
