import {
  choices,
  cue,
  gap,
  grouped,
  intro,
  letters,
  match,
  mcq,
  outro,
  say,
  script,
  speaker,
  speakingQuestions,
  tfng,
  writingPaper,
} from '../builders';
import type { TestContent } from '../types';

export const content: TestContent = {
  listening: [
    {
      id: 'l1',
      index: 1,
      instruction: 'You will hear some sentences. Choose the correct reply to each sentence.',
      emphasis: 'A, B or C',
      durationSec: 0,
      questions: [
        mcq('l', 1, '', ['No, please sit down.', 'Yes, I sit here every day.', 'It was very comfortable.'], 'A'),
        mcq('l', 2, '', ['It left yesterday.', 'In about ten minutes.', 'By bus, usually.'], 'B'),
        mcq('l', 3, '', ["Never mind, we haven't started yet.", "Yes, I'm late too.", "I'll take a taxi."], 'A'),
        mcq('l', 4, '', ["They're quite heavy.", 'Upstairs, on the left.', 'Of course, give me one.'], 'C'),
        mcq(
          'l',
          5,
          '',
          ['Yes, please.', 'Coffee, please, with milk.', 'I like it very much.'],
          'B',
          '"Tea or coffee?" — tanlov savoli, shuning uchun "Yes, please" mos kelmaydi.',
        ),
        mcq('l', 6, '', ["That's fantastic news!", 'Which one would you offer?', "I'm sorry to hear that."], 'A'),
        mcq('l', 7, '', ["Yes, it's a blue one.", 'Not at all, here you are.', "I've borrowed it already."], 'B'),
        mcq('l', 8, '', ["I'm going next week.", 'By train, it was quicker.', 'Wonderful, the old town was amazing.'], 'C'),
      ],
    },
    {
      id: 'l2',
      index: 2,
      title: 'Central Library — tour notes',
      instruction: 'You will hear a librarian giving a tour. Fill in the missing information. Write',
      emphasis: 'ONE WORD and / or A NUMBER',
      durationSec: 0,
      questions: [
        gap('l', 9, 'Members can borrow up to … books at a time', '6|six', "Avval 4 ta edi, hozir 6 ta."),
        gap('l', 10, 'Study rooms are on the … floor', 'third|3rd'),
        gap('l', 11, 'To use a printer, get a code from the', 'librarian'),
        gap('l', 12, 'Fine for late books: … som per day', '2000|2,000|two thousand'),
        gap('l', 13, 'In the quiet zone, no … is allowed', 'food'),
        gap(
          'l',
          14,
          'The library is closed every',
          'Sunday',
          "Juma kuni kech soatgacha ochiq — bu chalg'ituvchi ma'lumot.",
        ),
      ],
    },
    {
      id: 'l3',
      index: 3,
      instruction: 'You will hear people speaking in different situations. Match each speaker (15–18) to the place where the speaker is (A–F). There are',
      emphasis: 'TWO EXTRA places',
      durationSec: 0,
      choices: choices(['at an airport', 'in a bank', 'at a cinema', "at a doctor's", 'in a restaurant', 'at a zoo']),
      questions: [
        match('l', 15, 'Speaker 1', 'E'),
        match(
          'l',
          16,
          'Speaker 2',
          'A',
          'Pul almashtirish tilga olinadi, lekin "boarding gate" va "passport" — aeroport.',
        ),
        match('l', 17, 'Speaker 3', 'F'),
        match('l', 18, 'Speaker 4', 'D'),
      ],
    },
    {
      id: 'l4',
      index: 4,
      instruction: 'You will hear someone giving a talk. Label the places (19–23) on the map (A–H). There are',
      emphasis: 'THREE extra options',
      durationSec: 0,
      choices: letters(8),
      map: {
        width: 320,
        height: 240,
        roads: [
          { points: [[10, 112], [310, 112]] },
          { points: [[110, 112], [110, 230]] },
          { points: [[230, 10], [230, 112]] },
        ],
        blocks: [
          { x: 20, y: 62, w: 55, h: 34, letter: 'A' },
          { x: 92, y: 62, w: 55, h: 34, letter: 'B' },
          { x: 162, y: 62, w: 55, h: 34, letter: 'C' },
          { x: 246, y: 28, w: 55, h: 34, letter: 'D' },
          { x: 246, y: 128, w: 55, h: 34, letter: 'E' },
          { x: 20, y: 128, w: 70, h: 34, letter: 'F' },
          { x: 148, y: 128, w: 64, h: 30, name: 'Main entrance' },
          { x: 126, y: 184, w: 55, h: 34, letter: 'G' },
          { x: 36, y: 186, w: 55, h: 34, letter: 'H' },
        ],
        labels: [
          { x: 60, y: 116, text: 'Campus Road' },
          { x: 110, y: 236, text: 'Library Walk' },
          { x: 230, y: 20, text: 'Park Lane' },
        ],
      },
      questions: [
        match('l', 19, 'Canteen', 'E'),
        match('l', 20, 'Sports field', 'G'),
        match('l', 21, 'Science building', 'D'),
        match('l', 22, 'Bookshop', 'A'),
        match(
          'l',
          23,
          'Student office',
          'C',
          '"Directly opposite the main entrance" — kiraverish qarshisida, yo\'lning shimoliy tomonida.',
        ),
      ],
    },
    {
      id: 'l5',
      index: 5,
      instruction: 'You will hear three extracts. Choose the correct answer (A, B or C) for each question. There are',
      emphasis: 'TWO questions for each extract',
      durationSec: 0,
      questions: [
        ...grouped('Extract One', [
          mcq('l', 24, 'Where are the friends going to camp?', ['by a lake', 'in the mountains', 'near the sea'], 'A'),
          mcq(
            'l',
            25,
            'What does Zarina still need to buy?',
            ['a tent', 'a sleeping bag', 'a torch'],
            'B',
            "Chodirni Bekzod olib keladi, chiroq esa uyda bor.",
          ),
        ]),
        ...grouped('Extract Two', [
          mcq(
            'l',
            26,
            'What gave Malika the idea for her app?',
            ["her grandmother's problem with remembering medicine", 'a project at school', 'a national competition'],
            'A',
          ),
          mcq(
            'l',
            27,
            'What does Malika find most difficult now?',
            ['learning new programming languages', 'finding investors', 'balancing her studies and her work'],
            'C',
          ),
        ]),
        ...grouped('Extract Three', [
          mcq('l', 28, 'What is the man complaining about?', ['loud music', 'a barking dog', 'building work'], 'B'),
          mcq(
            'l',
            29,
            'What do the neighbours decide to do?',
            ['call the police', 'talk to the owner together', 'write to the newspaper'],
            'B',
          ),
        ]),
      ],
    },
    {
      id: 'l6',
      index: 6,
      title: 'The history of paper',
      instruction: 'You will hear a part of a lecture. Fill in the missing information. Write',
      emphasis: 'no more than ONE WORD',
      durationSec: 0,
      questions: [
        gap('l', 30, 'Before paper, people in China wrote on bamboo and', 'silk'),
        gap('l', 31, 'Early paper was made from tree bark, old cloth and fishing', 'nets'),
        gap('l', 32, 'Paper-making reached Samarkand through Chinese', 'prisoners'),
        gap('l', 33, 'Samarkand paper was famous for being smooth and', 'strong'),
        gap('l', 34, 'In Europe, paper slowly replaced', 'parchment'),
        gap('l', 35, 'Most paper today is made from', 'wood'),
      ],
    },
  ],
  reading: [
    {
      id: 'r1',
      index: 1,
      title: 'Learning a language as an adult',
      instruction: 'Read the text. Fill in each gap with ONE word. You must use a word which is somewhere in the rest of the text.',
      passage: [
        {
          label: '1',
          text: 'Many people believe that only children can learn a new language well. However, research shows that (1) ______ can also become excellent speakers. In fact, adults often learn grammar faster than children, because they can use their knowledge of their first (2) ______.',
        },
        {
          label: '2',
          text: 'The biggest problem for adult learners is usually time. Busy people with jobs and families find it hard to (3) ______ every day. Experts say that short, regular practice is better than one long lesson a week. Even ten minutes a day can make a big (4) ______.',
        },
        {
          label: '3',
          text: 'Another important thing is not to be afraid of making (5) ______. Children make mistakes all the time and do not worry about them. Finally, it helps to find a (6) ______ — someone who speaks the language and wants to learn yours. Adults who practise with a partner often stay motivated for longer, and every small difference in your daily routine helps. So try to practise little and often.',
        },
      ],
      questions: [
        gap('r', 1, 'Research shows that (1) ______ can also become excellent speakers.', 'adults'),
        gap('r', 2, 'They can use their knowledge of their first (2) ______.', 'language'),
        gap('r', 3, 'Busy people find it hard to (3) ______ every day.', 'practise|practice'),
        gap('r', 4, 'Even ten minutes a day can make a big (4) ______.', 'difference'),
        gap('r', 5, 'Do not be afraid of making (5) ______.', 'mistakes'),
        gap('r', 6, 'It helps to find a (6) ______.', 'partner'),
      ],
    },
    {
      id: 'r2',
      index: 2,
      title: 'Online courses',
      instruction: 'Read the texts 7–14 and the statements A–J. Decide which text matches the situation in each statement. Each statement can be used ONCE only. There are TWO extra statements.',
      passage: [
        {
          label: '7',
          text: 'CODE STARTER — Learn programming from zero. Live lessons with a teacher every evening at 7 pm. Certificate at the end of the course.',
        },
        {
          label: '8',
          text: 'SPEAK UP ENGLISH — Conversation practice with native speakers in groups of four. Your first lesson is free, so you can see if it is right for you.',
        },
        {
          label: '9',
          text: 'PHOTO MASTER — Recorded video lessons that you can watch whenever you want. Pay once and keep access for life.',
        },
        {
          label: '10',
          text: 'KIDS SCIENCE LAB — Fun experiments for children aged 8–12. Parents receive a short report on their progress every week.',
        },
        {
          label: '11',
          text: 'BUSINESS ACCOUNTING — Our course prepares you for the official professional examination. Last year, 92% of our students passed.',
        },
        {
          label: '12',
          text: 'BALCONY GARDENING — A six-week course on growing vegetables in small spaces. A box of seeds and tools is posted to your home.',
        },
        {
          label: '13',
          text: 'CAREER COACH — One-to-one online sessions with an experienced adviser who will help you write your CV and prepare for job interviews.',
        },
        {
          label: '14',
          text: 'CHESS ACADEMY — Online tournaments every weekend. The best players win a place at the national championship.',
        },
      ],
      choices: choices([
        'You would like to receive materials by post.',
        'You want individual help to find a job.',
        'You want to try a lesson before paying.',
        'You want to learn how to cook.',
        'You want to study whenever it suits you.',
        'You need to prepare for an exam.',
        'You want to study with a teacher at a fixed time.',
        'You want to compete against other people.',
        'You are looking for a course for your child.',
        'You want to meet learners from your own city.',
      ]),
      questions: [
        match('r', 7, 'Text 7', 'G', '"Certificate" imtihon degani emas — F javobi 11-matnga tegishli.'),
        match('r', 8, 'Text 8', 'C'),
        match('r', 9, 'Text 9', 'E'),
        match('r', 10, 'Text 10', 'I'),
        match('r', 11, 'Text 11', 'F'),
        match('r', 12, 'Text 12', 'A'),
        match('r', 13, 'Text 13', 'B'),
        match('r', 14, 'Text 14', 'H'),
      ],
    },
    {
      id: 'r3',
      index: 3,
      title: 'Working from home',
      instruction: 'Read the text and choose the correct heading for each paragraph from the list of headings. There are more headings than paragraphs, so you will not use all of them.',
      passage: [
        {
          label: 'I',
          text: 'Until a few years ago, working from home was a privilege enjoyed by a small number of freelancers. Then, almost overnight, millions of office workers were told to stay at home and continue their jobs from kitchen tables and bedrooms. What began as an emergency soon became a normal way of working.',
        },
        {
          label: 'II',
          text: 'For many employees, the benefits were obvious. Without the daily journey to the office, they gained an hour or more every day. They also spent less on transport, lunches and work clothes, and some used the extra time to exercise or be with their children.',
        },
        {
          label: 'III',
          text: 'However, not everyone was happy. Many people found that they missed the small conversations in the corridor and the feeling of being part of a team. Young employees in particular said it was harder to learn from experienced colleagues when they could only see them on a screen.',
        },
        {
          label: 'IV',
          text: 'Employers have mixed feelings too. Some studies show that people working at home get more done, while others suggest the opposite. Much seems to depend on the type of job and on whether managers trust their staff to work without being watched.',
        },
        {
          label: 'V',
          text: 'Experts agree that a good home workplace makes a big difference. A proper desk and chair, natural light and a door that can be closed help people concentrate. It is also important to set clear hours, so that work does not take over the whole evening.',
        },
        {
          label: 'VI',
          text: 'For the future, most companies are choosing a mix of the two. Employees come to the office two or three days a week to meet and plan, and work from home on the other days. Many believe this combination offers the advantages of both systems.',
        },
      ],
      choices: choices([
        'Creating the right space',
        'The best of both worlds',
        'Mixed results for employers',
        'A sudden change',
        'Why cities are becoming empty',
        'Missing the office',
        'Time and money saved',
        'The end of business travel',
      ]),
      questions: [
        match('r', 15, 'Paragraph I', 'D'),
        match('r', 16, 'Paragraph II', 'G'),
        match('r', 17, 'Paragraph III', 'F'),
        match('r', 18, 'Paragraph IV', 'C'),
        match('r', 19, 'Paragraph V', 'A'),
        match('r', 20, 'Paragraph VI', 'B'),
      ],
    },
    {
      id: 'r4',
      index: 4,
      title: 'A guesthouse in the mountains',
      instruction: 'Read the text. For questions 21–24, choose the correct answer A, B, C or D. For questions 25–29, decide if the statements agree with the information in the text.',
      passage: [
        {
          label: '1',
          text: 'Six years ago I had a good job in an office in Tashkent, a comfortable flat and a busy social life. I also had a constant headache from the traffic and the noise. One evening, stuck in a traffic jam for the third time that week, I decided that I wanted a quieter life, and a month later I handed in my notice.',
        },
        {
          label: '2',
          text: 'I moved to a small village in the mountains where I had spent my summers as a child. My friends thought I was mad. The first winter was not easy. The cold I could deal with — I had bought plenty of wood — but I had never felt so lonely. Most of the young people had left for the cities, and the evenings were long and silent.',
        },
        {
          label: '3',
          text: 'In spring I started to repair my grandparents’ old house, with the idea of renting rooms to visitors. For the first year only a few guests came. Then a travel blogger stayed for a week and wrote about the views, the bread from my clay oven and the walks to the waterfall. Within a month I was fully booked for the whole summer.',
        },
        {
          label: '4',
          text: 'Electricity only arrived in the village ten years ago, and the road is still rough, but life here has changed a lot. Today I grow most of my own vegetables, and my neighbours sell honey, dried fruit and carpets to my guests. Most visitors come from Tashkent and Samarkand, although more people from abroad arrive every year.',
        },
        {
          label: '5',
          text: 'Some people say tourism will spoil places like this, and I understand their fears. But I have seen how it has given families a reason to stay in the village instead of leaving. As long as we keep it small and respect the mountains, I believe visitors can help this place survive.',
        },
      ],
      questions: [
        mcq(
          'r',
          21,
          'Why did the writer leave Tashkent?',
          ['She lost her job.', 'Her doctor told her to.', 'She wanted a quieter life.', 'Her family lived in the village.'],
          'C',
        ),
        mcq(
          'r',
          22,
          'What did the writer find hardest in her first winter?',
          ['the cold weather', 'feeling lonely', 'a lack of money', 'repairing the house'],
          'B',
          "Sovuq bilan kurashgan — o'tin olgan, eng qiyini yolg'izlik bo'lgan.",
        ),
        mcq(
          'r',
          23,
          'The guesthouse became popular after',
          [
            'a blogger wrote about it.',
            'she advertised it on television.',
            'a new road was built.',
            'she opened a restaurant.',
          ],
          'A',
        ),
        mcq(
          'r',
          24,
          'In the writer’s opinion, tourism',
          [
            'has already damaged the village.',
            'helps families to stay in the village.',
            'should be stopped completely.',
            'only benefits hotel owners.',
          ],
          'B',
        ),
        tfng(25, 'The writer knew the village before she moved there.', 'True'),
        tfng(26, 'The writer’s husband did not want to move.', 'No Information'),
        tfng(27, 'There is still no electricity in the village.', 'False'),
        tfng(28, 'The writer produces most of her own vegetables.', 'True'),
        tfng(
          29,
          'Most of the writer’s guests come from other countries.',
          'False',
          "Mehmonlarning ko'pchiligi Toshkent va Samarqanddan.",
        ),
      ],
    },
    {
      id: 'r5',
      index: 5,
      title: 'The Aral Sea',
      instruction: 'Read the text. For questions 30–33, fill in the missing information. Write no more than ONE WORD and / or A NUMBER. For questions 34–35, choose the correct answer A, B, C or D.',
      passage: [
        {
          label: '1',
          text: 'Sixty years ago, the Aral Sea was the fourth largest lake in the world. Fishing boats sailed from busy ports such as Muynak, and thousands of people worked in the fishing and canning industries. The sea was fed by two great rivers, the Amu Darya and the Syr Darya.',
        },
        {
          label: '2',
          text: 'In the 1960s, planners decided to take water from these rivers to grow cotton in the desert. The plan produced a great deal of cotton, but very little water reached the sea any more. Year after year, the shoreline moved further away, and today the sea has lost about ninety per cent of its water.',
        },
        {
          label: '3',
          text: 'The effects have been terrible. The fishing industry almost disappeared, and old ships now lie rusting in the sand, many kilometres from the water. Winds carry salt and dust from the dry seabed across the region, and local people have suffered from health problems.',
        },
        {
          label: '4',
          text: 'There are, however, some signs of hope. In 2005, a dam was completed in Kazakhstan to keep water in the northern part of the sea. Since then, the water level there has risen, the water has become less salty and fish have returned. In Uzbekistan, millions of trees have been planted on the dry seabed to stop the dust from blowing.',
        },
      ],
      questions: [
        gap('r', 30, 'The Aral Sea was once the … largest lake in the world.', 'fourth|4th'),
        gap('r', 31, 'Water from the rivers was used to grow', 'cotton'),
        gap('r', 32, 'The sea has lost about … per cent of its water.', '90|ninety'),
        gap('r', 33, 'In 2005, a … was completed to protect the northern part.', 'dam'),
        mcq(
          'r',
          34,
          'What happened to the fishing industry?',
          ['It moved to another sea.', 'It almost disappeared.', 'It grew larger.', 'It became illegal.'],
          'B',
        ),
        mcq(
          'r',
          35,
          'What is the writer’s main purpose?',
          [
            'to blame farmers for the disaster',
            'to explain the causes and effects of a disaster and some signs of hope',
            'to advertise tours to Muynak',
            'to compare the Aral Sea with other lakes',
          ],
          'B',
        ),
      ],
    },
  ],
  writing: writingPaper(
    {
      context: 'You stayed at a hotel in Samarkand last weekend, but several things went wrong during your stay.',
      prompt:
        'Write an email to the hotel manager. In your email:\n- explain why you chose this hotel;\n- describe what went wrong;\n- say what you would like the hotel to do.\nWrite about 150 words in an appropriate format and style.',
    },
    'Some people think that governments should spend more money on public transport. Others believe that building better roads is more important.\n\nDiscuss both views and give your opinion. Write at least 250 words in an appropriate style and format.',
  ),
  speaking: speakingQuestions({
    personal: [
      'What do you do? Do you work or study?',
      'How do you usually travel around your city?',
      'What was the last film or series you watched?',
    ],
    pictures:
      'Picture A: students studying together in a library · Picture B: a student studying alone at home with a laptop',
    compare: [
      'Compare the two pictures. What are the similarities and differences?',
      'Do you prefer studying alone or with other people? Why?',
      'How has technology changed the way students study?',
    ],
    monologue: {
      image: 'An old man telling stories to his grandchildren',
      prompt: 'Describe an older person you admire. Say who they are, what they have done and why you admire them.',
    },
    debate:
      'Mobile phones should be banned in schools. For: phones distract students and cause cheating. Against: phones are useful for learning and for safety. Give arguments for and against this statement and say what you think.',
  }),
  scripts: [
    script('l1', [
      intro('Part one. You will hear some sentences. Choose the correct reply to each sentence.'),
      cue(1, 'man', 'Excuse me, is anyone sitting here?', 2),
      cue(2, 'woman', 'What time does the next bus to the city centre leave?', 2),
      cue(3, 'man', "I'm so sorry I'm late, the traffic was terrible.", 2),
      cue(4, 'woman', 'Could you help me carry these boxes upstairs?', 2),
      cue(5, 'man', 'Would you like tea or coffee?', 2),
      cue(6, 'woman', "Guess what? I've just been offered a place at university!", 2),
      cue(7, 'man', 'Do you mind if I borrow your pen for a minute?', 2),
      cue(8, 'woman', 'So, how was your holiday in Khiva?', 2),
      outro('one'),
    ]),
    script('l2', [
      intro('Part two. You will hear a librarian giving a tour. Fill in the missing information. Write one word and, or, a number for each answer.'),
      say('woman', "Hello, everyone, and welcome to the Central Library. I'll show you around and explain how everything works."),
      cue(9, 'woman', "With your membership card you can borrow books for three weeks. Until last year the limit was four books, but now you can take up to six books at a time."),
      cue(10, 'woman', "The computers are on the second floor, and if you need somewhere quiet to work with friends, the study rooms are on the third floor. You can book them online."),
      cue(11, 'woman', "There are printers on every floor. They aren't free, I'm afraid. To use one, you need a code, which you can get from the librarian at the desk."),
      cue(12, 'woman', "Please return your books on time. If a book is late, the fine is two thousand som per day, so it's worth setting a reminder on your phone."),
      cue(13, 'woman', "On the ground floor there's a quiet zone. You can bring a bottle of water, but no food is allowed there, because it attracts insects."),
      cue(14, 'woman', "Finally, opening hours. We're open late on Fridays, until nine, and the library is closed every Sunday. Enjoy your reading!"),
      outro('two'),
    ]),
    script('l3', [
      intro('Part three. You will hear people speaking in different situations. Match each speaker to the place where the speaker is. There are two extra places which you do not need to use.'),
      speaker(15, 1),
      say('man', "Good evening. Are you ready to order? Today's special is lamb with rice and vegetables, and our chef recommends the apricot dessert. Can I get you anything to drink first?"),
      speaker(16, 2),
      say('woman', "Your boarding gate is number twelve, and boarding starts in forty minutes. Please keep your passport ready. If you need to change money, there's an exchange office just after security."),
      speaker(17, 3),
      say('man2', "If you'd like to watch the penguins being fed, come back here at two o'clock. And please remember, don't give the animals any of your own food. It can make them very ill."),
      speaker(18, 4),
      say('woman2', "Right, open your mouth and say 'ah'. Yes, your throat is quite red. Take these tablets twice a day after meals, drink plenty of water, and come back to see me if you're not better in a week."),
      outro('three'),
    ]),
    script('l4', [
      intro('Part four. You will hear someone giving a talk. Label the places on the map. There are three extra options which you do not need to use.'),
      say('man', "Welcome to the university. We're standing at the main entrance, on the south side of Campus Road. Let me show you where a few important places are."),
      cue(19, 'man', "If you're hungry, the canteen is very close. It's next to the main entrance, on its east side, on this side of the road."),
      cue(20, 'man', "The sports field is down Library Walk. Walk south all the way to the end, and you'll find it on your left-hand side."),
      cue(21, 'man', "For the science building, go east along Campus Road and turn left into Park Lane. Walk north, and the science building is on your right."),
      cue(22, 'man', "The bookshop is at the far western end of Campus Road, on the north side."),
      cue(23, 'man', "And finally, the student office, where you'll collect your ID card. It's directly opposite the main entrance, on the other side of Campus Road."),
      outro('four'),
    ]),
    script('l5', [
      intro('Part five. You will hear three extracts. Choose the correct answer for each question. There are two questions for each extract.'),
      say('narrator', 'Extract one. You will hear two friends planning a camping trip.'),
      say('man', "So, Zarina, are we still going camping in the mountains this weekend?"),
      cue(24, 'woman', "Actually, I've changed my mind. It's going to be really cold up there. Let's camp by the lake instead. It's warmer, and we can swim."),
      cue(25, 'woman', "You're bringing your tent, aren't you? Good. I've got a torch at home, but my old sleeping bag is broken, so I'll buy a new one tomorrow."),
      say('narrator', 'Extract two. You will hear part of an interview with a young app developer.'),
      say('woman2', "Malika, your app has been downloaded half a million times. Where did the idea come from?"),
      cue(26, 'woman3', "From my grandmother, really. She takes several kinds of medicine and kept forgetting which ones she'd taken. So I built a simple app that reminds her. It wasn't a school project or anything like that."),
      cue(27, 'woman3', "I learnt to code on my own, and investors found me quite quickly. The hard part now is time. I'm still at university, and balancing my studies and the company is really difficult."),
      say('narrator', 'Extract three. You will hear two neighbours talking.'),
      cue(28, 'man2', "Excuse me, do you live in flat twelve? The dog next door has been barking all night again. It's not the music, that stopped weeks ago, but I just can't sleep."),
      cue(29, 'woman', "I know, it's terrible for me too. I don't want to call the police. Why don't we go and talk to the owner together this evening? I'm sure she doesn't realise."),
      outro('five'),
    ]),
    script('l6', [
      intro('Part six. You will hear a part of a lecture. Fill in the missing information. Write no more than one word for each answer.'),
      say('man3', "Today we're going to look at the history of something we use every day without thinking about it: paper."),
      cue(30, 'man3', "Before paper was invented, people in China wrote on strips of bamboo, which were heavy, and on silk, which was very expensive."),
      cue(31, 'man3', "Around two thousand years ago, the first real paper was made in China from tree bark, old pieces of cloth and even old fishing nets."),
      cue(32, 'man3', "For centuries, the method was kept secret. According to tradition, it reached Samarkand in the eighth century, when Chinese prisoners taught local craftsmen how to make it."),
      cue(33, 'man3', "Samarkand paper soon became famous across the Islamic world. It was smooth and strong, and it was used for books, letters and maps."),
      cue(34, 'man3', "When paper finally arrived in Europe, it slowly replaced parchment, which was made from animal skin and cost a great deal."),
      cue(35, 'man3', "Today, of course, most paper is made from wood, although more and more is now recycled."),
      outro('six'),
    ]),
  ],
};
