import {
  ask,
  cue,
  gap,
  intro,
  mcq,
  outro,
  say,
  script,
  speaker,
  speakingQuestions,
  tfng,
  writingTasks,
} from '../builders';
import type { TestContent } from '../types';

export const content: TestContent = {
  listening: [
    {
      id: 'l1',
      index: 1,
      instruction: 'You will hear some short conversations. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq('l', 1, 'What does the man want to buy?', ['A jacket', 'A pair of shoes', 'A shirt'], 'B'),
        mcq('l', 2, 'Where will the friends meet?', ['At the cinema', 'At the bus stop', 'At the park gate'], 'C'),
        mcq('l', 3, 'What is the woman’s new job?', ['Teacher', 'Nurse', 'Accountant'], 'A'),
        mcq(
          'l',
          4,
          'How will they get to the airport?',
          ['By taxi', 'By train', 'By car'],
          'B',
          "Taksi qimmat, mashinada joy yo'q — poyezd.",
        ),
        mcq('l', 5, 'What did the boy forget?', ['His homework', 'His lunch', 'His sports kit'], 'C'),
        mcq('l', 6, 'When is the concert?', ['On Friday', 'On Saturday', 'On Sunday'], 'B'),
        mcq('l', 7, 'What is wrong with the room?', ['It is too small', 'It is noisy', 'It is cold'], 'B'),
        mcq(
          'l',
          8,
          'How many people are coming to dinner?',
          ['Four', 'Six', 'Eight'],
          'B',
          'Sakkiz kishi taklif qilingan, lekin ikki kishi kela olmaydi.',
        ),
      ],
    },
    {
      id: 'l2',
      index: 2,
      title: 'Sunrise Fitness Club — New Members',
      instruction: 'Complete the notes. Write',
      emphasis: 'no more than two words',
      durationSec: 0,
      questions: [
        gap('l', 9, 'Opening time on weekdays:', '6 am|6 a.m.'),
        gap('l', 10, 'Monthly fee: £', '25', 'Odatiy narx 30, lekin talabalar uchun 25.'),
        gap('l', 11, 'Joining requires a recent', 'photo|photograph'),
        gap('l', 12, 'First personal training session is', 'free'),
        gap('l', 13, 'Yoga classes take place on', 'Wednesday|Wednesdays'),
        gap('l', 14, 'Lockers are next to the', 'reception'),
        gap('l', 15, 'Members should bring a', 'towel'),
        gap('l', 16, 'Car park is at the', 'back'),
      ],
    },
    {
      id: 'l3',
      index: 3,
      instruction: 'You will hear six people talking about their holidays. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq('l', 17, 'Speaker 1 enjoyed her holiday mainly because of', ['the food', 'the people', 'the beaches'], 'A'),
        mcq('l', 18, 'Speaker 2 had a problem with', ['his hotel', 'his luggage', 'the weather'], 'B'),
        mcq('l', 19, 'Speaker 3 travelled', ['alone', 'with friends', 'with her family'], 'A'),
        mcq('l', 20, 'Speaker 4 prefers holidays', ['in the mountains', 'by the sea', 'in big cities'], 'A'),
        mcq('l', 21, 'Speaker 5 says his trip was', ['too expensive', 'too short', 'too tiring'], 'B'),
        mcq('l', 22, 'Speaker 6 wants to go back to learn', ['the language', 'to cook', 'to dive'], 'A'),
      ],
    },
    {
      id: 'l4',
      index: 4,
      instruction: 'Listen to an interview with a university librarian. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          23,
          'The librarian says students today mostly use the library to',
          ['borrow books', 'study in groups', 'print documents'],
          'B',
        ),
        mcq(
          'l',
          24,
          'The biggest change in recent years has been',
          ['longer opening hours', 'digital resources', 'a new building'],
          'B',
        ),
        mcq('l', 25, 'What do students complain about most?', ['Noise', 'The Wi-Fi', 'The lack of seats'], 'C'),
        mcq('l', 26, 'The library plans to', ['open a café', 'build a quiet floor', 'stay open all night'], 'B'),
        mcq(
          'l',
          27,
          'She thinks paper books will',
          ['disappear soon', 'remain important', 'become more expensive'],
          'B',
        ),
      ],
    },
    {
      id: 'l5',
      index: 5,
      title: 'Old Town Walking Tour',
      instruction: 'Complete the notes. Write',
      emphasis: 'one word or a number',
      durationSec: 0,
      questions: [
        gap('l', 28, 'Tour meeting point: the old', 'clock|clock tower'),
        gap('l', 29, 'Number of stops on the tour:', '7|seven'),
        gap('l', 30, 'Tour finishes at the', 'market'),
      ],
    },
    {
      id: 'l6',
      index: 6,
      instruction: 'Listen to a lecture about social media. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          31,
          'On average, young people spend on social media',
          ['one hour a day', 'three hours a day', 'six hours a day'],
          'B',
        ),
        mcq(
          'l',
          32,
          'The lecturer says the main risk is',
          ['losing sleep', 'comparing ourselves to others', 'sharing personal data'],
          'B',
        ),
        mcq(
          'l',
          33,
          'Social media can be positive when it helps people',
          ['earn money', 'stay in touch', 'learn to code'],
          'B',
        ),
        mcq('l', 34, 'In the study, students who took a break felt', ['bored', 'happier', 'more stressed'], 'B'),
        mcq(
          'l',
          35,
          'The lecturer recommends',
          ['deleting all apps', 'turning off notifications', 'using only one app'],
          'B',
        ),
      ],
    },
  ],
  reading: [
    {
      id: 'r1',
      index: 1,
      title: 'Notice: City Swimming Competition',
      instruction: 'Read the text and fill in the gaps. Write one word only.',
      passage: [
        {
          label: 'A',
          text: 'The City Swimming Competition for young people aged ten to sixteen will be held at the Olympic Pool on 3 June. Registration closes on 20 May.',
        },
        {
          label: 'B',
          text: 'Each swimmer may enter up to three races. The registration fee is five pounds, and all participants will receive a free T-shirt.',
        },
        {
          label: 'C',
          text: 'Parents are welcome to watch from the upper seating area. Please note that photography near the pool is not allowed.',
        },
      ],
      questions: [
        gap('r', 1, 'The competition takes place at the Olympic', 'pool'),
        gap('r', 2, 'The oldest swimmers can be', 'sixteen|16'),
        gap('r', 3, 'Registration ends in', 'May'),
        gap('r', 4, 'A swimmer can enter a maximum of three', 'races'),
        gap('r', 5, 'Every participant gets a free', 'T-shirt|tshirt'),
        gap('r', 6, 'Parents sit in the upper seating', 'area'),
        gap('r', 7, 'Taking photos near the pool is not', 'allowed'),
      ],
    },
    {
      id: 'r2',
      index: 2,
      title: 'Short Messages',
      instruction: 'Read the messages and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Hi Dilnoza! Mum’s birthday dinner is at 8 on Saturday at the Silk Road restaurant. I’ve ordered the cake — could you buy the flowers?',
        },
        {
          label: 'B',
          text: 'Notice to residents: water will be switched off on Wednesday from 9 am to 1 pm while pipes are replaced.',
        },
        {
          label: 'C',
          text: 'Your order #4521 has been sent. It will arrive within three working days. You can track it on our website.',
        },
      ],
      questions: [
        mcq('r', 8, 'What is the dinner for?', ['A wedding', 'A birthday', 'A graduation'], 'B'),
        mcq('r', 9, 'What should Dilnoza buy?', ['A cake', 'Flowers', 'A present'], 'B'),
        mcq(
          'r',
          10,
          'Why will the water be switched off?',
          ['To clean the tanks', 'To replace pipes', 'To save water'],
          'B',
        ),
        mcq('r', 11, 'For how long will there be no water?', ['Two hours', 'Four hours', 'All day'], 'B'),
        mcq('r', 12, 'When will the order arrive?', ['Tomorrow', 'Within three working days', 'Next week'], 'B'),
        mcq('r', 13, 'How can the customer check the delivery?', ['By phone', 'On the website', 'By email'], 'B'),
        mcq('r', 14, 'Which message is from a family member?', ['A', 'B', 'C'], 'A'),
      ],
    },
    {
      id: 'r3',
      index: 3,
      title: 'Learning a Language as an Adult',
      instruction: 'Read the article and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Many adults believe they are too old to learn a new language. Research, however, shows that adults can learn grammar and vocabulary faster than children.',
        },
        {
          label: 'B',
          text: 'What children do better is pronunciation. Young learners often develop a native-like accent, which is much harder for adults.',
        },
        {
          label: 'C',
          text: 'Experts say the key for adults is regular practice. Twenty minutes a day is more effective than two hours once a week.',
        },
        {
          label: 'D',
          text: 'Motivation also matters. Adults who learn a language for a clear reason, such as a job or travel, usually make faster progress.',
        },
      ],
      questions: [
        mcq(
          'r',
          15,
          'Many adults wrongly believe that they',
          ['learn slowly', 'are too old to learn', 'need a teacher'],
          'B',
        ),
        mcq(
          'r',
          16,
          'Adults learn faster than children in',
          ['grammar and vocabulary', 'pronunciation', 'listening'],
          'A',
        ),
        mcq('r', 17, 'Children are better at', ['reading', 'accent', 'writing'], 'B'),
        mcq('r', 18, 'Experts recommend', ['long lessons', 'short daily practice', 'weekend courses'], 'B'),
        mcq(
          'r',
          19,
          'Which learners usually progress faster?',
          ['Those with a clear reason', 'Those who study grammar', 'Those who travel often'],
          'A',
        ),
        mcq('r', 20, 'The word “effective” is closest to', ['successful', 'difficult', 'expensive'], 'A'),
        mcq('r', 21, 'The best title is', ['Never Too Late', 'Why Children Learn Faster', 'The Perfect Accent'], 'A'),
      ],
    },
    {
      id: 'r4',
      index: 4,
      title: 'The Aral Sea: A Story of Loss and Hope',
      instruction: 'Do the following statements agree with the information in the text?',
      passage: [
        {
          label: 'A',
          text: 'Once the fourth-largest lake in the world, the Aral Sea began to shrink in the 1960s, when rivers that fed it were used to water cotton fields.',
        },
        {
          label: 'B',
          text: 'By the 2000s, the sea had split into several smaller lakes, and many fishing towns found themselves far from the water.',
        },
        {
          label: 'C',
          text: 'In 2005, a dam was built to protect the northern part of the sea. Since then, water levels there have risen and some fish have returned.',
          highlight: 'water levels there have risen and some fish have returned',
        },
        {
          label: 'D',
          text: 'Scientists are now planting desert plants on the dry seabed to stop salt and dust from spreading to nearby villages.',
        },
      ],
      questions: [
        tfng(22, 'The Aral Sea started to shrink in the 1960s.', 'True'),
        tfng(23, 'The rivers were used to produce electricity.', 'False'),
        tfng(
          24,
          'The northern part of the sea has improved since 2005.',
          'True',
          "C paragrafi: suv sathi ko'tarilgan, baliqlar qaytgan.",
        ),
        tfng(25, 'The dam cost more than one billion dollars.', 'Not given'),
        tfng(26, 'Plants are being grown on the dry seabed.', 'True'),
      ],
    },
    {
      id: 'r5',
      index: 5,
      title: 'The Power of Walking',
      instruction: 'Read the text and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Walking is one of the simplest ways to stay healthy. Doctors recommend around seven thousand steps a day, not ten thousand as many people think.',
        },
        {
          label: 'B',
          text: 'A thirty-minute walk can improve mood, reduce stress and even help people sleep better at night.',
        },
        {
          label: 'C',
          text: 'Walking also helps creativity. In one study, people came up with sixty percent more ideas while walking than while sitting.',
        },
        {
          label: 'D',
          text: 'Best of all, walking is free and needs no special equipment — just a comfortable pair of shoes.',
        },
      ],
      questions: [
        mcq('r', 27, 'How many steps do doctors recommend?', ['5,000', '7,000', '10,000'], 'B'),
        mcq(
          'r',
          28,
          'The number “ten thousand” is described as',
          ['a scientific fact', 'a common belief', 'the minimum'],
          'B',
        ),
        mcq(
          'r',
          29,
          'A thirty-minute walk can help people to',
          ['lose weight quickly', 'sleep better', 'build muscles'],
          'B',
        ),
        mcq('r', 30, 'In the study, walking increased ideas by', ['16%', '40%', '60%'], 'C'),
        mcq(
          'r',
          31,
          'What equipment does walking need?',
          ['None except shoes', 'A fitness watch', 'Special clothes'],
          'A',
        ),
        mcq('r', 32, 'The word “reduce” is closest to', ['increase', 'lower', 'cause'], 'B'),
        mcq('r', 33, 'Paragraph C is mainly about', ['health', 'creativity', 'cost'], 'B'),
        mcq('r', 34, 'The writer’s attitude to walking is', ['critical', 'neutral', 'enthusiastic'], 'C'),
        mcq(
          'r',
          35,
          'The main idea of the text is that walking',
          ['is easy and beneficial', 'is boring', 'is only for older people'],
          'A',
        ),
      ],
    },
  ],
  writing: writingTasks(
    'You and your friends are planning a trip to Samarkand next month. You have received this message from the travel agency:\n\n"Unfortunately, the hotel you booked is no longer available. We can offer you a hotel outside the city centre at the same price, or return your money."',
    'Write a message to a friend who is going on the trip with you. Tell them about the news and say which option you prefer and why. Write about 50 words.',
    'Write a letter to the travel agency manager. Say how you feel about the situation, which option you choose and what else you expect from the agency. Write 120–150 words.',
    'Some people say that it is better to live in a big city, while others prefer life in a small town or village. Discuss both views and give your own opinion. Write at least 180 words.',
  ),
  speaking: speakingQuestions({
    personal: [
      'What do you do? Do you work or study?',
      'How do you usually travel around your city?',
      'What was the last film or series you watched?',
    ],
    pictures:
      'Picture A: students studying together in a library · Picture B: a student studying alone at home with a laptop',
    compare: [
      'Compare the two pictures. What are the similarities and differences?',
      'Do you prefer studying alone or with other people? Why?',
      'How has technology changed the way students study?',
    ],
    monologue: {
      image: 'An old man telling stories to his grandchildren',
      prompt: 'Describe an older person you admire. Say who they are, what they have done and why you admire them.',
    },
    debate:
      'Mobile phones should be banned in schools. For: phones distract students and cause cheating. Against: phones are useful for learning and for safety. Give arguments for and against this statement and say what you think.',
  }),
  scripts: [
    script('l1', [
      intro('Part one. You will hear some short conversations. For each question, choose the correct answer.'),
      ask(1, 'What does the man want to buy?'),
      say('woman', 'Can I help you? Are you looking for a jacket? They are all half price today.'),
      say(
        'man',
        "Thanks, but I've got enough jackets. I need a pair of shoes for my sister's wedding. Something black and smart.",
        2,
      ),
      ask(2, 'Where will the friends meet?'),
      say('man', 'Shall we meet at the bus stop and walk to the park together?'),
      say(
        'woman',
        "It's quicker if I go straight there. Let's meet at the park gate, the main one opposite the cinema.",
        2,
      ),
      ask(3, 'What is the woman’s new job?'),
      say('man', 'I heard you left the hospital. Are you still working as a nurse?'),
      say(
        'woman',
        "No, I've changed careers completely. I'm teaching English at a secondary school now, and I love it.",
        2,
      ),
      ask(4, 'How will they get to the airport?'),
      say('woman', 'Should we take a taxi to the airport?'),
      say(
        'man',
        "It's far too expensive at that time, and my car is full of boxes. Let's take the train. It's fast and it goes right to the terminal.",
        2,
      ),
      ask(5, 'What did the boy forget?'),
      say('woman', 'Have you got everything for school? Your homework? Your lunch box?'),
      say(
        'man2',
        "Yes, Mum, they're both in my bag. Oh no, I've left my sports kit in the hall, and we've got football today!",
        2,
      ),
      ask(6, 'When is the concert?'),
      say('man', 'Is the concert on Friday evening?'),
      say(
        'woman',
        "No, Friday is the rehearsal. The concert is on Saturday, and on Sunday they're playing in another city.",
        2,
      ),
      ask(7, 'What is wrong with the room?'),
      say(
        'woman',
        "Excuse me, I'd like to change rooms. It's big and warm enough, but it's right above the street, and the traffic is so loud I can't sleep.",
        2,
      ),
      ask(8, 'How many people are coming to dinner?'),
      say('man', 'How many people did you invite to dinner on Saturday?'),
      say('woman', "I invited eight, but the Rahimovs can't come because they'll be away. So we'll be six.", 2),
      outro('one'),
    ]),
    script('l2', [
      intro(
        'Part two. You will hear a phone call to a fitness club. Complete the notes. Write no more than two words.',
      ),
      say('man', 'Sunrise Fitness Club, how can I help?'),
      say('woman', "Hi, I'm thinking of joining. What are your opening hours?"),
      cue(9, 'man', 'At weekends we open at eight, but on weekdays we open at six a.m. and close at ten at night.'),
      say('woman', 'And how much is the membership?'),
      cue(10, 'man', "The standard fee is thirty pounds a month. Are you a student? Then it's twenty-five pounds."),
      say('woman', 'Yes, I am. What do I need to join?'),
      cue(11, 'man', 'Just bring your student card and a recent photo for your membership card.'),
      cue(12, 'man', 'Also, your first personal training session is free, so a trainer can make a plan for you.'),
      say('woman', 'Do you have yoga classes?'),
      cue(13, 'man', 'Yes, on Wednesday evenings. We used to have them on Mondays, but Wednesday is more popular.'),
      say('woman', 'Where can I leave my things?'),
      cue(14, 'man', 'The lockers are next to the reception, and they are free to use.'),
      cue(15, 'man', "We don't provide towels, so please remember to bring a towel with you."),
      say('woman', 'And is there parking?'),
      cue(16, 'man', "Yes, there's a free car park at the back of the building. The front is for buses only."),
      say('woman', 'Great, thanks a lot.', 2),
      outro('two'),
    ]),
    script('l3', [
      intro(
        'Part three. You will hear six people talking about their holidays. For each speaker, choose the correct answer.',
      ),
      speaker(17, 1),
      say(
        'woman',
        "The beaches were nice, and people were friendly enough. But what I'll remember is the food. Every meal was an adventure, and I tried dishes I'd never heard of.",
        2,
      ),
      speaker(18, 2),
      say(
        'man',
        'The hotel was lovely and the weather was perfect. The only problem was that the airline lost my suitcase, and I spent the first three days in the same clothes.',
        2,
      ),
      speaker(19, 3),
      say(
        'woman2',
        "My friends couldn't get time off work, so for the first time I went on my own. I was nervous at first, but it was the best trip of my life.",
        2,
      ),
      speaker(20, 4),
      say(
        'man2',
        'Beaches bore me, and big cities are too crowded. Give me the mountains any time: fresh air, long walks and complete silence.',
        2,
      ),
      speaker(21, 5),
      say(
        'man3',
        "It wasn't cheap, but it was worth every penny. My only complaint is that five days wasn't enough. I needed at least two weeks.",
        2,
      ),
      speaker(22, 6),
      say(
        'woman3',
        "I loved the food, and I went diving twice. But I couldn't talk to anyone, so I want to go back after I've learned some of the language.",
        2,
      ),
      outro('three'),
    ]),
    script('l4', [
      intro('Part four. You will hear an interview with a university librarian. Choose the correct answer.'),
      say(
        'man',
        'My guest today is Mrs Nazarova, head librarian at the State University. How do students use the library today?',
      ),
      cue(
        23,
        'woman',
        'Far fewer students borrow books than before, and most print at home. Today they mainly come to study in groups. Our group rooms are always full.',
      ),
      cue(
        24,
        'woman',
        'The biggest change has been digital resources. Students can read thousands of journals and e-books online, even at home.',
      ),
      say('man', 'What do students complain about?'),
      cue(
        25,
        'woman',
        "Sometimes the Wi-Fi, and sometimes noise. But the most common complaint is that there aren't enough seats, especially before exams.",
      ),
      say('man', 'Any plans for the future?'),
      cue(
        26,
        'woman',
        'People keep asking for a café, and some want us open all night. But our main plan is to build a completely quiet floor for individual study.',
      ),
      say('man', 'Do paper books have a future?'),
      cue(
        27,
        'woman',
        'Definitely. Many students tell me they concentrate better with paper. I think printed books will remain important for a long time.',
        2,
      ),
      outro('four'),
    ]),
    script('l5', [
      intro(
        'Part five. You will hear a guide at the start of a walking tour. Complete the notes. Write one word or a number.',
      ),
      cue(
        28,
        'man',
        "Good morning, everyone! If you're here for the Old Town walking tour, you're in the right place: we always meet here, at the old clock tower.",
      ),
      cue(
        29,
        'man',
        "The tour lasts about two hours and has seven stops, including the old mosque and the craftsmen's street.",
      ),
      cue(30, 'man', "We'll finish at the market, where you can try local bread and dried fruit. Let's go!", 2),
      outro('five'),
    ]),
    script('l6', [
      intro('Part six. You will hear a lecture about social media. Choose the correct answer.'),
      cue(
        31,
        'woman',
        "Good afternoon. Let's start with a number. Studies show that young people spend on average three hours a day on social media. For some, it's much more, even six hours.",
      ),
      cue(
        32,
        'woman',
        'Many people worry about privacy or losing sleep, and these are real problems. But I believe the main risk is that we constantly compare ourselves to others, and that makes us feel worse about our own lives.',
      ),
      cue(
        33,
        'woman',
        "Of course, social media isn't all bad. It can be very positive when it helps people stay in touch with family and friends who live far away.",
      ),
      cue(
        34,
        'woman',
        "In one study, students stopped using social media for a week. Surprisingly, they didn't feel bored or stressed. Most said they felt happier and slept better.",
      ),
      cue(
        35,
        'woman',
        'So, do you need to delete all your apps? No. My recommendation is simpler: turn off notifications, and decide yourself when to check your phone. Thank you.',
        2,
      ),
      say('narrator', 'That is the end of the listening test.'),
    ]),
  ],
};
