import {
  choices,
  cue,
  gap,
  grouped,
  intro,
  letters,
  match,
  mcq,
  outro,
  say,
  script,
  speaker,
  speakingQuestions,
  tfng,
  writingPaper,
} from '../builders';
import type { TestContent } from '../types';

export const content: TestContent = {
  listening: [
    {
      id: 'l1',
      index: 1,
      instruction: 'You will hear some sentences. Choose the correct reply to each sentence.',
      emphasis: 'A, B or C',
      durationSec: 0,
      questions: [
        mcq('l', 1, '', ['Yes, of course.', 'It costs ten dollars.', 'I paid yesterday.'], 'A'),
        mcq('l', 2, '', ["I'll open the door.", "I think they're on the kitchen table.", "No, I haven't got a car."], 'B'),
        mcq('l', 3, '', ['Good idea, it gets busy on Fridays.', 'It was delicious.', 'Yes, I booked it last week.'], 'A'),
        mcq('l', 4, '', ['See you there!', 'Thanks for coming.', "That's a pity, maybe next time."], 'C'),
        mcq('l', 5, '', ["Yes, it's the third stop.", "It's a fast train.", "No, I'm going there too."], 'A'),
        mcq('l', 6, '', ["I've already had lunch.", "Sounds great, let's go to the park.", 'I walked there.'], 'B'),
        mcq('l', 7, '', ['Let me get you a plaster.', "It's very sharp.", 'Well done!'], 'A'),
        mcq(
          'l',
          8,
          '',
          ['She teaches maths.', "I'll ask her.", "She's strict, but her lessons are interesting."],
          'C',
          "Fikr so'ralmoqda (\"What do you think of...?\"), shuning uchun baho beradigan javob kerak.",
        ),
      ],
    },
    {
      id: 'l2',
      index: 2,
      title: 'Summer Language Camp — information',
      instruction: 'You will hear a camp director talking to parents. Fill in the missing information. Write',
      emphasis: 'ONE WORD and / or A NUMBER',
      durationSec: 0,
      questions: [
        gap('l', 9, 'The camp starts on … July', '15|15th|fifteenth', "1-iyul — ro'yxatdan o'tish oxirgi kuni, lager esa 15-iyulda boshlanadi."),
        gap('l', 10, 'Each room is for … students', '3|three'),
        gap('l', 11, 'For the pool, students must bring a swimming', 'cap'),
        gap('l', 12, 'Saturday trip: a walk to a', 'waterfall'),
        gap('l', 13, 'Phones can only be used in the', 'evening|evenings'),
        gap('l', 14, 'The price includes everything except', 'insurance'),
      ],
    },
    {
      id: 'l3',
      index: 3,
      instruction: 'You will hear people speaking in different situations. Match each speaker (15–18) to the place where the speaker is (A–F). There are',
      emphasis: 'TWO EXTRA places',
      durationSec: 0,
      choices: choices([
        "at a hairdresser's",
        'in a library',
        'at a petrol station',
        'in a clothes shop',
        'at a swimming pool',
        "at the dentist's",
      ]),
      questions: [
        match('l', 15, 'Speaker 1', 'D'),
        match('l', 16, 'Speaker 2', 'E'),
        match('l', 17, 'Speaker 3', 'A', '"Wash first", "a little off the sides" — sartaroshxona iboralari.'),
        match('l', 18, 'Speaker 4', 'C'),
      ],
    },
    {
      id: 'l4',
      index: 4,
      instruction: 'You will hear someone giving a talk. Label the places (19–23) on the map (A–H). There are',
      emphasis: 'THREE extra options',
      durationSec: 0,
      choices: letters(8),
      map: {
        width: 320,
        height: 240,
        roads: [
          { points: [[10, 130], [310, 130]] },
          { points: [[200, 10], [200, 130]] },
          { points: [[80, 130], [80, 230]] },
        ],
        blocks: [
          { x: 18, y: 84, w: 52, h: 32, letter: 'A' },
          { x: 100, y: 84, w: 60, h: 32, name: 'Clock tower' },
          { x: 130, y: 28, w: 52, h: 32, letter: 'D' },
          { x: 216, y: 28, w: 52, h: 32, letter: 'B' },
          { x: 216, y: 84, w: 52, h: 32, letter: 'C' },
          { x: 14, y: 146, w: 50, h: 32, letter: 'E' },
          { x: 96, y: 146, w: 60, h: 32, letter: 'F' },
          { x: 96, y: 192, w: 60, h: 32, letter: 'G' },
          { x: 240, y: 146, w: 60, h: 32, letter: 'H' },
        ],
        labels: [
          { x: 270, y: 134, text: 'Bazaar Street' },
          { x: 200, y: 20, text: 'Mosque Road' },
          { x: 80, y: 236, text: 'Garden Street' },
        ],
      },
      questions: [
        match('l', 19, 'Carpet shop', 'A'),
        match('l', 20, 'Tea house', 'D'),
        match(
          'l',
          21,
          'Pharmacy',
          'C',
          'Burchakda, Mosque Road ning sharqiy tomonida. B ham sharqda, lekin yuqorida.',
        ),
        match('l', 22, 'Museum', 'G'),
        match('l', 23, 'Hotel', 'H'),
      ],
    },
    {
      id: 'l5',
      index: 5,
      instruction: 'You will hear three extracts. Choose the correct answer (A, B or C) for each question. There are',
      emphasis: 'TWO questions for each extract',
      durationSec: 0,
      questions: [
        ...grouped('Extract One', [
          mcq(
            'l',
            24,
            'What topic have the students chosen for their project?',
            ['recycling', 'public transport', 'local history'],
            'A',
          ),
          mcq(
            'l',
            25,
            'Who will give the presentation?',
            ['Anvar', 'Dilnoza', 'both of them'],
            'C',
          ),
        ]),
        ...grouped('Extract Two', [
          mcq(
            'l',
            26,
            'Why did Nigora start running?',
            ['to lose weight', 'to get stronger after an illness', 'because a friend advised her'],
            'B',
          ),
          mcq(
            'l',
            27,
            'What is her main advice for beginners?',
            ['Buy expensive running shoes.', 'Run every single day.', 'Increase the distance slowly.'],
            'C',
            "Qimmat poyabzal shart emas, har kuni yugurish ham noto'g'ri deydi.",
          ),
        ]),
        ...grouped('Extract Three', [
          mcq(
            'l',
            28,
            'What is wrong with the customer’s phone?',
            ['The screen is cracked.', 'The battery runs out quickly.', 'It is the wrong colour.'],
            'B',
          ),
          mcq(
            'l',
            29,
            'What will the shop do?',
            ['give her money back', 'repair the phone', 'give her a new phone'],
            'C',
          ),
        ]),
      ],
    },
    {
      id: 'l6',
      index: 6,
      title: 'The life of honey bees',
      instruction: 'You will hear a part of a lecture. Fill in the missing information. Write',
      emphasis: 'no more than ONE WORD',
      durationSec: 0,
      questions: [
        gap('l', 30, 'Each colony has only one', 'queen'),
        gap('l', 31, 'Workers show where flowers are by performing a', 'dance'),
        gap('l', 32, 'Honey lasts a long time because it contains very little', 'water'),
        gap('l', 33, 'Bees keep the hive at a steady', 'temperature'),
        gap('l', 34, 'About a third of our food depends on', 'pollination'),
        gap('l', 35, 'Bees are threatened by disease and', 'pesticides|chemicals'),
      ],
    },
  ],
  reading: [
    {
      id: 'r1',
      index: 1,
      title: 'The benefits of walking',
      instruction: 'Read the text. Fill in each gap with ONE word. You must use a word which is somewhere in the rest of the text.',
      passage: [
        {
          label: '1',
          text: 'Many people spend hours sitting at a desk every day. Walking is one of the easiest ways to stay healthy, and you do not need special (1) ______ or a gym membership — just a good pair of shoes. Doctors say that thirty minutes of walking a (2) ______ can lower the risk of heart disease.',
        },
        {
          label: '2',
          text: 'Walking is also good for the mind. People who walk regularly often feel less (3) ______ and sleep better. If you live near your office, try walking to (4) ______ instead of taking the bus. You can also walk with friends or family; it is a good way to (5) ______ time with people you love.',
        },
        {
          label: '3',
          text: 'Many cities now have special paths for walkers, and some offer free guided walks every (6) ______. So put on your shoes: you need no equipment, just thirty minutes a day. Walking to work keeps you fit and less stressed. Why not join a guided walk this weekend?',
        },
      ],
      questions: [
        gap('r', 1, 'You do not need special (1) ______ or a gym membership.', 'equipment'),
        gap('r', 2, 'Thirty minutes of walking a (2) ______ can lower the risk of heart disease.', 'day'),
        gap('r', 3, 'People who walk regularly often feel less (3) ______.', 'stressed'),
        gap('r', 4, 'Try walking to (4) ______ instead of taking the bus.', 'work'),
        gap('r', 5, 'It is a good way to (5) ______ time with people you love.', 'spend'),
        gap('r', 6, 'Some cities offer free guided walks every (6) ______.', 'weekend'),
      ],
    },
    {
      id: 'r2',
      index: 2,
      title: 'Places to eat',
      instruction: 'Read the texts 7–14 and the statements A–J. Decide which text matches the situation in each statement. Each statement can be used ONCE only. There are TWO extra statements.',
      passage: [
        { label: '7', text: 'GREEN LEAF — Vegetarian dishes only. Fresh salads, soups and homemade bread every day.' },
        { label: '8', text: 'PIZZA EXPRESS — Order online and we deliver to your door within 30 minutes. Delivery is always free.' },
        { label: '9', text: 'SAMARKAND HOUSE — Traditional dishes and live music by local musicians every Friday and Saturday evening.' },
        { label: '10', text: 'FAMILY CORNER — A safe play area for little ones, high chairs and a special children’s menu.' },
        { label: '11', text: 'MORNING BAKERY — Open from 6 am. Fresh bread, pastries and the best coffee in town to start your day.' },
        { label: '12', text: 'SKY TERRACE — A rooftop restaurant on the 20th floor with views across the whole city.' },
        { label: '13', text: 'BUDGET BITES — Big portions at small prices. Students get 20% off with a student card.' },
        { label: '14', text: 'CHEF’S TABLE — Join our chef in the kitchen for a two-hour class, then enjoy the dinner you have cooked.' },
      ],
      choices: choices([
        'You want breakfast very early.',
        'You need a private room for a business meeting.',
        'You want food brought to your home.',
        'You would like a good view while you eat.',
        'You do not eat meat.',
        'You want to learn how to prepare a dish.',
        'You are a student with little money.',
        'You want to eat after midnight.',
        'You would like to listen to live music.',
        'You are eating out with young children.',
      ]),
      questions: [
        match('r', 7, 'Text 7', 'E'),
        match('r', 8, 'Text 8', 'C'),
        match('r', 9, 'Text 9', 'I'),
        match('r', 10, 'Text 10', 'J'),
        match('r', 11, 'Text 11', 'A'),
        match('r', 12, 'Text 12', 'D'),
        match('r', 13, 'Text 13', 'G'),
        match('r', 14, 'Text 14', 'F'),
      ],
    },
    {
      id: 'r3',
      index: 3,
      title: 'Plastic in the ocean',
      instruction: 'Read the text and choose the correct heading for each paragraph from the list of headings. There are more headings than paragraphs, so you will not use all of them.',
      passage: [
        {
          label: 'I',
          text: 'Every year, millions of tonnes of plastic end up in the world’s oceans. Scientists have found plastic on remote islands, at the bottom of the deepest ocean trenches and even in Arctic ice. If nothing changes, some experts warn that there may soon be more plastic than fish in parts of the sea.',
        },
        {
          label: 'II',
          text: 'Most of this plastic does not come from ships. It starts its journey on land, as bottles, bags and packaging that are dropped in the street or lost from rubbish dumps. Rain washes it into rivers, and the rivers carry it all the way to the sea.',
        },
        {
          label: 'III',
          text: 'For sea creatures, plastic can be deadly. Turtles mistake floating bags for jellyfish, seabirds feed bottle tops to their chicks, and whales have been found with kilograms of plastic in their stomachs. Old fishing nets continue to trap fish and dolphins for years.',
        },
        {
          label: 'IV',
          text: 'Over time, sunlight and waves break plastic into tiny pieces called microplastics. They are often smaller than a grain of rice, and they are eaten by fish and shellfish. Scientists are now studying what happens when these particles reach the food on our plates.',
        },
        {
          label: 'V',
          text: 'Some governments are taking action. Many countries have banned or taxed thin plastic bags, and in several of them the number of bags used has fallen dramatically within a few years. Others have banned plastic straws and cups, or made companies pay for collecting their packaging.',
        },
        {
          label: 'VI',
          text: 'Individuals can help too. Carrying a reusable bag and water bottle, saying no to straws and sorting rubbish for recycling may seem small, but when millions of people do them, the effect is huge. Every bottle that is recycled is one less that might reach the sea.',
        },
      ],
      choices: choices([
        'Too small to see',
        'Laws that make a difference',
        'From land to sea',
        'The history of plastic',
        'Small steps at home',
        'A problem of enormous size',
        'Dangerous for wildlife',
        'Cleaner beaches for tourists',
      ]),
      questions: [
        match('r', 15, 'Paragraph I', 'F'),
        match('r', 16, 'Paragraph II', 'C'),
        match('r', 17, 'Paragraph III', 'G'),
        match('r', 18, 'Paragraph IV', 'A'),
        match('r', 19, 'Paragraph V', 'B'),
        match('r', 20, 'Paragraph VI', 'E'),
      ],
    },
    {
      id: 'r4',
      index: 4,
      title: 'My father’s car',
      instruction: 'Read the text. For questions 21–24, choose the correct answer A, B, C or D. For questions 25–29, decide if the statements agree with the information in the text.',
      passage: [
        {
          label: '1',
          text: 'Three years ago, my father and I were driving past a farm outside the city when he suddenly stopped the car. In a field behind the farmhouse, half covered with grass, stood an old blue Moskvich. My father walked around it twice and then told me, with a strange smile, that it was exactly the same model as his very first car.',
        },
        {
          label: '2',
          text: 'The farmer was happy to sell it for almost nothing. I was eighteen, and I knew nothing about engines, but my father said we would bring it back to life together. I thought it would take a few months. In the end, it took us just over two years of weekends and evenings in the garage.',
        },
        {
          label: '3',
          text: 'The engine was easier than we expected; my father still remembered how everything worked. The real problem was finding spare parts. The car had not been produced for decades, so we searched markets, asked old mechanics and finally ordered some parts from collectors abroad. Each time a box arrived, it felt like a holiday.',
        },
        {
          label: '4',
          text: 'Last spring we drove the car to a classic car show in Tashkent. We did not win a prize, but something better happened. All day, older visitors came to tell us stories about their own Moskvich: a wedding, a first trip to the sea, a broken-down engine in the desert. My father listened to every story.',
        },
        {
          label: '5',
          text: 'I learned more in those two years than in any classroom — not only about cars, but about patience and about my father. He is already looking for our next project. This time, he says, it will be an old motorbike.',
        },
      ],
      questions: [
        mcq(
          'r',
          21,
          'Where did the writer and his father find the car?',
          ['at a car show', 'in a field behind a farm', 'in an advertisement online', 'in the father’s garage'],
          'B',
        ),
        mcq(
          'r',
          22,
          'Why did the father want the car?',
          [
            'He wanted to sell it later.',
            'It was the same model as his first car.',
            'He wanted to win a competition.',
            'His son had asked for a car.',
          ],
          'B',
        ),
        mcq(
          'r',
          23,
          'What was the most difficult part of the project?',
          ['repairing the engine', 'painting the car', 'finding spare parts', 'paying for the car'],
          'C',
          "Dvigatel kutilganidan oson bo'lgan, haqiqiy muammo — ehtiyot qismlar.",
        ),
        mcq(
          'r',
          24,
          'At the car show,',
          [
            'the car won first prize.',
            'the car broke down.',
            'older visitors shared their memories.',
            'someone offered to buy the car.',
          ],
          'C',
        ),
        tfng(25, 'The writer had experience of repairing cars before the project.', 'False'),
        tfng(26, 'The project took more than a year.', 'True'),
        tfng(27, 'The writer’s mother helped to paint the car.', 'No Information'),
        tfng(28, 'Some parts came from other countries.', 'True'),
        tfng(
          29,
          'They are planning to repair another car.',
          'False',
          "Keyingi loyiha — mashina emas, eski mototsikl.",
        ),
      ],
    },
    {
      id: 'r5',
      index: 5,
      title: 'The saiga antelope',
      instruction: 'Read the text. For questions 30–33, fill in the missing information. Write no more than ONE WORD and / or A NUMBER. For questions 34–35, choose the correct answer A, B, C or D.',
      passage: [
        {
          label: '1',
          text: 'The saiga is one of the strangest-looking animals of the Central Asian steppe. Its large, soft nose hangs down over its mouth and works like a filter, cleaning the dusty air in summer and warming the cold air in winter.',
        },
        {
          label: '2',
          text: 'Saigas travel long distances across the grasslands in huge herds, sometimes tens of thousands of animals together. Their movements follow the seasons, as they search for fresh grass and safe places to give birth to their young.',
        },
        {
          label: '3',
          text: 'In the last century, the saiga came close to extinction. Hunters killed the males for their horns, which were sold for use in traditional medicine, and the population fell dramatically. Then, in 2015, a disease spread through the herds in Kazakhstan and killed more than half of the population in just a few weeks.',
        },
        {
          label: '4',
          text: 'Yet the story has a hopeful ending. Strict protection from hunting, new nature reserves and the work of rangers have allowed the saiga to recover. In Kazakhstan, numbers have grown to more than a million, and conservationists now see the saiga as an example of how quickly nature can return when it is given a chance.',
        },
      ],
      questions: [
        gap('r', 30, 'The saiga’s unusual … filters the dusty air.', 'nose'),
        gap('r', 31, 'Saigas travel across the steppe in large', 'herds'),
        gap('r', 32, 'In 2015, a … killed more than half of the saigas.', 'disease'),
        gap('r', 33, 'Male saigas were hunted for their', 'horns'),
        mcq(
          'r',
          34,
          'What has helped the saiga population to recover?',
          [
            'keeping saigas in zoos',
            'protection from hunting',
            'moving them to other countries',
            'feeding them in winter',
          ],
          'B',
        ),
        mcq(
          'r',
          35,
          'What is the writer’s main purpose?',
          [
            'to describe the dangers to an animal and its recovery',
            'to criticise traditional medicine',
            'to compare the saiga with other antelopes',
            'to encourage tourists to visit the steppe',
          ],
          'A',
        ),
      ],
    },
  ],
  writing: writingPaper(
    {
      context: 'Your local sports centre has asked its members for ideas on how to improve its services.',
      prompt:
        'Write an email to the manager of the sports centre. In your email:\n- say how long you have been a member and what you use;\n- describe two problems you have noticed;\n- suggest how the centre could improve.\nWrite about 150 words in an appropriate format and style.',
    },
    'Some people prefer to live in a big city, while others believe that life in the countryside is better.\n\nDiscuss both views and give your opinion. Write at least 250 words in an appropriate style and format.',
  ),
  speaking: speakingQuestions({
    personal: [
      'What do you usually do in the mornings before work or study?',
      'Do you prefer spending time indoors or outdoors? Why?',
      'Tell me about a place in your town that you like to visit.',
    ],
    pictures: 'Picture A: a family eating dinner together at home · Picture B: friends eating fast food in a café',
    compare: [
      'Compare the two pictures. What are the similarities and differences?',
      'Which kind of meal do you enjoy more? Why?',
      'Do you think families spend less time together than in the past?',
    ],
    monologue: {
      image: 'A group of volunteers planting trees in a city park',
      prompt:
        'Talk about a time when you helped someone or your community. Say what you did, why you did it and how you felt afterwards.',
    },
    debate:
      'Every student should learn to play a musical instrument at school. For: music improves concentration and creativity. Against: it takes time away from important subjects. Give arguments for and against this statement and say what you think.',
  }),
  scripts: [
    script('l1', [
      intro('Part one. You will hear some sentences. Choose the correct reply to each sentence.'),
      cue(1, 'man', 'Excuse me, can I pay by card here?', 2),
      cue(2, 'woman', "Have you seen my keys anywhere? I can't find them.", 2),
      cue(3, 'man', 'Shall I book a table at the restaurant for tonight?', 2),
      cue(4, 'woman', "I'm afraid I can't come to your party on Saturday.", 2),
      cue(5, 'man', 'Excuse me, does this train stop at Bukhara?', 2),
      cue(6, 'woman', 'How about going for a walk after lunch?', 2),
      cue(7, 'man', "Ouch! I've just cut my finger!", 2),
      cue(8, 'woman', 'What do you think of the new English teacher?', 2),
      outro('one'),
    ]),
    script('l2', [
      intro('Part two. You will hear a camp director talking to parents. Fill in the missing information. Write one word and, or, a number for each answer.'),
      say('man', "Good evening, everyone. Thank you for coming. I'd like to tell you about this year's Summer Language Camp."),
      cue(9, 'man', "Please remember that registration closes on the first of July. The camp itself starts on the fifteenth of July and lasts for three weeks."),
      cue(10, 'man', "The students stay in our new building. The rooms are quite large, and each room is for three students, with its own bathroom."),
      cue(11, 'man', "There's an indoor pool, and the children can swim every afternoon. For hygiene reasons, everyone must bring a swimming cap. Towels are provided."),
      cue(12, 'man', "Every Saturday we go on a trip. This year, instead of visiting the city museum, we'll go on a walk in the mountains to a beautiful waterfall."),
      cue(13, 'man', "We want the children to speak English with each other, so phones are only allowed in the evening, after dinner, to call home."),
      cue(14, 'man', "The price includes all lessons, meals, trips and books. The only thing it doesn't include is insurance, which you need to arrange yourselves."),
      outro('two'),
    ]),
    script('l3', [
      intro('Part three. You will hear people speaking in different situations. Match each speaker to the place where the speaker is. There are two extra places which you do not need to use.'),
      speaker(15, 1),
      say('woman', "This jacket also comes in blue and black. What size are you, a medium? The fitting rooms are just over there, behind the shoes. Let me know if you need a different size."),
      speaker(16, 2),
      say('man', "Excuse me! Please don't run around the edge, it's very slippery. And if you can't swim well, stay in the shallow end. The lifeguard is always here if you need help."),
      speaker(17, 3),
      say('woman2', "So, just a little off the sides and the back, like last time? Let's wash it first, then I'll cut it. Would you like me to dry it straight or with some curls?"),
      speaker(18, 4),
      say('man2', "Fill it up, please, on pump number three. Oh, and could you check the air in my tyres? The front one looks a bit low. Do you take cards?"),
      outro('three'),
    ]),
    script('l4', [
      intro('Part four. You will hear someone giving a talk. Label the places on the map. There are three extra options which you do not need to use.'),
      say('woman', "Welcome to the old town. We're standing next to the clock tower, on the north side of Bazaar Street. Let me tell you where to find a few interesting places."),
      cue(19, 'woman', "If you'd like to buy a carpet, there's a wonderful carpet shop right next to the clock tower, on its west side, on this side of the street."),
      cue(20, 'woman', "For tea, walk to the crossroads and turn into Mosque Road. Go north, and you'll find the tea house near the top of Mosque Road, on your left."),
      cue(21, 'woman', "The pharmacy is on the corner of Bazaar Street and Mosque Road, on the east side of Mosque Road. Don't go further up the road, or you'll miss it."),
      cue(22, 'woman', "The town museum is on Garden Street. Walk south down Garden Street, and it's right at the bottom, on your left-hand side."),
      cue(23, 'woman', "And if you need a place to stay, the best hotel is on the south side of Bazaar Street, at the eastern end."),
      outro('four'),
    ]),
    script('l5', [
      intro('Part five. You will hear three extracts. Choose the correct answer for each question. There are two questions for each extract.'),
      say('narrator', 'Extract one. You will hear two students talking about a project.'),
      say('woman', "Anvar, our teacher wants the project topic by Monday. Shall we do public transport?"),
      cue(24, 'man', "Everyone's doing transport, Dilnoza. I think recycling is more interesting. We could visit the new recycling centre and take photos. Local history is too difficult to research in two weeks."),
      cue(25, 'woman', "Fine, recycling it is. And for the presentation, I don't want to speak alone. Let's both present: you do the first half, and I'll do the second."),
      say('narrator', 'Extract two. You will hear part of an interview with a marathon runner.'),
      say('woman2', "Nigora, you've just finished your tenth marathon. Why did you start running?"),
      cue(26, 'woman3', "Not to lose weight, as people often think. Five years ago I was in hospital for a month, and when I came out I felt so weak. My doctor said gentle exercise would help me get my strength back, so I started jogging."),
      cue(27, 'woman3', "My advice to beginners? You don't need expensive shoes, and please don't run every day at first. The most important thing is to increase the distance slowly, a little more each week."),
      say('narrator', 'Extract three. You will hear a conversation in a phone shop.'),
      cue(28, 'woman', "Hello, I bought this phone here two weeks ago. The screen's fine and I love the colour, but the battery runs out by lunchtime every day."),
      cue(29, 'man2', "I'm sorry about that. As it's less than a month old, we won't repair it, and we can't give refunds on opened phones. But we'll exchange it for a new one right now."),
      outro('five'),
    ]),
    script('l6', [
      intro('Part six. You will hear a part of a lecture. Fill in the missing information. Write no more than one word for each answer.'),
      say('man3', "Good morning. Today I'd like to talk about one of the most important insects on the planet: the honey bee."),
      cue(30, 'man3', "A colony can contain tens of thousands of bees, but it has only one queen. Her job is to lay eggs, sometimes more than a thousand a day."),
      cue(31, 'man3', "When a worker bee finds good flowers, she returns to the hive and performs a special dance. The direction and speed of the dance tell the other bees where the flowers are."),
      cue(32, 'man3', "Honey is a remarkable food. Because it contains very little water, bacteria cannot grow in it, so it can stay good to eat for a very long time."),
      cue(33, 'man3', "Bees also work together to control the climate of the hive. By fanning their wings or moving closer together, they keep it at a steady temperature."),
      cue(34, 'man3', "Bees matter to us far more than honey. About a third of the food we eat depends on pollination by bees and other insects."),
      cue(35, 'man3', "Sadly, bee numbers are falling in many countries. The main threats are disease and the pesticides that are used on farms."),
      outro('six'),
    ]),
  ],
};
