import {
  ask,
  cue,
  gap,
  intro,
  mcq,
  outro,
  say,
  script,
  speaker,
  speakingQuestions,
  tfng,
  writingTasks,
} from '../builders';
import type { TestContent } from '../types';

export const content: TestContent = {
  listening: [
    {
      id: 'l1',
      index: 1,
      instruction: 'You will hear some short conversations. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          1,
          'What will the woman bring to the party?',
          ['A cake', 'Some drinks', 'Some fruit'],
          'C',
          'Tort allaqachon bor, ichimlikni Jek olib keladi — ayol meva olib keladi.',
        ),
        mcq('l', 2, 'Which bus should the man take?', ['Number 12', 'Number 21', 'Number 7'], 'B'),
        mcq('l', 3, 'What is the weather going to be like tomorrow?', ['Rainy', 'Sunny', 'Windy'], 'A'),
        mcq('l', 4, 'Why is the man late?', ['He overslept', 'His train was cancelled', 'He lost his wallet'], 'B'),
        mcq('l', 5, 'What does the woman want to study?', ['Medicine', 'Law', 'Architecture'], 'C'),
        mcq(
          'l',
          6,
          'How long will the repair take?',
          ['Two days', 'Five days', 'A week'],
          'A',
          'Odatda bir hafta, lekin ehtiyot qism omborda bor — ikki kun.',
        ),
        mcq('l', 7, 'Where are the speakers?', ['In a bank', 'In a hotel', 'In a pharmacy'], 'B'),
        mcq('l', 8, 'What time is the appointment now?', ['10:30', '11:00', '11:30'], 'C'),
      ],
    },
    {
      id: 'l2',
      index: 2,
      title: 'Greenway Language School — Enrolment',
      instruction: 'Complete the notes. Write',
      emphasis: 'no more than two words',
      durationSec: 0,
      questions: [
        gap('l', 9, 'Course level chosen:', 'intermediate'),
        gap('l', 10, 'Classes are held on Tuesday and', 'Thursday'),
        gap('l', 11, 'Class start time:', '6 pm|6 p.m.|6pm'),
        gap('l', 12, 'Course fee: £', '240', "Avval 300 deyiladi, erta ro'yxatdan o'tganlarga 60 funt chegirma — 240."),
        gap('l', 13, 'Maximum students per class:', 'twelve|12'),
        gap('l', 14, 'Free extra activity:', 'conversation club'),
        gap('l', 15, 'Placement test is taken', 'online'),
        gap('l', 16, 'Course books are included in the', 'price'),
      ],
    },
    {
      id: 'l3',
      index: 3,
      instruction: 'You will hear six people talking about their hobbies. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          17,
          'Speaker 1 started painting because',
          ['a friend advised her', 'she wanted to relax', 'she took a course at work'],
          'B',
        ),
        mcq(
          'l',
          18,
          'Speaker 2 says the hardest thing about running is',
          ['the weather', 'getting up early', 'staying motivated'],
          'C',
        ),
        mcq('l', 19, 'Speaker 3 collects', ['old coins', 'stamps', 'vinyl records'], 'C'),
        mcq('l', 20, 'Speaker 4 learned to cook from', ['videos online', 'her grandmother', 'a cookery school'], 'B'),
        mcq(
          'l',
          21,
          'Speaker 5 enjoys chess mainly because it',
          ['is cheap', 'trains his memory', 'helps him meet people'],
          'C',
        ),
        mcq('l', 22, 'Speaker 6 plans to', ['sell his photos', 'buy a new camera', 'enter a competition'], 'C'),
      ],
    },
    {
      id: 'l4',
      index: 4,
      instruction: 'Listen to a radio interview with a young app developer. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq('l', 23, 'Aziz got the idea for his app', ['at school', 'while travelling', 'from his parents'], 'B'),
        mcq(
          'l',
          24,
          'The app helps users to',
          ['learn languages', 'find cheap transport', 'split bills with friends'],
          'B',
        ),
        mcq('l', 25, 'The biggest challenge at the start was', ['money', 'finding a team', 'technical problems'], 'A'),
        mcq(
          'l',
          26,
          'How many people use the app now?',
          ['Ten thousand', 'Fifty thousand', 'One hundred thousand'],
          'B',
        ),
        mcq(
          'l',
          27,
          'His advice to young people is to',
          ['study programming early', 'start with a small idea', 'find investors quickly'],
          'B',
        ),
      ],
    },
    {
      id: 'l5',
      index: 5,
      title: 'Hillside National Park — Visitor Information',
      instruction: 'Complete the notes. Write',
      emphasis: 'one word or a number',
      durationSec: 0,
      questions: [
        gap('l', 28, 'The visitor centre closes at (pm)', '5|five'),
        gap('l', 29, 'The easiest path is the', 'river'),
        gap('l', 30, 'Visitors must not feed the', 'birds'),
      ],
    },
    {
      id: 'l6',
      index: 6,
      instruction: 'Listen to a talk about food waste. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq('l', 31, 'According to the speaker, most food waste happens', ['on farms', 'in shops', 'in homes'], 'C'),
        mcq('l', 32, 'The most commonly wasted food is', ['bread', 'fruit', 'meat'], 'A'),
        mcq('l', 33, 'Many people misunderstand', ['cooking times', 'date labels', 'portion sizes'], 'B'),
        mcq('l', 34, 'The speaker suggests making', ['a shopping list', 'smaller meals', 'home compost'], 'A'),
        mcq('l', 35, 'The speaker thinks change must start with', ['governments', 'supermarkets', 'individuals'], 'C'),
      ],
    },
  ],
  reading: [
    {
      id: 'r1',
      index: 1,
      title: 'Notice: Summer Book Fair',
      instruction: 'Read the text and fill in the gaps. Write one word only.',
      passage: [
        {
          label: 'A',
          text: 'The annual Summer Book Fair will take place in the Central Park pavilion from 12 to 14 July. Entry is free for everyone, and the fair opens at 10 am each day.',
        },
        {
          label: 'B',
          text: 'More than forty publishers will sell new and second-hand books at reduced prices. Local authors will sign copies of their latest novels on Saturday afternoon.',
        },
        {
          label: 'C',
          text: 'Children can join storytelling sessions in the green tent. Visitors are advised to bring cash, as some stalls do not accept cards.',
        },
      ],
      questions: [
        gap('r', 1, 'The fair is held in the Central Park', 'pavilion'),
        gap('r', 2, 'Visitors do not have to pay for', 'entry'),
        gap('r', 3, 'Books are sold at reduced', 'prices'),
        gap('r', 4, 'Authors sign books on Saturday', 'afternoon'),
        gap('r', 5, 'Storytelling takes place in the green', 'tent'),
        gap('r', 6, 'Some stalls only accept', 'cash'),
        gap('r', 7, 'Publishers will sell both new and', 'second-hand|secondhand'),
      ],
    },
    {
      id: 'r2',
      index: 2,
      title: 'Short Messages',
      instruction: 'Read the messages and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Dear students, the chemistry lab will be closed on Friday for cleaning. Friday’s practical lesson will take place next Monday instead.',
        },
        {
          label: 'B',
          text: 'Lost: a black umbrella with a wooden handle, left in the library reading room on Tuesday. Please hand it in at the front desk.',
        },
        {
          label: 'C',
          text: 'Anna — I’ve booked the tennis court for 7, not 6. Can you bring the balls? I only have my racket.',
        },
      ],
      questions: [
        mcq('r', 8, 'Why will the lab be closed?', ['For repairs', 'For cleaning', 'For an exam'], 'B'),
        mcq('r', 9, 'When will the practical lesson happen?', ['On Friday', 'Next Monday', 'Next Friday'], 'B'),
        mcq('r', 10, 'What is special about the umbrella?', ['Its colour', 'Its handle', 'Its size'], 'B'),
        mcq(
          'r',
          11,
          'Where should the umbrella be returned?',
          ['To the reading room', 'To the front desk', 'To the owner'],
          'B',
        ),
        mcq('r', 12, 'What time is the tennis court booked for?', ['6 o’clock', '6:30', '7 o’clock'], 'C'),
        mcq('r', 13, 'What should Anna bring?', ['A racket', 'Tennis balls', 'Water'], 'B'),
        mcq('r', 14, 'Which message is written to a group of people?', ['A', 'B', 'C'], 'A'),
      ],
    },
    {
      id: 'r3',
      index: 3,
      title: 'The Return of the Bicycle',
      instruction: 'Read the article and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'In many cities, the bicycle is making a comeback. Sales of bikes, especially electric ones, have doubled in the past five years.',
        },
        {
          label: 'B',
          text: 'City councils are building protected cycle lanes, and some employers now pay staff a small bonus for cycling to work.',
        },
        {
          label: 'C',
          text: 'Critics point out that cycling is still dangerous where lanes are missing, and that winter weather keeps many riders off the road.',
        },
        {
          label: 'D',
          text: 'Even so, experts believe cycling will play a central role in the transport of the future, as long as investment continues.',
        },
      ],
      questions: [
        mcq(
          'r',
          15,
          'Which type of bike has become especially popular?',
          ['Racing bikes', 'Electric bikes', 'Folding bikes'],
          'B',
        ),
        mcq('r', 16, 'Bike sales have', ['doubled', 'tripled', 'stayed the same'], 'A'),
        mcq(
          'r',
          17,
          'Some employers encourage cycling by',
          ['giving free bikes', 'paying a bonus', 'offering showers'],
          'B',
        ),
        mcq('r', 18, 'Critics are worried about', ['cost', 'safety', 'pollution'], 'B'),
        mcq('r', 19, 'What stops many people from cycling in winter?', ['Darkness', 'The weather', 'Holidays'], 'B'),
        mcq('r', 20, 'The future of cycling depends on', ['technology', 'investment', 'fuel prices'], 'B'),
        mcq('r', 21, 'The writer’s view of cycling is', ['negative', 'uncertain', 'positive'], 'C'),
      ],
    },
    {
      id: 'r4',
      index: 4,
      title: 'Sleeping Cities: The Rise of Night Markets',
      instruction: 'Do the following statements agree with the information in the text?',
      passage: [
        {
          label: 'A',
          text: 'Night markets have a long history in East Asia, but in recent years they have spread to Europe, Africa and Central Asia.',
        },
        {
          label: 'B',
          text: 'Most night markets open after sunset and stay open until midnight. They usually offer street food, crafts and live music.',
        },
        {
          label: 'C',
          text: 'Local councils often support these markets because they bring life to city centres that would otherwise be empty after office hours.',
          highlight: 'bring life to city centres that would otherwise be empty',
        },
        {
          label: 'D',
          text: 'However, some residents complain about noise and rubbish, and in a few cities markets have been moved to less central areas.',
        },
      ],
      questions: [
        tfng(22, 'Night markets first appeared in Europe.', 'False'),
        tfng(23, 'Most night markets close at around midnight.', 'True'),
        tfng(24, 'Night markets are the main source of income for local councils.', 'Not given'),
        tfng(
          25,
          'Councils like night markets because they make city centres livelier.',
          'True',
          'C paragrafi: "bring life to city centres".',
        ),
        tfng(26, 'All residents are happy with night markets.', 'False'),
      ],
    },
    {
      id: 'r5',
      index: 5,
      title: 'Why We Forget',
      instruction: 'Read the text and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'In the 1880s, the psychologist Hermann Ebbinghaus showed that we forget most new information within a day unless we review it.',
        },
        {
          label: 'B',
          text: 'His “forgetting curve” also revealed a solution: reviewing material at increasing intervals, a technique now called spaced repetition.',
        },
        {
          label: 'C',
          text: 'Modern research adds that sleep plays a key role. During deep sleep, the brain moves memories into long-term storage.',
        },
        {
          label: 'D',
          text: 'Surprisingly, forgetting is not always bad. By removing unimportant details, the brain makes room for what really matters.',
        },
      ],
      questions: [
        mcq('r', 27, 'When did Ebbinghaus do his research?', ['In the 1780s', 'In the 1880s', 'In the 1980s'], 'B'),
        mcq('r', 28, 'Without review, we forget most new information within', ['an hour', 'a day', 'a week'], 'B'),
        mcq(
          'r',
          29,
          'Spaced repetition means reviewing material',
          ['every day', 'at increasing intervals', 'once a month'],
          'B',
        ),
        mcq(
          'r',
          30,
          'During deep sleep, the brain',
          ['forgets details', 'stores memories long-term', 'creates dreams'],
          'B',
        ),
        mcq(
          'r',
          31,
          'According to paragraph D, forgetting',
          ['is always harmful', 'can be useful', 'is a sign of illness'],
          'B',
        ),
        mcq('r', 32, 'The word “reveal” is closest to', ['hide', 'show', 'change'], 'B'),
        mcq('r', 33, 'The “forgetting curve” was created by', ['a doctor', 'a psychologist', 'a teacher'], 'B'),
        mcq(
          'r',
          34,
          'The text is mainly about',
          ['memory and forgetting', 'sleep disorders', 'learning languages'],
          'A',
        ),
        mcq(
          'r',
          35,
          'A student who wants to remember more should',
          ['study all night', 'review often and sleep well', 'avoid taking notes'],
          'B',
        ),
      ],
    },
  ],
  writing: writingTasks(
    'You recently bought a new laptop from an online shop called TechWorld. When it arrived, the screen was broken and the charger was missing.',
    'Write a message to your friend who recommended this shop. Tell them what happened and ask for their advice. Write about 50 words.',
    'Write a letter to the customer service manager of TechWorld. Explain the problems, say how you feel and tell them what you want them to do. Write 120–150 words.',
    'Some people think that young people should be required to do unpaid voluntary work in their community. What are the advantages and disadvantages of this idea? Give reasons and examples. Write at least 180 words.',
  ),
  speaking: speakingQuestions({
    personal: [
      'What do you usually do in the mornings before work or study?',
      'Do you prefer spending time indoors or outdoors? Why?',
      'Tell me about a place in your town that you like to visit.',
    ],
    pictures: 'Picture A: a family eating dinner together at home · Picture B: friends eating fast food in a café',
    compare: [
      'Compare the two pictures. What are the similarities and differences?',
      'Which kind of meal do you enjoy more? Why?',
      'Do you think families spend less time together than in the past?',
    ],
    monologue: {
      image: 'A group of volunteers planting trees in a city park',
      prompt:
        'Talk about a time when you helped someone or your community. Say what you did, why you did it and how you felt afterwards.',
    },
    debate:
      'Every student should learn to play a musical instrument at school. For: music improves concentration and creativity. Against: it takes time away from important subjects. Give arguments for and against this statement and say what you think.',
  }),
  scripts: [
    script('l1', [
      intro('Part one. You will hear some short conversations. For each question, choose the correct answer.'),
      ask(1, 'What will the woman bring to the party?'),
      say('man', "Mia's already made a cake for the party, and Jack is bringing the drinks."),
      say('woman', "OK, so I'll get some fruit on my way. Grapes and strawberries, maybe?", 2),
      ask(2, 'Which bus should the man take?'),
      say('man', 'Excuse me, does the number twelve go to the hospital?'),
      say(
        'woman',
        'It used to, but they changed the route last month. Take the twenty-one. It stops right outside the main entrance.',
        2,
      ),
      ask(3, 'What is the weather going to be like tomorrow?'),
      say('woman', "It's so windy today. I hope it's better for our picnic tomorrow."),
      say(
        'man',
        "The forecast says the wind will stop, but it's going to rain all day. Let's have the picnic on Sunday instead.",
        2,
      ),
      ask(4, 'Why is the man late?'),
      say('woman', "You're forty minutes late! Did you oversleep again?"),
      say(
        'man',
        'Not this time. I was at the station on time, but my train was cancelled and I had to wait for the next one.',
        2,
      ),
      ask(5, 'What does the woman want to study?'),
      say('man', 'Your parents are both doctors. Are you going to study medicine too?'),
      say(
        'woman',
        "Everyone expects that, or law, like my uncle. But I've always loved drawing buildings, so I've applied for architecture.",
        2,
      ),
      ask(6, 'How long will the repair take?'),
      say('man', 'How long will it take to fix my washing machine?'),
      say(
        'woman',
        "Usually about a week, because we have to order the part. But luckily we've got one in the warehouse, so it'll be ready in two days.",
        2,
      ),
      ask(7, 'Where are the speakers?'),
      say('woman', "Good evening. I have a reservation under the name Karimova. It's a double room for three nights."),
      say(
        'man',
        "Welcome. Here's your key card. Breakfast is served from seven in the restaurant on the ground floor.",
        2,
      ),
      ask(8, 'What time is the appointment now?'),
      say('woman', 'I have an appointment with Dr Lee at ten thirty, but I need to change it.'),
      say('man', "Eleven o'clock is taken, I'm afraid. How about eleven thirty?"),
      say('woman', "That's fine. Eleven thirty, then.", 2),
      outro('one'),
    ]),
    script('l2', [
      intro(
        'Part two. You will hear a phone call to a language school. Complete the notes. Write no more than two words.',
      ),
      say('woman', 'Good afternoon, Greenway Language School.'),
      say(
        'man',
        "Hello. I'd like to join an English course. I did a beginner course last year, so I think I need the next level.",
      ),
      cue(9, 'woman', "Then the intermediate course would be right for you. It's our most popular level."),
      say('man', 'Great. When are the classes?'),
      cue(
        10,
        'woman',
        'There are two lessons a week, on Tuesday and Thursday. We used to have Monday classes, but not any more.',
      ),
      cue(11, 'woman', 'Classes start at six p.m. and finish at half past seven, so you can come after work.'),
      say('man', 'And how much does it cost?'),
      cue(
        12,
        'woman',
        'The full price is three hundred pounds, but if you register before the end of this month, you get sixty pounds off. So it would be two hundred and forty.',
      ),
      say('man', 'How big are the groups?'),
      cue(13, 'woman', 'Never more than twelve students, so everyone gets a chance to speak.'),
      cue(
        14,
        'woman',
        "And every Friday there's a free conversation club where you can practise with native speakers.",
      ),
      say('man', 'That sounds good. Do I need to take a test first?'),
      cue(15, 'woman', "Yes, a short placement test. You don't need to come in; you can take it online at home."),
      say('man', 'And do I have to buy the books?'),
      cue(16, 'woman', 'No, the course books are included in the price.'),
      say('man', 'Perfect. Thank you.', 2),
      outro('two'),
    ]),
    script('l3', [
      intro(
        'Part three. You will hear six people talking about their hobbies. For each speaker, choose the correct answer.',
      ),
      speaker(17, 1),
      say(
        'woman',
        "A friend kept telling me to try painting, but that's not why I started. I had a very stressful job, and I just needed something to help me relax in the evenings.",
        2,
      ),
      speaker(18, 2),
      say(
        'man',
        "People think getting up at six is the hardest part, or running in the rain. For me, it's keeping myself motivated. After a few weeks, it's so easy to find excuses.",
        2,
      ),
      speaker(19, 3),
      say(
        'man2',
        "My grandfather collected stamps and coins, but I've always preferred music. I've got more than five hundred vinyl records now, some of them from the nineteen sixties.",
        2,
      ),
      speaker(20, 4),
      say(
        'woman2',
        'Everyone learns from videos these days, but I learned to cook from my grandmother. I spent every summer in her kitchen, watching her make plov and samsa.',
        2,
      ),
      speaker(21, 5),
      say(
        'man3',
        "Chess is good for your memory, and it doesn't cost anything. But the main reason I love it is the club. I've made so many friends there.",
        2,
      ),
      speaker(22, 6),
      say(
        'woman3',
        "I'm happy with my camera, and I don't want to sell my photos. But next month I'm going to enter a national photography competition. I'm really excited about it.",
        2,
      ),
      outro('three'),
    ]),
    script('l4', [
      intro('Part four. You will hear a radio interview with a young app developer. Choose the correct answer.'),
      say(
        'woman',
        "Today I'm talking to Aziz, who created a very successful travel app at the age of nineteen. Aziz, where did the idea come from?",
      ),
      cue(
        23,
        'man',
        'Not from school, and not from my parents. It came to me while I was travelling around Central Asia with a backpack. I kept wasting hours looking for cheap buses and shared taxis.',
      ),
      cue(
        24,
        'man',
        "So the app does exactly that: it helps people find cheap transport between cities. It's not for booking hotels or learning languages; it's all about getting from A to B.",
      ),
      say('woman', 'What was the hardest part at the beginning?'),
      cue(
        25,
        'man',
        'I had a great team of friends, and the technical side was fine. The real problem was money. For the first year, I paid for everything from my savings.',
      ),
      say('woman', 'And now?'),
      cue(
        26,
        'man',
        'We reached ten thousand users in the first month, and today we have about fifty thousand. We hope to reach a hundred thousand next year.',
      ),
      say('woman', 'What would you say to young people who want to do the same?'),
      cue(
        27,
        'man',
        "Don't wait until you find investors or become an expert programmer. Start with a small idea that solves a real problem, and grow from there.",
      ),
      say('woman', 'Aziz, thank you.', 2),
      outro('four'),
    ]),
    script('l5', [
      intro(
        'Part five. You will hear a ranger at Hillside National Park. Complete the notes. Write one word or a number.',
      ),
      cue(
        28,
        'man',
        "Welcome to Hillside National Park. The visitor centre opens at nine and closes at five, so please make sure you're back before then.",
      ),
      cue(
        29,
        'man',
        'There are three walking paths. The mountain path is quite difficult, and the forest path takes about four hours. The easiest one is the river path, which is flat and good for families.',
      ),
      cue(
        30,
        'man',
        'Please remember that you must not feed the birds. Human food makes them ill. Enjoy your visit!',
        2,
      ),
      outro('five'),
    ]),
    script('l6', [
      intro('Part six. You will hear a talk about food waste. Choose the correct answer.'),
      cue(
        31,
        'woman',
        'Good morning. Every year, around a third of all the food we produce is wasted. Many people blame farms or supermarkets, but in fact, most food waste happens in our own homes.',
      ),
      cue(
        32,
        'woman',
        'So what do we throw away? Fruit and meat are high on the list, but the most commonly wasted food is bread. Millions of slices go in the bin every day.',
      ),
      cue(
        33,
        'woman',
        "One reason is that many people misunderstand date labels. 'Best before' does not mean the food is dangerous after that date; it simply may not taste as fresh.",
      ),
      cue(
        34,
        'woman',
        "My main tip is simple: before you go shopping, make a shopping list and stick to it. You'll buy only what you need, and you'll save money too.",
      ),
      cue(
        35,
        'woman',
        'Governments and supermarkets can help, of course. But I believe real change has to start with individuals, with each of us, in our own kitchens. Thank you.',
        2,
      ),
      say('narrator', 'That is the end of the listening test.'),
    ]),
  ],
};
