import {
  ask,
  cue,
  gap,
  intro,
  mcq,
  outro,
  say,
  script,
  speaker,
  speakingQuestions,
  tfng,
  writingTasks,
} from '../builders';
import type { TestContent } from '../types';

export const content: TestContent = {
  listening: [
    {
      id: 'l1',
      index: 1,
      instruction: 'You will hear some short conversations. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          1,
          'Where does the woman want to meet?',
          ['At the café', 'At the station', 'At the library'],
          'B',
          'Ayol "let\'s just meet at the station" deydi.',
        ),
        mcq(
          'l',
          2,
          'What time does the film start?',
          ['6:15', '6:45', '7:15'],
          'C',
          'Film 6:45 da emas, reklamadan keyin 7:15 da boshlanadi.',
        ),
        mcq(
          'l',
          3,
          'How will the man travel to work tomorrow?',
          ['By bus', 'By bike', 'By car'],
          'A',
          "Velosiped ta'mirda, mashina esa xotinida — shuning uchun avtobus.",
        ),
        mcq(
          'l',
          4,
          'What does the girl need to buy?',
          ['A notebook', 'A calculator', 'A dictionary'],
          'B',
          'Qiz "I\'ve got the notebooks already" deydi — kerakligi kalkulyator.',
        ),
        mcq('l', 5, 'Why is the shop closed?', ['It is a holiday', 'It is being repaired', 'The owner is ill'], 'B'),
        mcq(
          'l',
          6,
          'What does the man order?',
          ['Soup', 'A sandwich', 'A salad'],
          'C',
          "Sho'rva tugagan, shuning uchun salat buyuradi.",
        ),
        mcq('l', 7, 'Where did the woman leave her keys?', ['In the car', 'On the desk', 'In her bag'], 'A'),
        mcq(
          'l',
          8,
          'How much does the ticket cost?',
          ['£12', '£15', '£20'],
          'B',
          'Narx £20, lekin talabalar uchun £5 chegirma bor.',
        ),
      ],
    },
    {
      id: 'l2',
      index: 2,
      title: 'Riverside Library — Membership',
      instruction: 'Complete the notes. Write',
      emphasis: 'no more than two words',
      durationSec: 0,
      questions: [
        gap('l', 9, 'Closes on weekdays at', '7 pm|7 p.m.|7pm'),
        gap(
          'l',
          10,
          'Student fee per year: £',
          '35',
          'Spiker avval "forty-five" deydi, keyin talabalar uchun "ten pounds off" chegirmani qo\'shadi.',
        ),
        gap('l', 11, 'Bring a copy of your', 'passport'),
        gap('l', 12, 'Maximum books at one time:', 'eight|8'),
        gap(
          'l',
          13,
          'Late return fine per day: £',
          '0.50|0.5',
          '"Fifty pence" — 0.50 funt. "Fifteen" bilan adashtirmang.',
        ),
        gap('l', 14, 'Quiet study room is on the', 'second floor'),
        gap('l', 15, 'Free workshop topic:', 'CV writing'),
        gap('l', 16, 'Online catalogue password sent by', 'email'),
      ],
    },
    {
      id: 'l3',
      index: 3,
      instruction: 'You will hear six people talking about their jobs. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq('l', 17, 'Speaker 1 enjoys her job mainly because of', ['the salary', 'her colleagues', 'the travel'], 'B'),
        mcq('l', 18, 'Speaker 2 finds it difficult to', ['work at night', 'meet deadlines', 'speak in public'], 'A'),
        mcq('l', 19, 'Speaker 3 started his career as', ['a teacher', 'a journalist', 'an engineer'], 'B'),
        mcq('l', 20, 'Speaker 4 would like to', ['change jobs', 'work abroad', 'start a business'], 'C'),
        mcq(
          'l',
          21,
          'Speaker 5 says her training was',
          ['too short', 'very practical', 'expensive'],
          'B',
          '"Hands-on" iborasi amaliy degan ma\'noni beradi.',
        ),
        mcq(
          'l',
          22,
          'Speaker 6 thinks the best part of his job is',
          ['helping people', 'solving problems', 'flexible hours'],
          'A',
        ),
      ],
    },
    {
      id: 'l4',
      index: 4,
      instruction: 'Listen to a radio interview. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          23,
          'The guest first became interested in gardening',
          ['as a child', 'at university', 'after moving house'],
          'A',
        ),
        mcq(
          'l',
          24,
          'What is the main problem with city gardens?',
          ['Lack of space', 'Poor soil', 'Air pollution'],
          'B',
        ),
        mcq('l', 25, 'She recommends beginners to start with', ['herbs', 'tomatoes', 'flowers'], 'A'),
        mcq(
          'l',
          26,
          'According to the guest, community gardens',
          ['are expensive to run', 'bring neighbours together', 'need official permission'],
          'B',
        ),
        mcq('l', 27, 'What will she talk about next week?', ['Water saving', 'Composting', 'Garden tools'], 'B'),
      ],
    },
    {
      id: 'l5',
      index: 5,
      title: 'City Museum — Guided Tour',
      instruction: 'Complete the notes. Write',
      emphasis: 'one word or a number',
      durationSec: 0,
      questions: [
        gap('l', 28, 'Tour starts at the main', 'entrance'),
        gap('l', 29, 'Tour length in minutes:', '90|ninety'),
        gap('l', 30, 'Photos are not allowed in the', 'gallery', 'Spiker "except in the gallery" deydi.'),
      ],
    },
    {
      id: 'l6',
      index: 6,
      instruction: 'Listen to a lecture about sleep. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          31,
          'The lecturer says most adults need',
          ['6 hours of sleep', '7–9 hours of sleep', '10 hours of sleep'],
          'B',
        ),
        mcq('l', 32, 'Screens before bed mainly affect', ['dreaming', 'falling asleep', 'waking up'], 'B'),
        mcq('l', 33, 'Short naps are most useful', ['in the morning', 'after lunch', 'in the evening'], 'B'),
        mcq('l', 34, 'Teenagers tend to', ['sleep earlier', 'sleep later', 'sleep less deeply'], 'B'),
        mcq('l', 35, 'The lecture ends with advice about', ['diet', 'exercise', 'routine'], 'C'),
      ],
    },
  ],
  reading: [
    {
      id: 'r1',
      index: 1,
      title: 'Notice: Community Sports Centre',
      instruction: 'Read the text and fill in the gaps. Write one word only.',
      passage: [
        {
          label: 'A',
          text: 'The Community Sports Centre will reopen on Monday after a two-month renovation. Members can now use the new swimming pool, which is open from 6 am until 10 pm every day.',
        },
        {
          label: 'B',
          text: 'Children under twelve must be accompanied by an adult. Lockers are free, but you need to bring your own lock. Towels can be rented at reception.',
        },
      ],
      questions: [
        gap('r', 1, 'The centre was closed for two', 'months'),
        gap('r', 2, 'The pool closes at 10 pm every', 'day'),
        gap('r', 3, 'Children under twelve need an', 'adult'),
        gap('r', 4, 'Lockers cost', 'nothing'),
        gap('r', 5, 'You must bring your own', 'lock'),
        gap('r', 6, 'Towels are available at', 'reception'),
        gap('r', 7, 'The new facility is a swimming', 'pool'),
      ],
    },
    {
      id: 'r2',
      index: 2,
      title: 'Short Messages',
      instruction: 'Read the messages and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Hi Sam — the meeting has moved to Thursday. Same room, same time. Please bring the budget figures.',
        },
        {
          label: 'B',
          text: 'Parcel delivery: we tried to deliver your package today. It is now waiting at the post office on King Street.',
        },
        { label: 'C', text: 'Reminder: your dental check-up is tomorrow at 9:30. Please arrive ten minutes early.' },
      ],
      questions: [
        mcq('r', 8, 'What has changed about the meeting?', ['The room', 'The day', 'The time'], 'B'),
        mcq('r', 9, 'What should Sam bring?', ['A report', 'Budget figures', 'A laptop'], 'B'),
        mcq('r', 10, 'Where is the parcel now?', ['At home', 'At the post office', 'With a neighbour'], 'B'),
        mcq('r', 11, 'When is the dental appointment?', ['Today', 'Tomorrow', 'Next week'], 'B'),
        mcq('r', 12, 'The patient should arrive at', ['9:10', '9:20', '9:30'], 'B'),
        mcq('r', 13, 'Message B is from', ['a shop', 'a delivery service', 'a friend'], 'B'),
        mcq('r', 14, 'Which message asks for preparation?', ['A', 'B', 'C'], 'A'),
      ],
    },
    {
      id: 'r3',
      index: 3,
      title: 'Working From Home',
      instruction: 'Read the article and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Since 2020, millions of office workers have discovered the benefits of working from home. Many report saving over an hour a day on commuting.',
        },
        {
          label: 'B',
          text: 'However, managers worry that creativity suffers when teams rarely meet. Some companies now require staff to come in at least three days a week.',
        },
        {
          label: 'C',
          text: 'Researchers suggest that the best model depends on the task: focused work at home, collaboration in the office.',
        },
      ],
      questions: [
        mcq(
          'r',
          15,
          'What benefit do many workers mention?',
          ['Higher pay', 'Less commuting', 'Better equipment'],
          'B',
        ),
        mcq('r', 16, 'Managers are concerned about', ['costs', 'creativity', 'security'], 'B'),
        mcq('r', 17, 'Some companies now ask staff to come in', ['once a week', 'three days a week', 'every day'], 'B'),
        mcq(
          'r',
          18,
          'Researchers believe the best model',
          ['depends on the task', 'is fully remote', 'is fully in the office'],
          'A',
        ),
        mcq('r', 19, 'Focused work is best done', ['at home', 'in the office', 'in cafés'], 'A'),
        mcq('r', 20, 'The writer’s attitude is', ['critical', 'balanced', 'enthusiastic'], 'B'),
        mcq(
          'r',
          21,
          'The best title for the article is',
          ['The End of Offices', 'Finding the Right Balance', 'Why Commuting Matters'],
          'B',
        ),
      ],
    },
    {
      id: 'r4',
      index: 4,
      title: 'The Quiet Revolution of Urban Beekeeping',
      instruction: 'Do the following statements agree with the information in the text?',
      passage: [
        {
          label: 'A',
          text: 'Over the past decade, beehives have appeared on rooftops, balconies and school grounds in cities around the world.',
        },
        {
          label: 'B',
          text: 'Supporters argue that urban hives help pollinate parks and gardens, while also teaching residents about nature.',
        },
        {
          label: 'C',
          text: 'Early studies suggested rooftop hives would struggle, yet the opposite proved true. City bees often produce more honey than their rural counterparts, largely because parks offer a longer flowering season.',
          highlight: 'City bees often produce more honey than their rural counterparts',
        },
        {
          label: 'D',
          text: 'Not everyone is convinced. Ecologists warn that a sudden rise in managed hives may crowd out wild pollinators.',
        },
      ],
      questions: [
        tfng(22, 'Urban beehives can only be found on rooftops.', 'False'),
        tfng(
          23,
          'Rooftop hives yield less honey than hives in the countryside.',
          'False',
          'C paragrafda "city bees often produce more honey" deyilgan — ya\'ni aksincha.',
        ),
        tfng(24, 'Parks have a longer flowering season than farmland.', 'True'),
        tfng(25, 'Most city residents support urban beekeeping.', 'Not given'),
        tfng(26, 'Some ecologists are worried about wild pollinators.', 'True'),
      ],
    },
    {
      id: 'r5',
      index: 5,
      title: 'The Science of Habits',
      instruction: 'Read the text and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Psychologists estimate that around forty percent of our daily actions are habits rather than conscious decisions.',
        },
        {
          label: 'B',
          text: 'Every habit follows a loop: a cue, a routine and a reward. Changing the routine while keeping the cue and reward is the most reliable way to break a bad habit.',
        },
        {
          label: 'C',
          text: 'Contrary to popular belief, forming a new habit takes on average sixty-six days, not twenty-one.',
        },
      ],
      questions: [
        mcq('r', 27, 'About what share of daily actions are habits?', ['20%', '40%', '60%'], 'B'),
        mcq('r', 28, 'A habit loop consists of', ['two parts', 'three parts', 'four parts'], 'B'),
        mcq('r', 29, 'To break a bad habit, you should change the', ['cue', 'routine', 'reward'], 'B'),
        mcq('r', 30, 'Forming a new habit takes on average', ['21 days', '45 days', '66 days'], 'C'),
        mcq('r', 31, 'The “21 days” idea is described as', ['accurate', 'a popular belief', 'a new finding'], 'B'),
        mcq('r', 32, 'The text is mainly about', ['how habits work', 'healthy eating', 'memory'], 'A'),
        mcq('r', 33, 'The word “reliable” is closest to', ['fast', 'dependable', 'difficult'], 'B'),
        mcq('r', 34, 'Who made the estimate in paragraph A?', ['Doctors', 'Psychologists', 'Teachers'], 'B'),
        mcq(
          'r',
          35,
          'The writer would most likely agree that',
          ['habits cannot change', 'change takes time', 'rewards are useless'],
          'B',
        ),
      ],
    },
  ],
  writing: writingTasks(
    'You are a member of the City Sports Club. You have received this email from the club manager:\n\n"Dear member, from next month the club will open two hours later in the morning and the swimming pool will close for six weeks for repairs. We apologise for any inconvenience."',
    'Write a letter to your friend who is also a member. Tell them about the changes and how you feel about them. Write about 50 words.',
    'Write a letter to the club manager. Say how the changes affect you and suggest what the club could do to help members. Write 120–150 words.',
    'Some people believe that cities should spend more money on public transport than on building new roads. To what extent do you agree or disagree? Give reasons and examples. Write at least 180 words.',
  ),
  speaking: speakingQuestions({
    personal: [
      'Where do you live, and what do you like most about it?',
      'How do you usually spend your weekends?',
      'What kind of music do you enjoy, and why?',
    ],
    pictures: 'Picture A: a busy open-air market · Picture B: a modern supermarket',
    compare: [
      'Compare the two pictures. What are the similarities and differences?',
      'Where do you prefer to do your shopping? Why?',
      'How have shopping habits changed in your country in recent years?',
    ],
    monologue: {
      image: 'A young woman learning to play the guitar at home',
      prompt:
        'Describe a skill you learned recently. Say how you learned it, why it was useful and how you felt about it.',
    },
    debate:
      'Online learning will replace traditional schools. For: lessons are flexible, cheaper and available anywhere. Against: students need teachers, friends and discipline. Give arguments for and against this statement and say what you think.',
  }),
  scripts: [
    script('l1', [
      intro('Part one. You will hear some short conversations. For each question, choose the correct answer.'),
      ask(1, 'Where does the woman want to meet?'),
      say('man', 'Shall we meet at the café before the concert? The one next to the library?'),
      say(
        'woman',
        "Hmm, it's always so crowded on Fridays, and the library closes early anyway. Let's just meet at the station. It's easier for both of us.",
      ),
      say('man', "Fine. I'll be by the ticket machines.", 2),
      ask(2, 'What time does the film start?'),
      say('woman', 'The website says six forty-five. We should leave now.'),
      say(
        'man',
        "That's when the doors open, but there are always half an hour of adverts first. The film itself doesn't start until seven fifteen.",
      ),
      say('woman', "Oh, then we've got time for a coffee.", 2),
      ask(3, 'How will the man travel to work tomorrow?'),
      say('woman', 'Are you cycling to work tomorrow?'),
      say(
        'man',
        "I'd love to, but my bike is still at the repair shop. And my wife needs the car to visit her mother, so I'll have to take the bus.",
        2,
      ),
      ask(4, 'What does the girl need to buy?'),
      say('man2', 'Have you got everything for the maths exam, Anna?'),
      say(
        'woman2',
        "I've got the notebooks already, and I can borrow Tom's dictionary for English. But my calculator broke yesterday, so I need to get a new one.",
        2,
      ),
      ask(5, 'Why is the shop closed?'),
      say('woman', "That's strange. The shop is closed. It isn't a holiday today, is it?"),
      say(
        'man',
        "No. Look at the sign on the door: closed for repairs. They're fixing the roof after the storm. The owner says they'll open again next Monday.",
        2,
      ),
      ask(6, 'What does the man order?'),
      say('man', "I'll have the tomato soup, please."),
      say('woman', "I'm sorry, the soup is finished. We have sandwiches or a chicken salad."),
      say('man', "I had a sandwich for lunch, so I'll take the salad, please.", 2),
      ask(7, 'Where did the woman leave her keys?'),
      say('man', 'Did you find your keys? Were they on your desk?'),
      say(
        'woman',
        "I checked my desk and my bag twice. In the end they were in the car. I'd left them next to the gear stick.",
        2,
      ),
      ask(8, 'How much does the ticket cost?'),
      say('woman', 'One ticket for the exhibition, please. How much is it?'),
      say('man', "It's twenty pounds, but if you're a student, you get five pounds off."),
      say('woman', "Great, here's my student card."),
      say('man', "So that's fifteen pounds, then.", 2),
      outro('one'),
    ]),
    script('l2', [
      intro(
        'Part two. You will hear a phone call to Riverside Library. Complete the notes. Write no more than two words.',
      ),
      say('woman', 'Good morning, Riverside Library. How can I help you?'),
      say('man', "Hello. I've just moved to the area and I'd like to become a member. Could you tell me about it?"),
      cue(
        9,
        'woman',
        "Of course. We're open every day. At weekends we close at five, and on weekdays we stay open until seven p.m.",
      ),
      say('man', 'Great. And how much does membership cost?'),
      cue(
        10,
        'woman',
        "The normal fee is forty-five pounds a year. Are you a student? Students get ten pounds off, so it's thirty-five pounds a year.",
      ),
      say('man', "Yes, I'm at the university. What do I need to bring?"),
      cue(
        11,
        'woman',
        "Your student card isn't enough, I'm afraid. Please bring a copy of your passport, so we can check your identity.",
      ),
      say('man', 'No problem. How many books can I borrow?'),
      cue(12, 'woman', 'You can have up to eight books at one time, and you can keep them for three weeks.'),
      say('man', 'And if I bring them back late?'),
      cue(13, 'woman', "Then there's a fine of fifty pence for each day. Not fifteen, fifty pence."),
      say('man', 'I see. Is there a place where I can study?'),
      cue(14, 'woman', "Yes. The ground floor is for children, but there's a quiet study room on the second floor."),
      say('man', 'Do you organise any events?'),
      cue(15, 'woman', "We do. This month there's a free workshop on CV writing, every Thursday evening."),
      say('man', 'Perfect. And can I search for books online?'),
      cue(
        16,
        'woman',
        "Yes. When you join, we'll send you a password for the online catalogue by email. We don't send it by post any more.",
      ),
      say('man', 'Thank you very much. See you tomorrow.', 2),
      outro('two'),
    ]),
    script('l3', [
      intro(
        'Part three. You will hear six people talking about their jobs. For each speaker, choose the correct answer.',
      ),
      speaker(17, 1),
      say(
        'woman',
        'The pay is fine, nothing special, and I hardly ever travel. But I work with a fantastic team. My colleagues are the reason I get up happily every morning.',
        2,
      ),
      speaker(18, 2),
      say(
        'man',
        "I'm a nurse, so giving presentations or meeting deadlines isn't really an issue. The hard part is the night shifts. My body never gets used to working when everyone else is asleep.",
        2,
      ),
      speaker(19, 3),
      say(
        'man2',
        "People are surprised that I'm an engineer now, because I studied teaching. But my first real job was as a journalist for a local newspaper. I wrote about technology, and that's how it all began.",
        2,
      ),
      speaker(20, 4),
      say(
        'woman2',
        "I'm happy with my company and I don't want to move abroad. But one day I'd like to be my own boss. My dream is to start a small business selling handmade furniture.",
        2,
      ),
      speaker(21, 5),
      say(
        'woman3',
        'My training lasted a whole year, and luckily the company paid for it. What I liked most was that it was so hands-on. We learned by actually doing the job, not just reading about it.',
        2,
      ),
      speaker(22, 6),
      say(
        'man3',
        "My hours are long and not flexible at all, and some problems take weeks to solve. But when a family leaves my office with a solution, knowing I've helped people makes it all worth it.",
        2,
      ),
      outro('three'),
    ]),
    script('l4', [
      intro('Part four. You will hear a radio interview with a gardening expert. Choose the correct answer.'),
      say(
        'man',
        'Welcome back to Green Hour. My guest today is Laura Hill, who writes about city gardening. Laura, how did it all start for you?',
      ),
      cue(
        23,
        'woman',
        'It started when I was about six. My grandmother gave me a tiny corner of her garden, and I grew my first carrots there. I studied economics at university, but I never lost that love.',
      ),
      say('man', "Many listeners live in flats. Isn't space the biggest problem in the city?"),
      cue(
        24,
        'woman',
        "Everyone thinks so, and pollution is a worry too. But actually the main problem is the soil. City soil is often poor, full of stones and building waste, so plants simply can't grow well.",
      ),
      say('man', 'So what should a complete beginner grow?'),
      cue(
        25,
        'woman',
        'Not tomatoes. They need a lot of care. And flowers can be disappointing at first. I always tell beginners to start with herbs, like mint or basil. They grow quickly in small pots.',
      ),
      say('man', 'You also support community gardens. Why are they important?'),
      cue(
        26,
        'woman',
        'They cost very little and you rarely need official permission. But the real benefit is social. Community gardens bring neighbours together. People who never spoke before start sharing tools and advice.',
      ),
      say('man', "Wonderful. And you'll be back next week?"),
      cue(
        27,
        'woman',
        'Yes. I was going to talk about saving water, but so many listeners asked about compost that next week will be all about composting at home.',
      ),
      say('man', 'Laura Hill, thank you.', 2),
      outro('four'),
    ]),
    script('l5', [
      intro('Part five. You will hear a guide at the City Museum. Complete the notes. Write one word or a number.'),
      cue(
        28,
        'woman',
        "Good morning, everyone, and welcome to the City Museum. Our guided tour starts here, at the main entrance, so please don't go to the side door by the shop.",
      ),
      cue(
        29,
        'woman',
        "The tour usually takes an hour and a half. That's ninety minutes, with a short break in the café halfway through.",
      ),
      cue(
        30,
        'woman',
        "You're welcome to take photos everywhere in the museum, except in the gallery, because the old paintings can be damaged by the flash.",
      ),
      say('woman', "Right, if everyone is ready, let's begin.", 2),
      outro('five'),
    ]),
    script('l6', [
      intro('Part six. You will hear a lecture about sleep. Choose the correct answer.'),
      cue(
        31,
        'man',
        "Good afternoon. Today we're talking about sleep. Let's start with the most common question: how much do we really need? Some people claim six hours is enough, and a few like ten. But research shows that most adults need between seven and nine hours a night.",
      ),
      cue(
        32,
        'man',
        "Now, what about phones and tablets? Many people think screens give us bad dreams, or make us wake up at night. In fact, their main effect is on falling asleep. The light from the screen tells the brain it's still daytime.",
      ),
      cue(
        33,
        'man',
        "What about naps? A morning nap doesn't do much, and an evening nap can ruin your night. The most useful time for a short nap is after lunch, when energy naturally drops.",
      ),
      cue(
        34,
        'man',
        "Teenagers are a special case. Parents often complain that they're lazy. But teenagers' body clocks actually shift, so they tend to fall asleep later and wake up later. It isn't that they sleep less deeply.",
      ),
      cue(
        35,
        'man',
        "So, what's my final advice? Diet and exercise both matter, but the most important thing is routine. Go to bed and get up at the same time every day, even at weekends. Thank you.",
        2,
      ),
      say('narrator', 'That is the end of the listening test.'),
    ]),
  ],
};
