import {
  choices,
  cue,
  gap,
  grouped,
  intro,
  letters,
  match,
  mcq,
  outro,
  say,
  script,
  speaker,
  speakingQuestions,
  tfng,
  writingPaper,
} from '../builders';
import type { TestContent } from '../types';

export const content: TestContent = {
  listening: [
    {
      id: 'l1',
      index: 1,
      instruction: 'You will hear some sentences. Choose the correct reply to each sentence.',
      emphasis: 'A, B or C',
      durationSec: 0,
      questions: [
        mcq('l', 1, '', ['Sure, no problem.', "It's very early.", 'I left at five.'], 'A'),
        mcq('l', 2, '', ['It takes an hour.', 'Number 23, from the stop over there.', "I've never flown."], 'B'),
        mcq('l', 3, '', ['Better luck next time.', 'Which exam are you taking?', 'Well done! You must be so happy.'], 'C'),
        mcq('l', 4, '', ['Oh, sorry, is it too loud?', 'I love this song too.', "It's on the radio."], 'A'),
        mcq(
          'l',
          5,
          '',
          ["At ten o'clock.", 'Outside the cinema?', "Yes, let's meet."],
          'B',
          '"Where" — joy so\'ralmoqda, vaqt emas.',
        ),
        mcq('l', 6, '', ['I made it myself.', 'Yes, please, it smells delicious.', "It's in the kitchen."], 'B'),
        mcq('l', 7, '', ["It's twelve dollars.", "It's a medium.", "It's made of cotton."], 'A'),
        mcq('l', 8, '', ['No, I went yesterday.', 'It closes at nine.', 'Could you get some bread?'], 'C'),
      ],
    },
    {
      id: 'l2',
      index: 2,
      title: 'Photography Club — first meeting',
      instruction: 'You will hear a club leader talking to new members. Fill in the missing information. Write',
      emphasis: 'ONE WORD and / or A NUMBER',
      durationSec: 0,
      questions: [
        gap('l', 9, 'Meetings are held every … evening', 'Wednesday'),
        gap('l', 10, 'Membership costs … dollars a year', '25|twenty-five', "O'tgan yili 30 dollar edi, endi 25."),
        gap('l', 11, 'First trip: taking photos of the old', 'fortress'),
        gap('l', 12, 'This year’s competition theme:', 'water'),
        gap('l', 13, 'Send your photos by … March', '20|20th|twentieth'),
        gap('l', 14, 'First prize: a new camera', 'lens'),
      ],
    },
    {
      id: 'l3',
      index: 3,
      instruction: 'You will hear people speaking in different situations. Match each speaker (15–18) to the place where the speaker is (A–F). There are',
      emphasis: 'TWO EXTRA places',
      durationSec: 0,
      choices: choices(['at a bakery', 'in a gym', 'in a museum', 'at a concert', 'on a plane', 'in a classroom']),
      questions: [
        match('l', 15, 'Speaker 1', 'E'),
        match('l', 16, 'Speaker 2', 'B'),
        match('l', 17, 'Speaker 3', 'F'),
        match('l', 18, 'Speaker 4', 'D', '"Next song", "sing along" — konsert.'),
      ],
    },
    {
      id: 'l4',
      index: 4,
      instruction: 'You will hear someone giving a talk. Label the places (19–23) on the map (A–H). There are',
      emphasis: 'THREE extra options',
      durationSec: 0,
      choices: letters(8),
      map: {
        width: 330,
        height: 240,
        roads: [
          { points: [[10, 100], [320, 100]] },
          { points: [[150, 100], [150, 230]] },
          { points: [[270, 10], [270, 100]] },
        ],
        blocks: [
          { x: 20, y: 22, w: 100, h: 56, name: 'Lake' },
          { x: 160, y: 40, w: 50, h: 32, letter: 'A' },
          { x: 218, y: 56, w: 40, h: 32, letter: 'C' },
          { x: 282, y: 30, w: 40, h: 32, letter: 'B' },
          { x: 20, y: 116, w: 55, h: 32, letter: 'D' },
          { x: 85, y: 116, w: 55, h: 32, letter: 'E' },
          { x: 164, y: 116, w: 55, h: 32, letter: 'F' },
          { x: 164, y: 186, w: 55, h: 32, letter: 'G' },
          { x: 85, y: 186, w: 55, h: 32, letter: 'H' },
        ],
        labels: [
          { x: 60, y: 104, text: 'Lake Path' },
          { x: 150, y: 236, text: 'Rose Avenue' },
          { x: 270, y: 20, text: 'Hill Path' },
        ],
      },
      questions: [
        match('l', 19, 'Café', 'F', "Rose Avenue dan sharqda, Lake Path ning janubiy tomonida. E esa g'arbda."),
        match('l', 20, 'Playground', 'H'),
        match('l', 21, 'Boat hire', 'A'),
        match('l', 22, 'Information centre', 'B'),
        match('l', 23, 'Mini golf', 'D'),
      ],
    },
    {
      id: 'l5',
      index: 5,
      instruction: 'You will hear three extracts. Choose the correct answer (A, B or C) for each question. There are',
      emphasis: 'TWO questions for each extract',
      durationSec: 0,
      questions: [
        ...grouped('Extract One', [
          mcq(
            'l',
            24,
            'Why has the business trip been cancelled?',
            ['The client cancelled the meeting.', 'All the flights were full.', 'One of the speakers is ill.'],
            'A',
          ),
          mcq(
            'l',
            25,
            'What will they do instead?',
            ['have a video call', 'send a long email', 'travel next week'],
            'A',
          ),
        ]),
        ...grouped('Extract Two', [
          mcq(
            'l',
            26,
            'What makes Davron’s restaurant different?',
            ['It only uses local seasonal food.', 'Its prices are very low.', 'It is open all night.'],
            'A',
          ),
          mcq(
            'l',
            27,
            'How did Davron learn to cook?',
            ['He studied at a cooking school abroad.', 'His mother taught him.', 'He started as a waiter.'],
            'B',
            "Chet elda o'qishni orzu qilgan, lekin hamma narsani onasidan o'rgangan.",
          ),
        ]),
        ...grouped('Extract Three', [
          mcq('l', 28, 'What does Sardor want to study?', ['medicine', 'architecture', 'law'], 'B'),
          mcq(
            'l',
            29,
            'What does his mother suggest?',
            ['going to a university open day', 'asking his teacher for advice', 'waiting for a year'],
            'A',
          ),
        ]),
      ],
    },
    {
      id: 'l6',
      index: 6,
      title: 'How glass is made',
      instruction: 'You will hear a part of a lecture. Fill in the missing information. Write',
      emphasis: 'no more than ONE WORD',
      durationSec: 0,
      questions: [
        gap('l', 30, 'The main ingredient of glass is', 'sand'),
        gap('l', 31, 'The mixture is heated in a', 'furnace'),
        gap('l', 32, 'The earliest glass objects were made in', 'Mesopotamia'),
        gap('l', 33, 'Glass-blowing made glass much', 'cheaper'),
        gap('l', 34, 'Glass can be recycled without losing its', 'quality'),
        gap('l', 35, 'Modern windows use special glass to save', 'energy'),
      ],
    },
  ],
  reading: [
    {
      id: 'r1',
      index: 1,
      title: 'Drink more water',
      instruction: 'Read the text. Fill in each gap with ONE word. You must use a word which is somewhere in the rest of the text.',
      passage: [
        {
          label: '1',
          text: 'Our bodies are about sixty per cent water, so it is not surprising that (1) ______ is so important for good health. It carries food and oxygen around the body, and it also controls our (2) ______. When it is hot, we sweat to cool down, and we need to drink more.',
        },
        {
          label: '2',
          text: 'Even mild dehydration can make you feel (3) ______ and find it hard to concentrate. Many people mistake thirst for hunger and eat a snack when their body really needs a (4) ______ of water. Doctors recommend carrying a bottle with you during the (5) ______.',
        },
        {
          label: '3',
          text: 'Fruit and vegetables also contain a lot of water, so they can help too. However, sugary (6) ______ such as cola are not a good choice. Drinking water throughout the day keeps your body temperature normal and stops you feeling tired. One glass before each meal is an easy habit. Avoid drinks full of sugar — plain water is always best.',
        },
      ],
      questions: [
        gap('r', 1, 'It is not surprising that (1) ______ is so important for good health.', 'water'),
        gap('r', 2, 'It also controls our (2) ______.', 'temperature'),
        gap('r', 3, 'Mild dehydration can make you feel (3) ______.', 'tired'),
        gap('r', 4, 'Your body really needs a (4) ______ of water.', 'glass'),
        gap('r', 5, 'Carry a bottle with you during the (5) ______.', 'day'),
        gap('r', 6, 'Sugary (6) ______ such as cola are not a good choice.', 'drinks'),
      ],
    },
    {
      id: 'r2',
      index: 2,
      title: 'Jobs for students',
      instruction: 'Read the texts 7–14 and the statements A–J. Decide which text matches the situation in each statement. Each statement can be used ONCE only. There are TWO extra statements.',
      passage: [
        { label: '7', text: 'CAFÉ ASSISTANT — Saturdays and Sundays only, 10 am to 4 pm. No experience needed; full training given.' },
        { label: '8', text: 'TOUR GUIDE — Show visitors around the old city. You must speak English and at least one other foreign language.' },
        { label: '9', text: 'DELIVERY RIDER — Use your own bicycle and choose the hours that suit you. Weekly pay.' },
        { label: '10', text: 'SUMMER CAMP LEADER — July and August. Free accommodation and all meals provided.' },
        { label: '11', text: 'IT HELP DESK — Answer customers’ questions online from your own home. We provide the laptop.' },
        { label: '12', text: 'LIBRARY ASSISTANT — Quiet evening shifts. There is usually plenty of time to study between tasks.' },
        { label: '13', text: 'FASHION STORE — Sales assistants wanted. All staff receive 10% off our clothes and shoes.' },
        { label: '14', text: 'SWIMMING TEACHER — Children’s classes at the city pool. A lifeguard certificate is required.' },
      ],
      choices: choices([
        'You want to work without leaving home.',
        'You want to work with animals.',
        'You can only work at weekends.',
        'You have a special qualification.',
        'You would like to buy things more cheaply.',
        'You need somewhere to stay for the summer.',
        'You want a job that could become permanent.',
        'You speak more than one foreign language.',
        'You want to choose your own working hours.',
        'You want time to study while you work.',
      ]),
      questions: [
        match('r', 7, 'Text 7', 'C'),
        match('r', 8, 'Text 8', 'H'),
        match('r', 9, 'Text 9', 'I'),
        match('r', 10, 'Text 10', 'F'),
        match('r', 11, 'Text 11', 'A'),
        match('r', 12, 'Text 12', 'J'),
        match('r', 13, 'Text 13', 'E'),
        match('r', 14, 'Text 14', 'D'),
      ],
    },
    {
      id: 'r3',
      index: 3,
      title: 'The road ahead for electric cars',
      instruction: 'Read the text and choose the correct heading for each paragraph from the list of headings. There are more headings than paragraphs, so you will not use all of them.',
      passage: [
        {
          label: 'I',
          text: 'Ten years ago, electric cars were a rare sight. Today, they are everywhere. In some countries, more than half of all new cars sold run on electricity, and almost every major car company has promised to make electric models in the coming years.',
        },
        {
          label: 'II',
          text: 'Owners point to several benefits. Electric cars are quiet, they produce no exhaust fumes in the street, and they are usually much cheaper to run than petrol cars. With fewer moving parts, they also need less maintenance.',
        },
        {
          label: 'III',
          text: 'The biggest worry for many drivers is charging. People who live in flats often have nowhere to charge at night, and on long journeys they may have to wait for a free charging point. Until there are many more charging stations, some buyers will stay away.',
        },
        {
          label: 'IV',
          text: 'Batteries raise other questions. They need metals such as lithium and cobalt, and mining these can damage the environment and the lives of local communities. Scientists are working on new batteries that use fewer rare materials and are easier to recycle.',
        },
        {
          label: 'V',
          text: 'It is also important to remember where the electricity comes from. A car charged with power from a coal plant is far less green than one charged from solar or wind energy. The real benefit for the climate depends on each country’s power supply.',
        },
        {
          label: 'VI',
          text: 'Looking forward, experts expect batteries to become cheaper and to last longer, so that electric cars cost the same as petrol ones. Some even predict that, combined with self-driving technology, they will change the way we travel completely.',
        },
      ],
      choices: choices([
        'Where to plug in',
        'What the next decade may bring',
        'A rapid rise',
        'The end of petrol stations',
        'Only as clean as the power supply',
        'The hidden cost of batteries',
        'Advantages for drivers',
        'Why people still prefer petrol',
      ]),
      questions: [
        match('r', 15, 'Paragraph I', 'C'),
        match('r', 16, 'Paragraph II', 'G'),
        match('r', 17, 'Paragraph III', 'A', "H emas: paragraf zaryadlash muammosi haqida, benzin afzalligi haqida emas."),
        match('r', 18, 'Paragraph IV', 'F'),
        match('r', 19, 'Paragraph V', 'E'),
        match('r', 20, 'Paragraph VI', 'B'),
      ],
    },
    {
      id: 'r4',
      index: 4,
      title: 'Two strings',
      instruction: 'Read the text. For questions 21–24, choose the correct answer A, B, C or D. For questions 25–29, decide if the statements agree with the information in the text.',
      passage: [
        {
          label: '1',
          text: 'I first heard the dutar played properly at a wedding in Khiva, when I was twenty-eight. An old man sat in the corner of the courtyard, and for half an hour nobody danced; everybody simply listened. I had played the piano as a child and given it up, but that evening I knew I wanted to learn this instrument.',
        },
        {
          label: '2',
          text: 'The name dutar means “two strings”, and at first I thought that would make it easy. I was very wrong. When I returned to Tashkent, I visited a well-known teacher, but he told me politely that he only taught children. Adults, he said, had too many habits and too little time. In the end, a young musician from the conservatory agreed to give me lessons on Sunday mornings.',
        },
        {
          label: '3',
          text: 'I still work full-time in an office, so the only time I could find was early in the morning. For three years I practised for forty minutes every day before work. I tried online videos and even a group class, but nothing helped as much as that short daily practice.',
        },
        {
          label: '4',
          text: 'Last month I played in public for the first time, at my cousin’s wedding. My hands were shaking, and I made two mistakes that I am sure everybody heard. But afterwards an old woman came to tell me that the song had reminded her of her childhood.',
        },
        {
          label: '5',
          text: 'I have no plans to leave my job or to become a professional musician. I know how much I still have to learn. But I am proud that, at thirty-one, I can finally make the sound that stopped a whole wedding in Khiva.',
        },
      ],
      questions: [
        mcq(
          'r',
          21,
          'Where did the writer first hear the dutar played well?',
          ['on the radio', 'at a wedding in Khiva', 'at his school', 'in an online video'],
          'B',
        ),
        mcq(
          'r',
          22,
          'Why did the famous teacher refuse to teach the writer?',
          ['He was too old.', 'He was too busy.', 'He only taught children.', 'The writer could not pay.'],
          'C',
        ),
        mcq(
          'r',
          23,
          'What helped the writer most?',
          ['online videos', 'a group class', 'short practice every morning', 'buying a better instrument'],
          'C',
        ),
        mcq(
          'r',
          24,
          'How does the writer feel about his playing now?',
          [
            'He wants to become a professional musician.',
            'He is proud but knows he has a lot to learn.',
            'He is disappointed with his progress.',
            'He thinks he no longer needs a teacher.',
          ],
          'B',
        ),
        tfng(25, 'The writer learned another instrument as a child.', 'True'),
        tfng(26, 'The dutar has two strings.', 'True'),
        tfng(27, 'The writer’s teacher is famous across Uzbekistan.', 'No Information'),
        tfng(28, 'The writer first played in public at his sister’s wedding.', 'False', "Matnda — amakivachchasining (cousin) to'yi."),
        tfng(29, 'The writer is planning to leave his office job.', 'False'),
      ],
    },
    {
      id: 'r5',
      index: 5,
      title: 'Khiva’s inner town',
      instruction: 'Read the text. For questions 30–33, fill in the missing information. Write no more than ONE WORD and / or A NUMBER. For questions 34–35, choose the correct answer A, B, C or D.',
      passage: [
        {
          label: '1',
          text: 'Walking into Itchan Kala, the inner town of Khiva, feels like stepping back several centuries. The old town is surrounded by thick walls made of clay, and inside them stand mosques, madrasas, palaces and minarets packed closely together along narrow streets.',
        },
        {
          label: '2',
          text: 'In 1990, Itchan Kala became the first site in Central Asia to be added to UNESCO’s World Heritage List. Unlike many historic cities, it has kept its original layout, and people still live and work inside the walls.',
        },
        {
          label: '3',
          text: 'Two minarets are especially famous. Kalta Minor is wide, covered in green and blue tiles, and very short — because it was never finished. Work stopped in the 1850s after the death of the khan who ordered it. Not far away rises the Islam Khodja minaret, the tallest in the city, from the top of which visitors can see the desert beyond the walls.',
        },
        {
          label: '4',
          text: 'In the twentieth century, the inner town was declared a museum, and many of its buildings were carefully restored. Today it is one of the most visited places in Uzbekistan, and in the evenings, when the tour groups have left, its quiet streets still feel much as they did hundreds of years ago.',
        },
      ],
      questions: [
        gap('r', 30, 'The walls of Itchan Kala are made of', 'clay'),
        gap('r', 31, 'It became a World Heritage Site in', '1990'),
        gap('r', 32, 'Kalta Minor was never', 'finished|completed'),
        gap('r', 33, 'The tallest minaret is called Islam', 'Khodja|Khoja'),
        mcq(
          'r',
          34,
          'Why is the inner town in such good condition today?',
          [
            'Nobody has lived there for centuries.',
            'It was turned into a museum and restored.',
            'It was protected by the desert sand.',
            'All its buildings are made of stone.',
          ],
          'B',
        ),
        mcq(
          'r',
          35,
          'What is the writer’s main purpose?',
          [
            'to give a short description and history of a historic town',
            'to complain about the number of tourists',
            'to compare Khiva with other cities in Central Asia',
            'to explain how minarets were built',
          ],
          'A',
        ),
      ],
    },
  ],
  writing: writingPaper(
    {
      context: 'You have seen an advertisement for a summer job as a guide for foreign tourists in your city.',
      prompt:
        'Write an email to the company. In your email:\n- say which job you are applying for and where you saw the advertisement;\n- describe your skills and experience;\n- ask about the working hours and pay.\nWrite about 150 words in an appropriate format and style.',
    },
    'Some people think that the best way to learn about another country is to live there. Others believe that books, films and the internet are enough.\n\nDiscuss both views and give your opinion. Write at least 250 words in an appropriate style and format.',
  ),
  speaking: speakingQuestions({
    personal: [
      'Where do you live, and what do you like most about it?',
      'How do you usually spend your weekends?',
      'What kind of music do you enjoy, and why?',
    ],
    pictures: 'Picture A: a busy open-air market · Picture B: a modern supermarket',
    compare: [
      'Compare the two pictures. What are the similarities and differences?',
      'Where do you prefer to do your shopping? Why?',
      'How have shopping habits changed in your country in recent years?',
    ],
    monologue: {
      image: 'A young woman learning to play the guitar at home',
      prompt:
        'Describe a skill you learned recently. Say how you learned it, why it was useful and how you felt about it.',
    },
    debate:
      'Online learning will replace traditional schools. For: lessons are flexible, cheaper and available anywhere. Against: students need teachers, friends and discipline. Give arguments for and against this statement and say what you think.',
  }),
  scripts: [
    script('l1', [
      intro('Part one. You will hear some sentences. Choose the correct reply to each sentence.'),
      cue(1, 'man', 'Is it OK if I leave a bit early today?', 2),
      cue(2, 'woman', 'Excuse me, which bus goes to the airport?', 2),
      cue(3, 'man', "I've just found out — I've passed all my exams!", 2),
      cue(4, 'woman', 'Could you turn the music down a bit, please?', 2),
      cue(5, 'man', 'Where shall we meet tomorrow?', 2),
      cue(6, 'woman', 'Would you like to try some of my plov?', 2),
      cue(7, 'man', 'Excuse me, how much is this T-shirt?', 2),
      cue(8, 'woman', "I'm going to the shop. Do you need anything?", 2),
      outro('one'),
    ]),
    script('l2', [
      intro('Part two. You will hear a club leader talking to new members. Fill in the missing information. Write one word and, or, a number for each answer.'),
      say('man', "Hi, everyone, and welcome to the Photography Club. It's great to see so many new faces."),
      cue(9, 'man', "We used to meet on Mondays, but most people found that difficult, so now our meetings are every Wednesday evening, from six to eight."),
      cue(10, 'man', "Membership was thirty dollars a year until last summer, but we've managed to reduce it, so it now costs twenty-five dollars a year."),
      cue(11, 'man', "Our first trip is next weekend. We're going to take photos of the old fortress outside the city. The light there is amazing in the late afternoon."),
      cue(12, 'man', "Every spring we have a competition. Last year the theme was people, but this year's theme is water — rivers, rain, even a glass of tea."),
      cue(13, 'man', "Please send your best three photos by the twentieth of March. We'll show the winners at the exhibition in April."),
      cue(14, 'man', "And the prize? A local shop has kindly given us a new camera lens for the winner. Good luck, everyone!"),
      outro('two'),
    ]),
    script('l3', [
      intro('Part three. You will hear people speaking in different situations. Match each speaker to the place where the speaker is. There are two extra places which you do not need to use.'),
      speaker(15, 1),
      say('woman', "Ladies and gentlemen, we will be landing in about twenty minutes. Please return to your seats, fasten your seatbelts and make sure your table is folded away. The cabin crew will now collect any rubbish."),
      speaker(16, 2),
      say('man', "Good, two more sets of ten, and keep your back straight this time. Don't hold your breath. Remember to drink some water between exercises, and then we'll finish on the running machine."),
      speaker(17, 3),
      say('woman2', "Right, everyone, open your books at page forty. Today we're looking at the past tense. And please put last week's homework on my desk before you leave."),
      speaker(18, 4),
      say('man2', "Thank you, Tashkent! You've been amazing tonight. This next song is one you all know, so I want to hear you sing along with us!"),
      outro('three'),
    ]),
    script('l4', [
      intro('Part four. You will hear someone giving a talk. Label the places on the map. There are three extra options which you do not need to use.'),
      say('woman', "Welcome to Green Hills Park. We're at the main gate, at the western end of Lake Path. Let me tell you where to find a few things."),
      cue(19, 'woman', "The café is on the south side of Lake Path, just east of Rose Avenue. Don't confuse it with the building just before Rose Avenue, which is the staff office."),
      cue(20, 'woman', "If you have children with you, the playground is down Rose Avenue. Walk all the way to the bottom, and it's on your right."),
      cue(21, 'woman', "You can hire a boat right next to the lake. The boat hire is on the north side of Lake Path, just to the east of the water."),
      cue(22, 'woman', "For maps and information, go along Lake Path and turn left into Hill Path. Walk north, and the information centre is near the top, on your right."),
      cue(23, 'woman', "And the mini golf is very close to where we are now: on the south side of Lake Path, at the western end, near the gate."),
      outro('four'),
    ]),
    script('l5', [
      intro('Part five. You will hear three extracts. Choose the correct answer for each question. There are two questions for each extract.'),
      say('narrator', 'Extract one. You will hear two colleagues talking about a business trip.'),
      say('man', "Lola, are the flights for Almaty booked? We're both speaking at the meeting on Thursday."),
      cue(24, 'woman', "There's no need, I'm afraid. The client phoned this morning and cancelled the meeting. Their director has to be in Europe all week. The flights weren't even full."),
      cue(25, 'woman', "They still want to see our plans, though, so we've agreed to have a video call on Thursday instead. I'll send the link this afternoon."),
      say('narrator', 'Extract two. You will hear part of a radio interview with a chef.'),
      say('woman2', "Davron, your restaurant is always full. What makes it different?"),
      cue(26, 'man2', "We only cook with what's in season and grown nearby. In winter you won't find tomatoes on our menu. Our prices aren't the cheapest, but people taste the difference."),
      cue(27, 'man2', "I always dreamed of going to a famous cooking school abroad, but I never did. Everything I know, I learnt from my mother, in her tiny kitchen."),
      say('narrator', 'Extract three. You will hear a mother and her son talking about university.'),
      cue(28, 'man3', "Mum, I know you wanted me to study medicine, and Dad keeps talking about law. But I really want to study architecture. I love designing things."),
      cue(29, 'woman', "Then that's what you should do. But before you decide, let's go to the university open day next month. You can talk to the students and see the department yourself."),
      outro('five'),
    ]),
    script('l6', [
      intro('Part six. You will hear a part of a lecture. Fill in the missing information. Write no more than one word for each answer.'),
      say('man3', "Good afternoon. Today's topic is a material we look through every day: glass."),
      cue(30, 'man3', "The main ingredient of glass is surprisingly simple: sand. It is mixed with a few other substances, such as soda and lime."),
      cue(31, 'man3', "The mixture is then heated in a furnace to well over a thousand degrees, until it becomes a thick liquid."),
      cue(32, 'man3', "People have been making glass for a very long time. The earliest glass objects, mostly beads, were made in Mesopotamia more than four thousand years ago."),
      cue(33, 'man3', "About two thousand years ago, the technique of glass-blowing appeared. It made glass much cheaper, and glass cups and bottles became common."),
      cue(34, 'man3', "One great thing about glass is that it can be recycled again and again without losing its quality."),
      cue(35, 'man3', "Today, scientists are developing new kinds of glass. Modern windows, for example, use special glass that keeps heat inside in winter and helps buildings save energy."),
      outro('six'),
    ]),
  ],
};
