import {
  choices,
  cue,
  gap,
  grouped,
  intro,
  letters,
  match,
  mcq,
  outro,
  say,
  script,
  speaker,
  speakingQuestions,
  tfng,
  writingPaper,
} from '../builders';
import type { TestContent } from '../types';

export const content: TestContent = {
  listening: [
    {
      id: 'l1',
      index: 1,
      instruction: 'You will hear some sentences. Choose the correct reply to each sentence.',
      emphasis: 'A, B or C',
      durationSec: 0,
      questions: [
        mcq('l', 1, '', ["It's at three o'clock.", "Yes, it's on the second floor.", "I don't have a meeting."], 'B'),
        mcq('l', 2, '', ["That's very kind of you, thanks.", "They're new bags.", 'I can help you too.'], 'A'),
        mcq('l', 3, '', ['Nice to meet you too.', "I'll catch it.", "It's Bobur. B-O-B-U-R."], 'C'),
        mcq('l', 4, '', ['About three times a week.', 'For an hour.', 'With my brother.'], 'A', '"How often" — chastota so\'raladi.'),
        mcq('l', 5, '', ['It was very tasty.', "Good idea, I'm too tired to cook.", 'I ordered it yesterday.'], 'B'),
        mcq('l', 6, '', ['Not really, it was too long.', "Yes, I'll enjoy it.", 'It starts at eight.'], 'A'),
        mcq('l', 7, '', ['I lent it on Friday.', "Sorry, I'm a bit short myself.", "It's a lot of money."], 'B'),
        mcq('l', 8, '', ["Thanks, I'll be careful.", "I'll watch it later.", "It's raining outside."], 'A'),
      ],
    },
    {
      id: 'l2',
      index: 2,
      title: 'Day trip to Shahrisabz',
      instruction: 'You will hear a tour guide talking to a group. Fill in the missing information. Write',
      emphasis: 'ONE WORD and / or A NUMBER',
      durationSec: 0,
      questions: [
        gap('l', 9, 'The bus leaves at … o’clock', '7|seven'),
        gap('l', 10, 'The journey takes about … hours', '2|two', "O'tgan yili yo'l ta'miri tufayli 3 soat bo'lgan, hozir 2 soat."),
        gap('l', 11, 'First stop: the ruins of the … Palace', 'White'),
        gap('l', 12, 'Lunch: in a local family', 'home|house'),
        gap('l', 13, 'Bring a … because of the sun', 'hat'),
        gap('l', 14, 'Return to Samarkand by … pm', '8|eight'),
      ],
    },
    {
      id: 'l3',
      index: 3,
      instruction: 'You will hear people speaking in different situations. Match each speaker (15–18) to the place where the speaker is (A–F). There are',
      emphasis: 'TWO EXTRA places',
      durationSec: 0,
      choices: choices([
        'at a post office',
        'at a cinema',
        'at a hotel',
        'at a train station',
        'in a bookshop',
        'at a car repair garage',
      ]),
      questions: [
        match('l', 15, 'Speaker 1', 'A'),
        match('l', 16, 'Speaker 2', 'E'),
        match('l', 17, 'Speaker 3', 'F'),
        match('l', 18, 'Speaker 4', 'B', "Poyezd haqida gap bor, lekin chipta va qator — kinoteatr."),
      ],
    },
    {
      id: 'l4',
      index: 4,
      instruction: 'You will hear someone giving a talk. Label the places (19–23) on the map (A–H). There are',
      emphasis: 'THREE extra options',
      durationSec: 0,
      choices: letters(8),
      map: {
        width: 320,
        height: 240,
        roads: [
          { points: [[10, 125], [310, 125]] },
          { points: [[120, 10], [120, 125]] },
          { points: [[230, 125], [230, 230]] },
        ],
        blocks: [
          { x: 20, y: 78, w: 55, h: 32, letter: 'A' },
          { x: 134, y: 78, w: 55, h: 32, letter: 'B' },
          { x: 50, y: 22, w: 55, h: 32, letter: 'C' },
          { x: 134, y: 22, w: 55, h: 32, letter: 'D' },
          { x: 250, y: 78, w: 55, h: 32, letter: 'E' },
          { x: 20, y: 140, w: 55, h: 32, letter: 'F' },
          { x: 128, y: 140, w: 80, h: 34, name: 'Station' },
          { x: 246, y: 150, w: 55, h: 32, letter: 'G' },
          { x: 140, y: 192, w: 60, h: 32, letter: 'H' },
        ],
        labels: [
          { x: 60, y: 129, text: 'Station Road' },
          { x: 120, y: 20, text: 'Market Street' },
          { x: 230, y: 236, text: 'Canal Road' },
        ],
      },
      questions: [
        match('l', 19, 'Bike hire', 'B'),
        match('l', 20, 'Hotel', 'C'),
        match('l', 21, 'Police station', 'G'),
        match('l', 22, 'Supermarket', 'F'),
        match('l', 23, 'Car park', 'H'),
      ],
    },
    {
      id: 'l5',
      index: 5,
      instruction: 'You will hear three extracts. Choose the correct answer (A, B or C) for each question. There are',
      emphasis: 'TWO questions for each extract',
      durationSec: 0,
      questions: [
        ...grouped('Extract One', [
          mcq(
            'l',
            24,
            'What is the main problem in the flat?',
            ['The kitchen is always dirty.', 'The neighbours are noisy.', 'The rent is too high.'],
            'A',
          ),
          mcq(
            'l',
            25,
            'What do the flatmates decide to do?',
            ['pay for a cleaner', 'make a cleaning timetable', 'eat out more often'],
            'B',
            "Farrosh yollash qimmat deb rad etiladi.",
          ),
        ]),
        ...grouped('Extract Two', [
          mcq(
            'l',
            26,
            'According to the rescuer, why do most people need help?',
            ['bad weather', 'getting lost', 'serious injuries'],
            'B',
          ),
          mcq(
            'l',
            27,
            'What is his most important advice?',
            ['Always tell someone your route.', 'Never walk alone.', 'Carry extra food.'],
            'A',
          ),
        ]),
        ...grouped('Extract Three', [
          mcq(
            'l',
            28,
            'What does the customer want to change?',
            ['the dates of her trip', 'her destination', 'her hotel'],
            'A',
          ),
          mcq(
            'l',
            29,
            'How much will the change cost?',
            ['nothing', '20 dollars', '50 dollars'],
            'A',
            "50 dollar — 30 kundan keyin o'zgartirilsa. Bu safar bepul.",
          ),
        ]),
      ],
    },
    {
      id: 'l6',
      index: 6,
      title: 'The camel',
      instruction: 'You will hear a part of a lecture. Fill in the missing information. Write',
      emphasis: 'no more than ONE WORD',
      durationSec: 0,
      questions: [
        gap('l', 30, 'A camel’s hump stores', 'fat'),
        gap('l', 31, 'Camels can close their … to keep out sand', 'nostrils'),
        gap('l', 32, 'Camels with two humps are called', 'Bactrian'),
        gap('l', 33, 'A thirsty camel can drink a lot of water very', 'quickly|fast'),
        gap('l', 34, 'Camel milk is rich in vitamin C and', 'iron'),
        gap('l', 35, 'In Central Asia, camels were essential for', 'trade'),
      ],
    },
  ],
  reading: [
    {
      id: 'r1',
      index: 1,
      title: 'Why volunteer?',
      instruction: 'Read the text. Fill in each gap with ONE word. You must use a word which is somewhere in the rest of the text.',
      passage: [
        {
          label: '1',
          text: 'Volunteering means giving your time to help others without being paid. Many (1) ______ believe they are too busy to volunteer, but even a few hours a month can make a difference. You can visit older (2) ______, clean parks or teach children to read.',
        },
        {
          label: '2',
          text: 'Volunteering is good for the community, but it is also good for the (3) ______ themselves. Studies show that people who help others feel happier and less lonely. Young people can also gain useful (4) ______ such as teamwork and organisation. To find an opportunity, ask at your local (5) ______ or search online. Choose something you enjoy, so that you will want to (6) ______.',
        },
        {
          label: '3',
          text: 'Volunteers often say they get more than they give. Many people who are busy still find time, and even helping your neighbours with their shopping counts. Young volunteers learn new skills, and the local library usually has a list of projects. Once you start, you will want to return again and again.',
        },
      ],
      questions: [
        gap('r', 1, 'Many (1) ______ believe they are too busy to volunteer.', 'people'),
        gap('r', 2, 'You can visit older (2) ______.', 'neighbours|neighbors'),
        gap('r', 3, 'It is also good for the (3) ______ themselves.', 'volunteers'),
        gap('r', 4, 'Young people can gain useful (4) ______.', 'skills'),
        gap('r', 5, 'Ask at your local (5) ______.', 'library'),
        gap('r', 6, 'Choose something you enjoy, so that you will want to (6) ______.', 'return'),
      ],
    },
    {
      id: 'r2',
      index: 2,
      title: 'Places to stay',
      instruction: 'Read the texts 7–14 and the statements A–J. Decide which text matches the situation in each statement. Each statement can be used ONCE only. There are TWO extra statements.',
      passage: [
        { label: '7', text: 'MOUNTAIN CABIN — Sleeps up to eight people. A large living room with a fireplace — perfect for big groups of friends.' },
        { label: '8', text: 'CITY STUDIO — Next to the metro, with a desk and fast wi-fi. Ideal for business travellers who need to work.' },
        { label: '9', text: 'LAKESIDE CAMPSITE — Bring your own tent. Showers and a small shop. Pets are welcome.' },
        { label: '10', text: 'FARM STAY — Help us feed the cows and goats, and enjoy fresh milk and eggs every morning.' },
        { label: '11', text: 'OLD TOWN B&B — Stay in a beautiful 200-year-old merchant’s house. Free walking tour for all guests.' },
        { label: '12', text: 'BEACH HOTEL — Breakfast, lunch and dinner are all included in the price. Three swimming pools.' },
        { label: '13', text: 'STUDENT HOSTEL — Beds from just $8 a night. Shared kitchen and lounge. The best prices in town.' },
        { label: '14', text: 'GARDEN APARTMENT — Ground floor, wide doors and a step-free bathroom, suitable for wheelchair users.' },
      ],
      choices: choices([
        'You do not want to pay for meals separately.',
        'You would like to help look after animals.',
        'You want the cheapest possible place to stay.',
        'You want to go skiing.',
        'You need to work during your stay.',
        'One person in your group uses a wheelchair.',
        'You want a room with a sea view.',
        'You are travelling in a large group.',
        'You want to bring your dog.',
        'You want to stay in a historic building.',
      ]),
      questions: [
        match('r', 7, 'Text 7', 'H'),
        match('r', 8, 'Text 8', 'E'),
        match('r', 9, 'Text 9', 'I'),
        match('r', 10, 'Text 10', 'B'),
        match('r', 11, 'Text 11', 'J'),
        match('r', 12, 'Text 12', 'A', "Dengiz manzarasi (G) haqida matnda hech narsa yo'q."),
        match('r', 13, 'Text 13', 'C'),
        match('r', 14, 'Text 14', 'F'),
      ],
    },
    {
      id: 'r3',
      index: 3,
      title: 'Growing up online',
      instruction: 'Read the text and choose the correct heading for each paragraph from the list of headings. There are more headings than paragraphs, so you will not use all of them.',
      passage: [
        {
          label: 'I',
          text: 'For today’s teenagers, the internet is not a place they visit; it is where they live. Many check their phones dozens of times a day, and messages from friends arrive from the moment they wake up until long after they should be asleep.',
        },
        {
          label: 'II',
          text: 'This is not all bad news. Social media allows young people to stay in touch with friends who have moved away and to find others who share their interests. Teenagers who feel different at school can often find a community online where they are accepted.',
        },
        {
          label: 'III',
          text: 'However, many young people say they feel they must always look their best. Photos are carefully chosen and edited, so it is easy to believe that everyone else has a more exciting and beautiful life. This constant comparison can damage confidence.',
        },
        {
          label: 'IV',
          text: 'Doctors are also worried about sleep. The light from screens tells the brain that it is still daytime, and exciting messages keep teenagers awake. As a result, many arrive at school tired and find it hard to concentrate in the morning.',
        },
        {
          label: 'V',
          text: 'Parents have an important role. Experts suggest agreeing on simple rules, such as no phones at the dinner table or in the bedroom at night. But they also say that children copy what adults do, so parents should think about their own screen habits too.',
        },
        {
          label: 'VI',
          text: 'Schools are starting to help as well. In some countries, students now have lessons on how to recognise false information, protect their privacy and behave kindly online — skills that are just as important today as reading and writing.',
        },
      ],
      choices: choices([
        'Late nights, tired mornings',
        'Lessons for the digital age',
        'Always connected',
        'Why teenagers prefer games',
        'The pressure to look perfect',
        'Setting a good example',
        'A place to belong',
        'Banning phones completely',
      ]),
      questions: [
        match('r', 15, 'Paragraph I', 'C'),
        match('r', 16, 'Paragraph II', 'G'),
        match('r', 17, 'Paragraph III', 'E'),
        match('r', 18, 'Paragraph IV', 'A'),
        match('r', 19, 'Paragraph V', 'F', "H emas: telefonni butunlay taqiqlash emas, oddiy qoidalar va o'rnak haqida."),
        match('r', 20, 'Paragraph VI', 'B'),
      ],
    },
    {
      id: 'r4',
      index: 4,
      title: 'Learning to swim at forty',
      instruction: 'Read the text. For questions 21–24, choose the correct answer A, B, C or D. For questions 25–29, decide if the statements agree with the information in the text.',
      passage: [
        {
          label: '1',
          text: 'I grew up in a small town in the desert, far from any river or lake, and nobody in my family could swim. As an adult I always found excuses to stay out of the water. On beach holidays I sat under an umbrella and told everyone I preferred reading.',
        },
        {
          label: '2',
          text: 'Everything changed two years ago, when I watched my nine-year-old daughter in her first swimming race. She came last, but she climbed out of the pool smiling and asked me why I never swam with her. I did not have a good answer. The next week, at the age of forty, I signed up for lessons.',
        },
        {
          label: '3',
          text: 'The lessons were at six in the morning, before work. The water was not cold and the pool was almost empty, but I was terrified of putting my face under the water. For the first three weeks I could not do it at all, and I almost gave up.',
        },
        {
          label: '4',
          text: 'My instructor, a calm young man called Timur, was endlessly patient. He never laughed and never made me feel stupid. Instead, he broke everything into tiny steps: first breathing out through my nose, then counting to three under the water, then to five.',
        },
        {
          label: '5',
          text: 'Last summer, I swam in the sea for the first time, next to my daughter. It was only a few hundred metres, and it was not elegant, but I did not care. I am not ready to teach anyone, but I tell every adult who cannot swim the same thing: it is never too late.',
        },
      ],
      questions: [
        mcq(
          'r',
          21,
          'Why had the writer never learnt to swim?',
          [
            'She did not like water.',
            'She was always too busy.',
            'She grew up far from water and nobody taught her.',
            'She had a bad experience as a child.',
          ],
          'C',
        ),
        mcq(
          'r',
          22,
          'What made the writer decide to take lessons?',
          ['advice from her doctor', 'a question from her daughter', 'a beach holiday', 'a friend at work'],
          'B',
        ),
        mcq(
          'r',
          23,
          'The first lessons were difficult because she',
          [
            'was afraid of putting her face in the water.',
            'found the water too cold.',
            'did not like her instructor.',
            'had to share the pool with many people.',
          ],
          'A',
        ),
        mcq(
          'r',
          24,
          'What does the writer say about her instructor?',
          [
            'He was very strict.',
            'He often laughed at her.',
            'He was patient and explained things step by step.',
            'He was an old friend of hers.',
          ],
          'C',
        ),
        tfng(25, 'The writer lived near a river as a child.', 'False'),
        tfng(26, 'The writer’s husband can swim.', 'No Information'),
        tfng(27, 'The lessons took place early in the morning.', 'True'),
        tfng(28, 'The writer swam in the sea last summer.', 'True'),
        tfng(29, 'The writer now teaches swimming to adults.', 'False'),
      ],
    },
    {
      id: 'r5',
      index: 5,
      title: 'The journey of the tulip',
      instruction: 'Read the text. For questions 30–33, fill in the missing information. Write no more than ONE WORD and / or A NUMBER. For questions 34–35, choose the correct answer A, B, C or D.',
      passage: [
        {
          label: '1',
          text: 'Most people connect tulips with the Netherlands, but the flower’s real home is much further east. Wild tulips first grew on the mountain slopes of Central Asia, and many species can still be found in Uzbekistan every spring.',
        },
        {
          label: '2',
          text: 'Tulips were grown in the gardens of the Ottoman Empire, and in the sixteenth century they arrived in the Netherlands. There, they quickly became a symbol of wealth. In the 1630s, during a period later called “tulip mania”, prices rose so high that a single rare bulb was said to cost as much as a house.',
        },
        {
          label: '3',
          text: 'Central Asia’s wild tulips are just as remarkable as the famous garden varieties. Greig’s tulip, for example, has bright red flowers and unusual striped leaves, and it has been used to create many modern garden tulips.',
        },
        {
          label: '4',
          text: 'Today, however, many wild tulips are in danger. People dig up the bulbs to sell them, and grazing animals and new roads destroy the places where they grow. Botanists are now working to protect the remaining populations, so that these ancestors of the world’s favourite spring flower do not disappear.',
        },
      ],
      questions: [
        gap('r', 30, 'Wild tulips first grew in the mountains of Central', 'Asia'),
        gap('r', 31, 'In the sixteenth century, tulips arrived in the', 'Netherlands'),
        gap('r', 32, 'During “tulip mania”, one bulb could cost as much as a', 'house'),
        gap('r', 33, 'Greig’s tulip has striped', 'leaves'),
        mcq(
          'r',
          34,
          'Why are wild tulips in danger today?',
          [
            'The climate is becoming too dry.',
            'People dig up the bulbs and their habitats are destroyed.',
            'Gardeners prefer modern varieties.',
            'They no longer produce seeds.',
          ],
          'B',
        ),
        mcq(
          'r',
          35,
          'What is the writer’s main purpose?',
          [
            'to give advice on growing tulips',
            'to explain the history of tulips from Central Asia to Europe',
            'to describe the economy of the Netherlands',
            'to compare tulips with other spring flowers',
          ],
          'B',
        ),
      ],
    },
  ],
  writing: writingPaper(
    {
      context: 'You are a student living in a university dormitory, and you have been having problems with your room.',
      prompt:
        'Write an email to the dormitory manager. In your email:\n- describe the problems;\n- explain how they affect your studies;\n- say what you would like the manager to do.\nWrite about 150 words in an appropriate format and style.',
    },
    'Some people believe that unpaid community work should be a compulsory part of high school education. Others think it should be the student’s own choice.\n\nDiscuss both views and give your opinion. Write at least 250 words in an appropriate style and format.',
  ),
  speaking: speakingQuestions({
    personal: [
      'What do you like about the place where you live?',
      'How do you usually celebrate your birthday?',
      'Do you like reading? What do you read?',
    ],
    pictures: 'Picture A: a family on holiday at the beach · Picture B: a group of friends hiking in the mountains',
    compare: [
      'Compare the two pictures. What are the similarities and differences?',
      'Which holiday would you prefer? Why?',
      'Why do people need holidays?',
    ],
    monologue: {
      image: 'A student giving a presentation in front of a class',
      prompt:
        'Describe a difficult challenge you have faced. Say what the challenge was, how you dealt with it and what you learned from it.',
    },
    debate:
      'Children should start learning a foreign language in kindergarten. For: young children learn languages easily and naturally. Against: they should first master their own language. Give arguments for and against this statement and say what you think.',
  }),
  scripts: [
    script('l1', [
      intro('Part one. You will hear some sentences. Choose the correct reply to each sentence.'),
      cue(1, 'woman', 'Excuse me, do you know where the meeting room is?', 2),
      cue(2, 'man', 'Those look heavy. Can I help you with your bags?', 2),
      cue(3, 'woman', "I'm sorry, I didn't catch your name.", 2),
      cue(4, 'man', 'How often do you go to the gym?', 2),
      cue(5, 'woman', "Let's order a pizza tonight.", 2),
      cue(6, 'man', 'So, did you enjoy the film?', 2),
      cue(7, 'woman', 'Could you lend me some money until Friday?', 2),
      cue(8, 'man', "Watch out! The floor's wet.", 2),
      outro('one'),
    ]),
    script('l2', [
      intro('Part two. You will hear a tour guide talking to a group. Fill in the missing information. Write one word and, or, a number for each answer.'),
      say('woman', "Good evening, everyone. Tomorrow we're going on a day trip to Shahrisabz, the birthplace of Amir Timur. Here's what you need to know."),
      cue(9, 'woman', "Please be in the hotel lobby on time, because the bus leaves at seven o'clock sharp. Breakfast will be ready from six."),
      cue(10, 'woman', "Last year, because of road works, the journey took three hours, but the new road is open now, so it takes about two hours."),
      cue(11, 'woman', "Our first stop is the ruins of the White Palace, or Ak-Saray. Only part of the huge entrance gate is still standing, but it's very impressive."),
      cue(12, 'woman', "For lunch, we won't go to a restaurant. Instead, we'll eat in a local family home, where you can try homemade dishes."),
      cue(13, 'woman', "It will be very sunny tomorrow, and there's little shade, so please bring a hat. We'll provide water on the bus."),
      cue(14, 'woman', "We'll leave Shahrisabz at about six, and we should be back in Samarkand by eight p.m. See you in the morning!"),
      outro('two'),
    ]),
    script('l3', [
      intro('Part three. You will hear people speaking in different situations. Match each speaker to the place where the speaker is. There are two extra places which you do not need to use.'),
      speaker(15, 1),
      say('man', "I'd like to send this parcel to Germany, please. Could you weigh it? And I need ten stamps for postcards as well. How long will the parcel take to arrive?"),
      speaker(16, 2),
      say('woman', "Hello, I'm looking for a novel by Abdulla Qodiriy for my sister. Is it in the classics section, or should I look with the new bestsellers? A gift bag would be great, too."),
      speaker(17, 3),
      say('man2', "I've had a look under the car. The brakes need changing, and one tyre is quite old. We'll order the parts today, and it should be ready tomorrow afternoon."),
      speaker(18, 4),
      say('woman2', "Two tickets for the seven o'clock showing of 'The Last Train', please. Row seven, if possible, in the middle. And a large popcorn to share."),
      outro('three'),
    ]),
    script('l4', [
      intro('Part four. You will hear someone giving a talk. Label the places on the map. There are three extra options which you do not need to use.'),
      say('man', "Welcome. We're standing outside the station entrance, on the south side of Station Road. Let me explain where a few useful places are."),
      cue(19, 'man', "You can hire a bike directly across Station Road from here, on the corner with Market Street, on the east side of Market Street."),
      cue(20, 'man', "Your hotel is on Market Street. Walk north up Market Street, and you'll find it near the top, on your left."),
      cue(21, 'man', "If you lose anything, the police station is on Canal Road. Go east along Station Road, turn right into Canal Road, and it's on your left."),
      cue(22, 'man', "For food shopping, the supermarket is at the far western end of Station Road, on this side, the south side."),
      cue(23, 'man', "And if you come by car, the car park is directly behind the station."),
      outro('four'),
    ]),
    script('l5', [
      intro('Part five. You will hear three extracts. Choose the correct answer for each question. There are two questions for each extract.'),
      say('narrator', 'Extract one. You will hear two flatmates talking.'),
      cue(24, 'woman', "Jamshid, we need to talk. The neighbours are fine and the rent's OK, but the kitchen is a mess every single day. I'm tired of washing everyone's plates."),
      cue(25, 'man', "You're right, sorry. Paying for a cleaner would be too expensive, though. Why don't we make a timetable, so everyone cleans on different days?"),
      say('narrator', 'Extract two. You will hear part of an interview with a mountain rescuer.'),
      say('woman2', "Alisher, you rescue walkers in the mountains. Why do most people need your help?"),
      cue(26, 'man2', "People imagine it's always storms or broken legs. Those happen, but most of our calls are simply people who've got lost. They leave the path and can't find it again."),
      cue(27, 'man2', "My most important advice: always tell someone your route and when you'll be back. Walking alone isn't a problem if somebody knows where you are."),
      say('narrator', 'Extract three. You will hear a conversation in a travel agency.'),
      cue(28, 'woman3', "Hello, I booked a trip to Istanbul with you last week. I still want to go to the same hotel, but my sister's wedding has moved, so I need to change the dates."),
      cue(29, 'man3', "That's no problem. Changes within thirty days of booking are free, so there's nothing to pay. After that it would be fifty dollars."),
      outro('five'),
    ]),
    script('l6', [
      intro('Part six. You will hear a part of a lecture. Fill in the missing information. Write no more than one word for each answer.'),
      say('man3', "Today's lecture is about an animal that has been part of life in Central Asia for thousands of years: the camel."),
      cue(30, 'man3', "Many people believe a camel's hump is full of water. In fact, it stores fat, which the camel can use for energy when food is hard to find."),
      cue(31, 'man3', "Camels are perfectly suited to the desert. They have long eyelashes, and they can close their nostrils to keep out sand during storms."),
      cue(32, 'man3', "There are two main kinds. Camels with one hump are called dromedaries, and camels with two humps are called Bactrian camels."),
      cue(33, 'man3', "Camels can go for days without drinking. But when a thirsty camel finds water, it can drink an enormous amount very quickly."),
      cue(34, 'man3', "Camel milk is also important. It is rich in vitamin C and iron, and in many desert regions it is a key part of people's diet."),
      cue(35, 'man3', "Finally, history. For centuries, camel caravans carried goods across the deserts, and in Central Asia camels were essential for trade along the Silk Road."),
      outro('six'),
    ]),
  ],
};
