import {
  ask,
  cue,
  gap,
  intro,
  mcq,
  outro,
  say,
  script,
  speaker,
  speakingQuestions,
  tfng,
  writingTasks,
} from '../builders';
import type { TestContent } from '../types';

export const content: TestContent = {
  listening: [
    {
      id: 'l1',
      index: 1,
      instruction: 'You will hear some short conversations. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq('l', 1, 'What is the woman looking for?', ['Her glasses', 'Her phone', 'Her passport'], 'A'),
        mcq('l', 2, 'How will the man pay?', ['In cash', 'By card', 'By bank transfer'], 'B'),
        mcq('l', 3, 'What does the boy want to be?', ['A pilot', 'A doctor', 'A programmer'], 'C'),
        mcq('l', 4, 'Where did the woman go on Sunday?', ['To the theatre', 'To the mountains', 'To a wedding'], 'B'),
        mcq('l', 5, 'What is the problem with the flat?', ['The heating', 'The windows', 'The neighbours'], 'A'),
        mcq('l', 6, 'How long has the man been waiting?', ['Ten minutes', 'Twenty minutes', 'Half an hour'], 'C'),
        mcq('l', 7, 'Which course will the woman take?', ['Photography', 'Painting', 'Pottery'], 'A'),
        mcq('l', 8, 'When will the parcel arrive?', ['Tomorrow morning', 'Tomorrow afternoon', 'On Friday'], 'B'),
      ],
    },
    {
      id: 'l2',
      index: 2,
      title: 'City Volunteers — Registration',
      instruction: 'Complete the notes. Write',
      emphasis: 'no more than two words',
      durationSec: 0,
      questions: [
        gap('l', 9, 'Volunteer project: helping at the', 'animal shelter|shelter'),
        gap('l', 10, 'Minimum age:', '18|eighteen'),
        gap('l', 11, 'Hours per week:', 'four|4', "Avval olti deyiladi, keyin minimum to'rt soat ekani aytiladi."),
        gap('l', 12, 'Volunteers usually work on', 'Saturday|Saturdays'),
        gap('l', 13, 'Training session takes place on the', 'first Monday'),
        gap('l', 14, 'Volunteers receive a free', 'uniform'),
        gap('l', 15, 'Contact person: Mrs', 'Karimova'),
        gap('l', 16, 'Application form available on the', 'website'),
      ],
    },
    {
      id: 'l3',
      index: 3,
      instruction: 'You will hear six people talking about moving to a new city. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq('l', 17, 'Speaker 1 moved because of', ['her studies', 'her husband’s job', 'the climate'], 'A'),
        mcq('l', 18, 'Speaker 2 found it difficult to', ['find a flat', 'make friends', 'learn the language'], 'B'),
        mcq('l', 19, 'Speaker 3 misses', ['his family', 'the food', 'the sea'], 'C'),
        mcq('l', 20, 'Speaker 4 says the new city is', ['cheaper', 'safer', 'more exciting'], 'C'),
        mcq('l', 21, 'Speaker 5 got help from', ['a colleague', 'a neighbour', 'an online group'], 'C'),
        mcq('l', 22, 'Speaker 6 plans to', ['stay forever', 'move back home', 'move again'], 'A'),
      ],
    },
    {
      id: 'l4',
      index: 4,
      instruction: 'Listen to an interview with a mountain guide. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq('l', 23, 'The guide started climbing', ['with his father', 'at a sports club', 'in the army'], 'A'),
        mcq(
          'l',
          24,
          'The most dangerous thing in the mountains is',
          ['the cold', 'sudden weather changes', 'wild animals'],
          'B',
        ),
        mcq(
          'l',
          25,
          'Beginners often make the mistake of',
          ['carrying too much', 'walking too fast', 'not drinking enough'],
          'B',
        ),
        mcq('l', 26, 'His favourite season for climbing is', ['spring', 'summer', 'autumn'], 'C'),
        mcq('l', 27, 'He thinks mountain tourism should', ['be limited', 'grow quickly', 'be free'], 'A'),
      ],
    },
    {
      id: 'l5',
      index: 5,
      title: 'University Open Day',
      instruction: 'Complete the notes. Write',
      emphasis: 'one word or a number',
      durationSec: 0,
      questions: [
        gap('l', 28, 'Welcome talk takes place in the', 'hall'),
        gap('l', 29, 'Campus tours start every (minutes):', '30|thirty'),
        gap('l', 30, 'Free lunch tickets are given at', 'registration'),
      ],
    },
    {
      id: 'l6',
      index: 6,
      instruction: 'Listen to a lecture about climate and cities. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          31,
          'Cities are hotter than the countryside mainly because of',
          ['traffic', 'concrete and asphalt', 'factories'],
          'B',
        ),
        mcq('l', 32, 'The difference in temperature can be up to', ['2 degrees', '5 degrees', '10 degrees'], 'B'),
        mcq('l', 33, 'Green roofs help by', ['producing food', 'cooling buildings', 'collecting rain'], 'B'),
        mcq(
          'l',
          34,
          'According to the lecturer, the cheapest solution is',
          ['planting trees', 'painting roofs white', 'building fountains'],
          'A',
        ),
        mcq(
          'l',
          35,
          'The lecturer believes that cities should',
          ['stop growing', 'plan for heat now', 'move industry outside'],
          'B',
        ),
      ],
    },
  ],
  reading: [
    {
      id: 'r1',
      index: 1,
      title: 'Notice: New Library Rules',
      instruction: 'Read the text and fill in the gaps. Write one word only.',
      passage: [
        {
          label: 'A',
          text: 'From 1 September, the university library will be open 24 hours a day during the exam period. Students must show their ID card at the entrance after 10 pm.',
        },
        {
          label: 'B',
          text: 'Food is not allowed in the reading rooms, but drinks in bottles with lids are permitted. The café on the ground floor will stay open until midnight.',
        },
        {
          label: 'C',
          text: 'Group study rooms must be booked online at least one day in advance, and each booking is limited to two hours.',
        },
      ],
      questions: [
        gap('r', 1, 'The library will open all night during the exam', 'period'),
        gap('r', 2, 'After 10 pm, students must show their ID', 'card'),
        gap('r', 3, 'Students cannot bring food into the reading', 'rooms'),
        gap('r', 4, 'Drinks are allowed in bottles with', 'lids'),
        gap('r', 5, 'The café closes at', 'midnight'),
        gap('r', 6, 'Group rooms must be booked', 'online'),
        gap('r', 7, 'A booking cannot be longer than two', 'hours'),
      ],
    },
    {
      id: 'r2',
      index: 2,
      title: 'Short Messages',
      instruction: 'Read the messages and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Team, the client presentation is now on Wednesday at 3, not Thursday. Please send me your slides by Tuesday evening.',
        },
        {
          label: 'B',
          text: 'Your flight HY 604 to Istanbul has been delayed by two hours. The new departure time is 16:40. We apologise for the inconvenience.',
        },
        {
          label: 'C',
          text: 'Aunt Gulnora, thank you for the beautiful scarf! I wore it to the concert last night and everyone asked where I got it.',
        },
      ],
      questions: [
        mcq('r', 8, 'When is the presentation now?', ['Tuesday', 'Wednesday', 'Thursday'], 'B'),
        mcq('r', 9, 'What should the team send?', ['Reports', 'Slides', 'Photos'], 'B'),
        mcq('r', 10, 'How long is the flight delay?', ['One hour', 'Two hours', 'Four hours'], 'B'),
        mcq('r', 11, 'What is the new departure time?', ['14:40', '16:40', '18:40'], 'B'),
        mcq(
          'r',
          12,
          'Why is the writer of message C thanking her aunt?',
          ['For a concert ticket', 'For a scarf', 'For a dinner'],
          'B',
        ),
        mcq('r', 13, 'Where did the writer wear the gift?', ['To work', 'To a concert', 'To a wedding'], 'B'),
        mcq('r', 14, 'Which message is from a company to a customer?', ['A', 'B', 'C'], 'B'),
      ],
    },
    {
      id: 'r3',
      index: 3,
      title: 'The Four-Day Working Week',
      instruction: 'Read the article and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'In recent trials, dozens of companies let their employees work four days a week for the same salary.',
        },
        {
          label: 'B',
          text: 'Most companies reported that productivity stayed the same or even increased, while staff took fewer sick days.',
        },
        {
          label: 'C',
          text: 'Not every business can adopt the idea. Hospitals, shops and factories that must stay open every day find it much harder.',
        },
        {
          label: 'D',
          text: 'Still, almost all companies in the trials decided to continue, suggesting that the idea may soon become more common.',
        },
      ],
      questions: [
        mcq('r', 15, 'In the trials, employees', ['earned less', 'earned the same', 'earned more'], 'B'),
        mcq('r', 16, 'Productivity in most companies', ['fell', 'stayed the same or rose', 'was not measured'], 'B'),
        mcq('r', 17, 'Staff in the trials', ['took fewer sick days', 'worked longer hours', 'changed jobs'], 'A'),
        mcq('r', 18, 'Which businesses find the idea difficult?', ['Offices', 'Hospitals and shops', 'Schools'], 'B'),
        mcq('r', 19, 'After the trials, most companies', ['stopped', 'continued', 'paid more'], 'B'),
        mcq('r', 20, 'The word “adopt” is closest to', ['reject', 'start using', 'study'], 'B'),
        mcq('r', 21, 'The writer suggests the idea will', ['fail', 'become more common', 'be banned'], 'B'),
      ],
    },
    {
      id: 'r4',
      index: 4,
      title: 'Snow Leopards of Central Asia',
      instruction: 'Do the following statements agree with the information in the text?',
      passage: [
        {
          label: 'A',
          text: 'The snow leopard lives high in the mountains of Central Asia, including parts of Uzbekistan, Kyrgyzstan and Tajikistan.',
        },
        {
          label: 'B',
          text: 'Because it is shy and active mainly at dawn and dusk, it is very rarely seen, and scientists often call it the “ghost of the mountains”.',
        },
        {
          label: 'C',
          text: 'Camera traps have changed research completely. Hidden cameras now record animals that no scientist has ever seen in person.',
          highlight: 'Camera traps have changed research completely',
        },
        {
          label: 'D',
          text: 'Numbers fell in the past because of hunting, but thanks to protection programmes, the population in some areas is now stable.',
        },
      ],
      questions: [
        tfng(22, 'Snow leopards can be found in Uzbekistan.', 'True'),
        tfng(23, 'Snow leopards are mostly active in the middle of the day.', 'False'),
        tfng(
          24,
          'Camera traps have transformed research on snow leopards.',
          'True',
          'C paragrafi: "changed research completely".',
        ),
        tfng(25, 'There are more than ten thousand snow leopards in the world.', 'Not given'),
        tfng(26, 'The population is now growing quickly everywhere.', 'False'),
      ],
    },
    {
      id: 'r5',
      index: 5,
      title: 'Why Some Words Survive',
      instruction: 'Read the text and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Every year, dictionaries add hundreds of new words, but only a few of them are still used ten years later.',
        },
        {
          label: 'B',
          text: 'Linguists have found that short words that describe something genuinely new, like “email”, are the most likely to survive.',
        },
        {
          label: 'C',
          text: 'Words based on jokes or famous events usually disappear quickly, because the situation that created them is soon forgotten.',
        },
        {
          label: 'D',
          text: 'Interestingly, the internet has made this process faster: words now appear and disappear within months rather than decades.',
        },
      ],
      questions: [
        mcq('r', 27, 'How many new words do dictionaries add each year?', ['A few', 'Hundreds', 'Millions'], 'B'),
        mcq(
          'r',
          28,
          'Which words are most likely to survive?',
          ['Long technical words', 'Short words for new things', 'Words from jokes'],
          'B',
        ),
        mcq(
          'r',
          29,
          '“Email” is given as an example of a word that',
          ['disappeared', 'survived', 'changed meaning'],
          'B',
        ),
        mcq(
          'r',
          30,
          'Words based on famous events usually',
          ['last for decades', 'disappear quickly', 'become formal'],
          'B',
        ),
        mcq('r', 31, 'The internet has made the life of new words', ['longer', 'shorter', 'more formal'], 'B'),
        mcq('r', 32, 'The word “genuinely” is closest to', ['really', 'rarely', 'partly'], 'A'),
        mcq('r', 33, 'Who studied the survival of words?', ['Historians', 'Linguists', 'Journalists'], 'B'),
        mcq(
          'r',
          34,
          'The text is mainly about',
          ['how new words live and die', 'how to write dictionaries', 'internet slang'],
          'A',
        ),
        mcq('r', 35, 'The writer finds the effect of the internet', ['worrying', 'interesting', 'unimportant'], 'B'),
      ],
    },
  ],
  writing: writingTasks(
    'You work for a company in Tashkent. You have received this email from your manager:\n\n"Next month the company will move to a new office outside the city. The working day will start at 8 am instead of 9 am, and a free company bus will be provided."',
    'Write a message to a colleague. Tell them what you think about the news and how it will affect you. Write about 50 words.',
    'Write a letter to your manager. Explain how the changes will affect you and make suggestions to help employees. Write 120–150 words.',
    'Some people think that governments should spend money on space exploration, while others believe this money should be used to solve problems on Earth. Discuss both views and give your opinion. Write at least 180 words.',
  ),
  speaking: speakingQuestions({
    personal: [
      'What do you like about the place where you live?',
      'How do you usually celebrate your birthday?',
      'Do you like reading? What do you read?',
    ],
    pictures: 'Picture A: a family on holiday at the beach · Picture B: a group of friends hiking in the mountains',
    compare: [
      'Compare the two pictures. What are the similarities and differences?',
      'Which holiday would you prefer? Why?',
      'Why do people need holidays?',
    ],
    monologue: {
      image: 'A student giving a presentation in front of a class',
      prompt:
        'Describe a difficult challenge you have faced. Say what the challenge was, how you dealt with it and what you learned from it.',
    },
    debate:
      'Children should start learning a foreign language in kindergarten. For: young children learn languages easily and naturally. Against: they should first master their own language. Give arguments for and against this statement and say what you think.',
  }),
  scripts: [
    script('l1', [
      intro('Part one. You will hear some short conversations. For each question, choose the correct answer.'),
      ask(1, 'What is the woman looking for?'),
      say('man', 'What are you looking for? Your phone is on the table, and your passport is in your bag.'),
      say('woman', "I know. It's my glasses. I can't read anything without them.", 2),
      ask(2, 'How will the man pay?'),
      say('woman', 'That will be ninety thousand sum. Cash or card?'),
      say('man', "I'd prefer to pay by bank transfer, but I don't have my phone. So card, please.", 2),
      ask(3, 'What does the boy want to be?'),
      say('woman', 'Do you still want to be a pilot, Sardor?'),
      say('man2', "Not any more. Dad wants me to be a doctor, but I love computers. I'm going to be a programmer.", 2),
      ask(4, 'Where did the woman go on Sunday?'),
      say('man', 'Did you go to your cousin’s wedding on Sunday?'),
      say(
        'woman',
        "That was on Saturday. On Sunday we drove to the mountains. It was beautiful. We're going to the theatre next week.",
        2,
      ),
      ask(5, 'What is the problem with the flat?'),
      say(
        'woman',
        "The flat is lovely, and the neighbours are quiet. The windows are new too. But the heating doesn't work, and it's freezing at night.",
        2,
      ),
      ask(6, 'How long has the man been waiting?'),
      say('woman', "Sorry I'm late! Have you been waiting long? Ten minutes?"),
      say('man', "More like half an hour. I got here at ten, and it's half past now.", 2),
      ask(7, 'Which course will the woman take?'),
      say('man', 'Are you doing the painting course again this year?'),
      say(
        'woman',
        "No, the pottery course was full, so I've signed up for photography. I've just bought a new camera.",
        2,
      ),
      ask(8, 'When will the parcel arrive?'),
      say('man', 'Will my parcel arrive tomorrow morning?'),
      say(
        'woman',
        'The morning deliveries are full, but the driver will bring it tomorrow afternoon, between two and five.',
        2,
      ),
      outro('one'),
    ]),
    script('l2', [
      intro(
        'Part two. You will hear a phone call to a volunteering organisation. Complete the notes. Write no more than two words.',
      ),
      say('man', 'City Volunteers, good morning.'),
      cue(9, 'woman', "Hello. I'd like to volunteer. I saw that you need people to help at the animal shelter."),
      cue(10, 'man', "That's right. Can I ask how old you are? Volunteers must be at least eighteen."),
      say('woman', "I'm twenty-two. How much time would I need to give?"),
      cue(11, 'man', 'Most of our volunteers do about six hours a week, but the minimum is four hours.'),
      cue(12, 'man', 'And volunteers usually work on Saturday, because that is when most visitors come.'),
      cue(13, 'man', 'Before you start, there is a training session on the first Monday of every month.'),
      say('woman', 'Do I need special clothes?'),
      cue(14, 'man', 'No, you get a free uniform, a green T-shirt and a jacket.'),
      say('woman', 'Who should I contact?'),
      cue(15, 'man', "Mrs Karimova. That's K-A-R-I-M-O-V-A. She organises all the volunteers."),
      cue(16, 'man', "You can download the application form from our website. We don't send paper forms any more."),
      say('woman', 'Thank you so much.', 2),
      outro('two'),
    ]),
    script('l3', [
      intro(
        'Part three. You will hear six people talking about moving to a new city. For each speaker, choose the correct answer.',
      ),
      speaker(17, 1),
      say(
        'woman',
        "My husband's job didn't change, and I actually preferred the climate at home. But I got a place at a great university here, so we moved for my studies.",
        2,
      ),
      speaker(18, 2),
      say(
        'man',
        'Finding a flat was easy, and I already spoke the language. The difficult part was making friends. For months I only knew people from work.',
        2,
      ),
      speaker(19, 3),
      say(
        'man2',
        "I call my family every day, and the food here is great. What I really miss is the sea. I grew up next to it, and now I'm a thousand kilometres away.",
        2,
      ),
      speaker(20, 4),
      say(
        'woman2',
        "It's definitely not cheaper, and I'm not sure it's safer. But it's much more exciting. There's always a concert or an exhibition to go to.",
        2,
      ),
      speaker(21, 5),
      say(
        'man3',
        "My neighbours were polite but busy, and I didn't know anyone at work yet. Luckily, I found an online group for newcomers. They helped me with everything.",
        2,
      ),
      speaker(22, 6),
      say(
        'woman3',
        "People ask if I'll move back home one day, or somewhere else. Honestly, no. I've found my place. I'm staying here for the rest of my life.",
        2,
      ),
      outro('three'),
    ]),
    script('l4', [
      intro('Part four. You will hear an interview with a mountain guide. Choose the correct answer.'),
      say(
        'woman',
        'My guest is Bakhtiyor, who has been a mountain guide for twenty years. How did you start climbing?',
      ),
      cue(
        23,
        'man',
        'I joined a sports club later, and I did some climbing in the army. But I really started with my father. He took me to the mountains when I was seven.',
      ),
      cue(
        24,
        'man',
        'People fear the cold or wild animals, but the most dangerous thing is how suddenly the weather can change. A sunny morning can become a storm in an hour.',
      ),
      say('woman', 'What mistakes do beginners make?'),
      cue(
        25,
        'man',
        "They often carry too much, and some forget to drink. But the most common mistake is walking too fast at the start. They're exhausted after two hours.",
      ),
      cue(
        26,
        'man',
        'Summer is busy, and spring can be wet. My favourite season is autumn: the air is clear, and the colours are amazing.',
      ),
      say('woman', 'Should more tourists come to the mountains?'),
      cue(
        27,
        'man',
        'Tourism is good for local villages, but it must be limited. Too many visitors damage the paths and leave rubbish. We need to protect these places.',
        2,
      ),
      outro('four'),
    ]),
    script('l5', [
      intro(
        'Part five. You will hear an announcement at a university open day. Complete the notes. Write one word or a number.',
      ),
      cue(
        28,
        'woman',
        'Welcome to our Open Day! The welcome talk by the rector starts at ten in the main hall, on the first floor.',
      ),
      cue(29, 'woman', 'After that, you can join a campus tour. Tours start every thirty minutes from the front door.'),
      cue(
        30,
        'woman',
        "And don't forget: you can get a free lunch ticket at registration, when you collect your badge.",
        2,
      ),
      outro('five'),
    ]),
    script('l6', [
      intro('Part six. You will hear a lecture about climate and cities. Choose the correct answer.'),
      cue(
        31,
        'man',
        'Good morning. Have you noticed that cities are hotter than the countryside? Traffic and factories add some heat, but the main reason is concrete and asphalt. They absorb heat during the day and release it at night.',
      ),
      cue(
        32,
        'man',
        'The difference can be surprising. In summer, a city centre can be up to five degrees hotter than the villages around it.',
      ),
      cue(
        33,
        'man',
        "What can we do? One solution is green roofs. They don't just look nice; plants on the roof help cool the buildings below.",
      ),
      cue(
        34,
        'man',
        'Painting roofs white and building fountains also help. But the cheapest and most effective solution is simply planting more trees along the streets.',
      ),
      cue(
        35,
        'man',
        "Summers will get hotter. Cities don't need to stop growing, but they must plan for the heat now, not in twenty years. Thank you.",
        2,
      ),
      say('narrator', 'That is the end of the listening test.'),
    ]),
  ],
};
