import {
  choices,
  cue,
  gap,
  grouped,
  intro,
  letters,
  match,
  mcq,
  outro,
  say,
  script,
  speaker,
  speakingQuestions,
  tfng,
  writingPaper,
} from '../builders';
import type { TestContent } from '../types';

export const content: TestContent = {
  listening: [
    {
      id: 'l1',
      index: 1,
      instruction: 'You will hear some sentences. Choose the correct reply to each sentence.',
      emphasis: 'A, B or C',
      durationSec: 0,
      questions: [
        mcq('l', 1, '', ["Not yet, I'm nearly done.", 'I finished it tomorrow.', "It's maths homework."], 'A'),
        mcq('l', 2, '', ["Yes, I'm taking it.", 'Yes, please. Tell her Akmal called.', "No, it's a long message."], 'B'),
        mcq('l', 3, '', ['I like it.', "It's Tuesday.", 'Sunny, but quite windy.'], 'C'),
        mcq('l', 4, '', ["You're welcome, any time.", 'Help yourself.', "I'm fine, thanks."], 'A'),
        mcq('l', 5, '', ['The metro is quicker at this time of day.', "It's a new car.", 'I went by car.'], 'A'),
        mcq('l', 6, '', ["I don't need money.", 'Yes, just around the corner.', 'It opens at nine.'], 'B'),
        mcq(
          'l',
          7,
          '',
          ["That's a nice shirt.", "I'll order two then.", 'Oh, when will you have it again?'],
          'C',
          '"Out of stock" — omborda yo\'q, shuning uchun qachon bo\'lishini so\'rash mantiqiy.',
        ),
        mcq('l', 8, '', ['No, not at all.', "Yes, it's a few minutes.", "I'll wait tomorrow."], 'A'),
      ],
    },
    {
      id: 'l2',
      index: 2,
      title: 'City Cooking School — beginners’ course',
      instruction: 'You will hear a chef talking to new students. Fill in the missing information. Write',
      emphasis: 'ONE WORD and / or A NUMBER',
      durationSec: 0,
      questions: [
        gap('l', 9, 'The course lasts … weeks', '6|six'),
        gap('l', 10, 'Classes are on … mornings', 'Saturday', "Avval yakshanba edi, hozir shanba."),
        gap('l', 11, 'Every student must bring an', 'apron'),
        gap('l', 12, 'The first dish: … soup', 'lentil'),
        gap('l', 13, 'Maximum … students in each class', '12|twelve'),
        gap('l', 14, 'At the end, students receive a', 'certificate'),
      ],
    },
    {
      id: 'l3',
      index: 3,
      instruction: 'You will hear people speaking in different situations. Match each speaker (15–18) to the place where the speaker is (A–F). There are',
      emphasis: 'TWO EXTRA places',
      durationSec: 0,
      choices: choices(['in a park', 'at a wedding', 'at a police station', 'in a shoe shop', 'in a library', 'at an airport']),
      questions: [
        match('l', 15, 'Speaker 1', 'B'),
        match('l', 16, 'Speaker 2', 'D'),
        match('l', 17, 'Speaker 3', 'C', "Aeroport tilga olinadi — sumka u yerda o'g'irlangan, lekin gapirayotgan joy — politsiya bo'limi."),
        match('l', 18, 'Speaker 4', 'A'),
      ],
    },
    {
      id: 'l4',
      index: 4,
      instruction: 'You will hear someone giving a talk. Label the places (19–23) on the map (A–H). There are',
      emphasis: 'THREE extra options',
      durationSec: 0,
      choices: letters(8),
      map: {
        width: 320,
        height: 240,
        roads: [
          { points: [[10, 90], [310, 90]] },
          { points: [[200, 90], [200, 230]] },
          { points: [[70, 10], [70, 90]] },
        ],
        blocks: [
          { x: 8, y: 30, w: 50, h: 32, letter: 'B' },
          { x: 84, y: 30, w: 52, h: 32, letter: 'A' },
          { x: 148, y: 48, w: 48, h: 30, letter: 'C' },
          { x: 245, y: 48, w: 55, h: 30, letter: 'D' },
          { x: 20, y: 104, w: 60, h: 32, letter: 'E' },
          { x: 120, y: 104, w: 60, h: 32, letter: 'F' },
          { x: 212, y: 104, w: 72, h: 32, name: 'Bus station' },
          { x: 215, y: 170, w: 60, h: 32, letter: 'G' },
          { x: 125, y: 180, w: 60, h: 32, letter: 'H' },
        ],
        labels: [
          { x: 40, y: 94, text: 'Sea Road' },
          { x: 70, y: 20, text: 'Hill Road' },
          { x: 200, y: 236, text: 'Pine Street' },
        ],
      },
      questions: [
        match('l', 19, 'Swimming pool', 'A'),
        match('l', 20, 'Bank', 'D', '"Directly opposite the bus station" — avtovokzal qarshisida, shimoliy tomonda.'),
        match('l', 21, 'Souvenir shop', 'F'),
        match('l', 22, 'Hospital', 'H'),
        match('l', 23, 'Ferry office', 'E'),
      ],
    },
    {
      id: 'l5',
      index: 5,
      instruction: 'You will hear three extracts. Choose the correct answer (A, B or C) for each question. There are',
      emphasis: 'TWO questions for each extract',
      durationSec: 0,
      questions: [
        ...grouped('Extract One', [
          mcq(
            'l',
            24,
            'Why can’t Kamila go to the concert?',
            ['She has an exam the next day.', 'The ticket is too expensive.', 'She is ill.'],
            'A',
          ),
          mcq(
            'l',
            25,
            'What will they do with Kamila’s ticket?',
            ['sell it online', 'give it to her brother', 'keep it for another concert'],
            'B',
          ),
        ]),
        ...grouped('Extract Two', [
          mcq(
            'l',
            26,
            'Why did Sanjar return to his village?',
            ['His father became ill.', 'He could not find a job in the city.', 'He had always wanted to be a farmer.'],
            'A',
          ),
          mcq(
            'l',
            27,
            'What has helped his business most?',
            ['selling directly to customers online', 'a loan from the government', 'exporting to other countries'],
            'A',
            "Kredit olmaganini aytadi; eksport — kelajak rejasi.",
          ),
        ]),
        ...grouped('Extract Three', [
          mcq(
            'l',
            28,
            'Why is the patient calling?',
            ['to cancel her appointment', 'to move her appointment', 'to ask about the price'],
            'B',
          ),
          mcq(
            'l',
            29,
            'When is her new appointment?',
            ['Monday at nine', 'Tuesday at three', 'Thursday at eleven'],
            'B',
          ),
        ]),
      ],
    },
    {
      id: 'l6',
      index: 6,
      title: 'The history of chess',
      instruction: 'You will hear a part of a lecture. Fill in the missing information. Write',
      emphasis: 'no more than ONE WORD',
      durationSec: 0,
      questions: [
        gap('l', 30, 'Chess probably began in', 'India'),
        gap('l', 31, 'The early game was based on an', 'army'),
        gap('l', 32, 'From Persia, chess spread to the … world', 'Arab|Islamic|Muslim'),
        gap('l', 33, 'In Europe, the queen became the most … piece', 'powerful'),
        gap('l', 34, 'In 1997, a computer called Deep … beat the world champion', 'Blue'),
        gap('l', 35, 'Chess can improve concentration and', 'memory'),
      ],
    },
  ],
  reading: [
    {
      id: 'r1',
      index: 1,
      title: 'Keeping a diary',
      instruction: 'Read the text. Fill in each gap with ONE word. You must use a word which is somewhere in the rest of the text.',
      passage: [
        {
          label: '1',
          text: 'Writing a diary is an old habit, but it is becoming popular again. Many (1) ______ say that writing for just ten minutes a day helps them feel calmer. A diary is a private place where you can describe your (2) ______ honestly, without worrying about what others think.',
        },
        {
          label: '2',
          text: 'Some people write about their day; others list three things they are (3) ______ for. Experts say this simple exercise can improve your mood. Writing also helps you remember (4) ______ that might otherwise be forgotten. Years later, reading an old diary can be like meeting your younger (5) ______.',
        },
        {
          label: '3',
          text: 'You do not need an expensive notebook; your (6) ______ is enough. Writers of diaries often say they feel calmer and more grateful, and many write on their phone before bed. Their old diaries keep important moments and feelings safe, and bring their younger self back to life.',
        },
      ],
      questions: [
        gap('r', 1, 'Many (1) ______ say that writing helps them feel calmer.', 'writers'),
        gap('r', 2, 'You can describe your (2) ______ honestly.', 'feelings'),
        gap('r', 3, 'Others list three things they are (3) ______ for.', 'grateful'),
        gap('r', 4, 'Writing helps you remember (4) ______.', 'moments'),
        gap('r', 5, 'It can be like meeting your younger (5) ______.', 'self'),
        gap('r', 6, 'Your (6) ______ is enough.', 'phone'),
      ],
    },
    {
      id: 'r2',
      index: 2,
      title: 'Sports clubs',
      instruction: 'Read the texts 7–14 and the statements A–J. Decide which text matches the situation in each statement. Each statement can be used ONCE only. There are TWO extra statements.',
      passage: [
        { label: '7', text: 'PARK RUNNERS — Free group runs every Sunday morning. All levels welcome; just turn up and run.' },
        { label: '8', text: 'ACE TENNIS — Private lessons with a former national champion. Book early, places are limited.' },
        { label: '9', text: 'FAMILY SWIM — Every Saturday, parents and children can enjoy the pool together. Toys and floats provided.' },
        { label: '10', text: 'KURASH CENTRE — Discover Uzbekistan’s national wrestling. Beginners’ classes for teenagers and adults.' },
        { label: '11', text: 'VERTICAL CLIMBING WALL — Open every day until midnight. Climb after work or late in the evening.' },
        { label: '12', text: 'WOMEN’S FOOTBALL — Our new women’s team is looking for players. Friendly matches every month.' },
        { label: '13', text: 'MOUNTAIN CYCLING TOURS — Weekend rides into the mountains. Bikes and helmets are provided.' },
        { label: '14', text: 'DESK YOGA — 30-minute classes at lunchtime, right next to the business centre. Come in your work clothes.' },
      ],
      choices: choices([
        'You can only exercise late at night.',
        'You want lessons from a top player.',
        'You need help preparing for a marathon.',
        'You want an activity to do with your children.',
        'You do not have your own equipment.',
        'You want to try a traditional national sport.',
        'You want to learn to ski.',
        'You want to exercise during your lunch break.',
        'You are a woman looking for a team to join.',
        'You do not want to pay anything.',
      ]),
      questions: [
        match('r', 7, 'Text 7', 'J', "Marafonga tayyorlov (C) haqida gap yo'q — faqat bepul yugurish."),
        match('r', 8, 'Text 8', 'B'),
        match('r', 9, 'Text 9', 'D'),
        match('r', 10, 'Text 10', 'F'),
        match('r', 11, 'Text 11', 'A'),
        match('r', 12, 'Text 12', 'I'),
        match('r', 13, 'Text 13', 'E'),
        match('r', 14, 'Text 14', 'H'),
      ],
    },
    {
      id: 'r3',
      index: 3,
      title: 'The true cost of fast fashion',
      instruction: 'Read the text and choose the correct heading for each paragraph from the list of headings. There are more headings than paragraphs, so you will not use all of them.',
      passage: [
        {
          label: 'I',
          text: 'Not long ago, clothes shops changed their collections twice a year, for summer and winter. Today, some big brands bring new designs into their shops every week. Prices are so low that a T-shirt can cost less than a sandwich.',
        },
        {
          label: 'II',
          text: 'But cheap clothes are expensive for the planet. Growing cotton uses huge amounts of water, and the dyes used to colour fabrics often end up in rivers. The fashion industry is also responsible for a large share of the world’s greenhouse gas emissions.',
        },
        {
          label: 'III',
          text: 'Behind every cheap shirt there are also workers, often young women in poorer countries, who work long hours for very low pay. In some factories, conditions are unsafe, and terrible accidents have made headlines around the world.',
        },
        {
          label: 'IV',
          text: 'Because clothes are so cheap, many people no longer look after them. Studies suggest that some items are worn only a few times before they are thrown away, and enormous amounts of clothing end up in rubbish dumps every year.',
        },
        {
          label: 'V',
          text: 'There are signs of change, especially among young people. Second-hand shops and apps for selling used clothes have become very popular, and wearing something old is now seen as stylish rather than embarrassing.',
        },
        {
          label: 'VI',
          text: 'Experts say the best thing shoppers can do is simple: buy fewer clothes, choose good quality and keep them for longer. Repairing a jacket or swapping clothes with friends can save money and help the environment at the same time.',
        },
      ],
      choices: choices([
        'The rise of second-hand',
        'A heavy price for nature',
        'Clothes at lightning speed',
        'The history of the shopping centre',
        'Buy less, choose well',
        'Worn once, then thrown away',
        'The people who make our clothes',
        'Designer brands for everyone',
      ]),
      questions: [
        match('r', 15, 'Paragraph I', 'C'),
        match('r', 16, 'Paragraph II', 'B'),
        match('r', 17, 'Paragraph III', 'G'),
        match('r', 18, 'Paragraph IV', 'F'),
        match('r', 19, 'Paragraph V', 'A'),
        match('r', 20, 'Paragraph VI', 'E'),
      ],
    },
    {
      id: 'r4',
      index: 4,
      title: 'My grandmother’s kitchen',
      instruction: 'Read the text. For questions 21–24, choose the correct answer A, B, C or D. For questions 25–29, decide if the statements agree with the information in the text.',
      passage: [
        {
          label: '1',
          text: 'My grandmother has cooked for our family in Andijan for more than sixty years. She learned from her own mother, standing on a stool in a small kitchen, and she has never used a cookbook. When she turned eighty, I suddenly realised that none of her recipes had ever been written down. If we did not record them, they would be lost.',
        },
        {
          label: '2',
          text: 'I thought it would be easy: I would ask her questions, and she would tell me the recipes. But when I asked how much flour to put in her famous pastries, she looked at me as if I had asked something very strange. “Enough,” she said. She had never measured anything in her life; she cooked by feel, by smell and by memory.',
        },
        {
          label: '3',
          text: 'So we changed our method. Every Sunday I cooked with her, and before she added anything to the pot, I weighed it or poured it into a measuring cup. It drove her a little mad, but slowly a notebook filled with real quantities, times and temperatures.',
        },
        {
          label: '4',
          text: 'It took almost a year to collect forty recipes, from everyday soups to the dishes she makes only for weddings. Every one of them comes from her own kitchen. My cousin, who is good at photography, took pictures, and last month we printed the book and gave a copy to every family in our large family.',
        },
        {
          label: '5',
          text: 'At the family dinner where we gave it out, my grandmother turned the pages slowly. Then she said that the plov recipe was wrong — she always adds a little more cumin than I had written. We all laughed, and I made a note for the second edition.',
        },
      ],
      questions: [
        mcq(
          'r',
          21,
          'Why did the writer start recording the recipes?',
          [
            'His grandmother asked him to.',
            'The recipes had never been written down.',
            'He wanted to open a restaurant.',
            'He needed them for a cooking competition.',
          ],
          'B',
        ),
        mcq(
          'r',
          22,
          'What was the main difficulty at first?',
          [
            'His grandmother did not want to share the recipes.',
            'His grandmother never used exact amounts.',
            'He did not have enough time.',
            'Some ingredients were hard to find.',
          ],
          'B',
        ),
        mcq(
          'r',
          23,
          'How did the writer solve the problem?',
          [
            'He found an old cookbook.',
            'He asked other relatives.',
            'He measured everything while she cooked.',
            'He watched videos of other cooks.',
          ],
          'C',
        ),
        mcq(
          'r',
          24,
          'What happened to the finished book?',
          [
            'It was sold in bookshops.',
            'It won a prize.',
            'Copies were given to the family.',
            'It was published online.',
          ],
          'C',
        ),
        tfng(25, 'The grandmother learned to cook from her mother.', 'True'),
        tfng(26, 'The grandmother kept her recipes in a notebook.', 'False'),
        tfng(27, 'The writer works as a professional cook.', 'No Information'),
        tfng(28, 'Collecting the recipes took about a year.', 'True'),
        tfng(
          29,
          'The book includes recipes from other countries.',
          'False',
          "Har bir retsept buvisining oshxonasidan — chet el retseptlari yo'q.",
        ),
      ],
    },
    {
      id: 'r5',
      index: 5,
      title: 'The Tashkent metro',
      instruction: 'Read the text. For questions 30–33, fill in the missing information. Write no more than ONE WORD and / or A NUMBER. For questions 34–35, choose the correct answer A, B, C or D.',
      passage: [
        {
          label: '1',
          text: 'The Tashkent metro opened in 1977 and was the first underground railway in Central Asia. It was built a decade after a powerful earthquake had destroyed much of the city, so engineers designed the tunnels and stations to survive earthquakes.',
        },
        {
          label: '2',
          text: 'What makes the metro special is its decoration. Each station has its own theme, created with marble, granite, ceramics and chandeliers. Kosmonavtlar station, for example, is dedicated to space exploration, with portraits of famous cosmonauts on its walls.',
        },
        {
          label: '3',
          text: 'For many years, visitors could only admire the stations from memory, because taking photographs underground was not allowed. The ban was finally lifted in 2018, and since then the stations have become popular on social media.',
        },
        {
          label: '4',
          text: 'Today the metro is still growing, with new lines carrying commuters to the city’s newer districts. For local people it is a cheap and fast way to travel, and for tourists it is one of the city’s most surprising attractions: a museum that you can visit for the price of a ticket.',
        },
      ],
      questions: [
        gap('r', 30, 'The Tashkent metro opened in', '1977'),
        gap('r', 31, 'The stations were designed to survive', 'earthquakes'),
        gap('r', 32, 'Kosmonavtlar station is dedicated to … exploration.', 'space'),
        gap('r', 33, 'Until 2018, taking … underground was not allowed.', 'photographs|photos|pictures'),
        mcq(
          'r',
          34,
          'Why do tourists enjoy visiting the metro?',
          [
            'It is the fastest metro in the world.',
            'Its stations are beautifully decorated.',
            'Tickets for tourists are free.',
            'It has a museum about trains.',
          ],
          'B',
        ),
        mcq(
          'r',
          35,
          'What is the writer’s main purpose?',
          [
            'to describe the history and special features of the metro',
            'to complain about public transport in Tashkent',
            'to compare the metro with buses',
            'to explain how earthquakes happen',
          ],
          'A',
        ),
      ],
    },
  ],
  writing: writingPaper(
    {
      context: 'You have read an article in an English-language magazine which says that young people today do not read books.',
      prompt:
        'Write an email to the editor of the magazine. In your email:\n- say whether you agree with the article;\n- describe your own reading habits;\n- suggest how young people could be encouraged to read more.\nWrite about 150 words in an appropriate format and style.',
    },
    'Some people believe that famous sports stars earn far too much money. Others think they deserve their high salaries.\n\nDiscuss both views and give your opinion. Write at least 250 words in an appropriate style and format.',
  ),
  speaking: speakingQuestions({
    personal: [
      'What is your favourite season, and why?',
      'How often do you use the internet, and what for?',
      'Tell me about your best friend.',
    ],
    pictures: 'Picture A: people shopping online at home · Picture B: people shopping in a busy shopping centre',
    compare: [
      'Compare the two pictures. What are the similarities and differences?',
      'Which way of shopping do you prefer? Why?',
      'What are the risks of shopping online?',
    ],
    monologue: {
      image: 'A woman teaching a small group of adults in a community centre',
      prompt:
        'Describe a teacher who has had a strong influence on you. Say who they were, what they taught you and why they were special.',
    },
    debate:
      'Everyone should do sport every day. For: sport keeps people healthy and reduces stress. Against: people have different interests and not enough time. Give arguments for and against this statement and say what you think.',
  }),
  scripts: [
    script('l1', [
      intro('Part one. You will hear some sentences. Choose the correct reply to each sentence.'),
      cue(1, 'woman', 'Have you finished your homework yet?', 2),
      cue(2, 'man', "I'm sorry, Nilufar isn't here at the moment. Can I take a message?", 2),
      cue(3, 'woman', "What's the weather like today?", 2),
      cue(4, 'man', 'Thank you so much for your help!', 2),
      cue(5, 'woman', 'Shall we go by car or by metro?', 2),
      cue(6, 'man', 'Excuse me, is there a bank near here?', 2),
      cue(7, 'woman', "I'm afraid the shirt you ordered is out of stock.", 2),
      cue(8, 'man', 'Do you mind waiting for a few minutes?', 2),
      outro('one'),
    ]),
    script('l2', [
      intro('Part two. You will hear a chef talking to new students. Fill in the missing information. Write one word and, or, a number for each answer.'),
      say('man', "Welcome to the City Cooking School. I'm chef Bahrom, and I'll be teaching you on the beginners' course."),
      cue(9, 'man', "The course lasts six weeks, and in that time you'll learn twelve dishes, from simple salads to a proper plov."),
      cue(10, 'man', "Classes used to be on Sunday mornings, but many students asked us to change, so now all classes are on Saturday mornings, from ten until one."),
      cue(11, 'man', "We provide all the ingredients and knives, but every student must bring an apron. Your clothes will thank you!"),
      cue(12, 'man', "We'll start with something simple and healthy: lentil soup. Next week we'll move on to fresh bread."),
      cue(13, 'man', "To make sure everyone gets enough attention, there's a maximum of twelve students in each class."),
      cue(14, 'man', "And at the end of the course, after a final cooking test, every student receives a certificate."),
      outro('two'),
    ]),
    script('l3', [
      intro('Part three. You will hear people speaking in different situations. Match each speaker to the place where the speaker is. There are two extra places which you do not need to use.'),
      speaker(15, 1),
      say('man', "Ladies and gentlemen, please raise your glasses to the bride and groom. I've known Aziz since we were five, and I've never seen him as happy as he is today."),
      speaker(16, 2),
      say('woman', "These are a bit tight at the front. Could I try them in a size forty-two? And do you have the same style in brown, maybe without laces?"),
      speaker(17, 3),
      say('man2', "I'd like to report a stolen bag. It was taken at the airport this morning, while I was buying coffee. Yes, I can fill in the form now. My passport was inside."),
      speaker(18, 4),
      say('woman2', "Look, there's a free bench by the fountain. Let's sit in the shade for a while. And please put the dog back on the lead, the sign says so."),
      outro('three'),
    ]),
    script('l4', [
      intro('Part four. You will hear someone giving a talk. Label the places on the map. There are three extra options which you do not need to use.'),
      say('woman', "Welcome to Seaside Town. We're at the bus station, on the south side of Sea Road, just east of Pine Street. Here are a few places you might need."),
      cue(19, 'woman', "For the swimming pool, walk west along Sea Road and turn right into Hill Road. Walk north, and the pool is on your right."),
      cue(20, 'woman', "If you need money, the bank is directly opposite the bus station, on the north side of Sea Road."),
      cue(21, 'woman', "The souvenir shop is on the corner of Sea Road and Pine Street, on the west side of Pine Street."),
      cue(22, 'woman', "The hospital is down Pine Street. Walk south, and it's near the end of the street, on your right."),
      cue(23, 'woman', "And to take the ferry to the island, go to the ferry office at the western end of Sea Road, on the south side."),
      outro('four'),
    ]),
    script('l5', [
      intro('Part five. You will hear three extracts. Choose the correct answer for each question. There are two questions for each extract.'),
      say('narrator', 'Extract one. You will hear two friends talking about a concert.'),
      say('man', "Kamila, the concert is on Friday! Are you ready?"),
      cue(24, 'woman', "I'm so sorry, I can't come after all. I'm not ill and I've already paid for the ticket, but I've just found out my exam is on Saturday morning, so I need to study."),
      cue(25, 'woman', "I don't want to sell it online, it's too complicated. My brother loves this band, so I'll give it to him. You two can go together."),
      say('narrator', 'Extract two. You will hear part of a radio interview with a young farmer.'),
      say('woman2', "Sanjar, you left a job in Tashkent to grow strawberries in your village. Why?"),
      cue(26, 'man2', "I liked my job in the city, and I never planned to be a farmer. But my father became seriously ill, and someone had to look after the greenhouses, so I went home."),
      cue(27, 'man2', "I didn't get any loans. What changed everything was selling directly to customers online. People order in the morning, and the strawberries arrive the same day. Exporting is our plan for the future."),
      say('narrator', "Extract three. You will hear a phone call to a dentist's surgery."),
      cue(28, 'woman3', "Hello, I have an appointment on Monday at nine, but I have to travel for work. I don't want to cancel; can I move it to later in the week?"),
      cue(29, 'man3', "Let me see. Thursday at eleven is taken, I'm afraid, but there's a free slot on Tuesday at three. Shall I book that for you?"),
      outro('five'),
    ]),
    script('l6', [
      intro('Part six. You will hear a part of a lecture. Fill in the missing information. Write no more than one word for each answer.'),
      say('man3', "Good afternoon. Today we're looking at the long history of one of the world's oldest games: chess."),
      cue(30, 'man3', "Most historians believe that chess began in India about fifteen hundred years ago, with a game called chaturanga."),
      cue(31, 'man3', "The early game was based on an army, with pieces representing foot soldiers, horses, chariots and elephants."),
      cue(32, 'man3', "From India the game travelled to Persia, and from there it spread across the Arab world, where many of its rules were written down."),
      cue(33, 'man3', "When chess reached Europe, some pieces changed. In the fifteenth century, the queen became the most powerful piece on the board, which made the game much faster."),
      cue(34, 'man3', "In 1997, chess made headlines again, when a computer called Deep Blue defeated the world champion, Garry Kasparov."),
      cue(35, 'man3', "Today, many schools teach chess, because studies suggest it can improve concentration and memory."),
      outro('six'),
    ]),
  ],
};
