import {
  ask,
  cue,
  gap,
  intro,
  mcq,
  outro,
  say,
  script,
  speaker,
  speakingQuestions,
  tfng,
  writingTasks,
} from '../builders';
import type { TestContent } from '../types';

export const content: TestContent = {
  listening: [
    {
      id: 'l1',
      index: 1,
      instruction: 'You will hear some short conversations. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          1,
          'What will the weather be like at the weekend?',
          ['Cold and sunny', 'Warm and rainy', 'Snowy'],
          'A',
        ),
        mcq('l', 2, 'Where does the man work now?', ['In a bank', 'In a school', 'In a hospital'], 'C'),
        mcq('l', 3, 'What time does the train leave?', ['8:05', '8:15', '8:50'], 'B'),
        mcq('l', 4, 'What does the woman want to drink?', ['Water', 'Tea', 'Lemonade'], 'C'),
        mcq('l', 5, 'Why is the man selling his car?', ['It is too old', 'He is moving abroad', 'He needs money'], 'B'),
        mcq('l', 6, 'How did the woman hurt her arm?', ['Playing tennis', 'Falling off a bike', 'Carrying boxes'], 'B'),
        mcq('l', 7, 'What will they cook tonight?', ['Plov', 'Pasta', 'Soup'], 'B'),
        mcq('l', 8, 'Which room is the exam in?', ['Room 104', 'Room 140', 'Room 214'], 'C'),
      ],
    },
    {
      id: 'l2',
      index: 2,
      title: 'Bright Future Scholarship — Information',
      instruction: 'Complete the notes. Write',
      emphasis: 'no more than two words',
      durationSec: 0,
      questions: [
        gap('l', 9, 'Scholarship is for students of', 'engineering'),
        gap('l', 10, 'Application deadline: 30', 'November'),
        gap(
          'l',
          11,
          'Amount per year: $',
          '3000|3,000',
          'Avval 5000 deyiladi, bu umumiy byudjet — har bir talabaga 3000.',
        ),
        gap('l', 12, 'Applicants need two', 'references'),
        gap('l', 13, 'Essay length (words):', '500|five hundred'),
        gap('l', 14, 'Interviews are held in', 'January'),
        gap('l', 15, 'Winners must keep a high', 'average|grade average'),
        gap('l', 16, 'Questions can be sent by', 'email'),
      ],
    },
    {
      id: 'l3',
      index: 3,
      instruction: 'You will hear six people talking about their first job. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq('l', 17, 'Speaker 1’s first job was in', ['a café', 'a bookshop', 'a hotel'], 'B'),
        mcq('l', 18, 'Speaker 2 remembers that the job was', ['boring', 'well paid', 'tiring'], 'C'),
        mcq('l', 19, 'Speaker 3 learned most about', ['teamwork', 'money', 'customers'], 'A'),
        mcq(
          'l',
          20,
          'Speaker 4 left the job because',
          ['she went to university', 'the pay was low', 'the boss was rude'],
          'A',
        ),
        mcq('l', 21, 'Speaker 5 got the job through', ['an advert', 'his uncle', 'his school'], 'B'),
        mcq('l', 22, 'Speaker 6 says the job helped her', ['choose a career', 'buy a car', 'travel'], 'A'),
      ],
    },
    {
      id: 'l4',
      index: 4,
      instruction: 'Listen to an interview with a sports coach. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq(
          'l',
          23,
          'The coach started working with children',
          ['ten years ago', 'after an injury', 'at university'],
          'B',
        ),
        mcq('l', 24, 'He believes children should first learn to', ['win', 'enjoy sport', 'train hard'], 'B'),
        mcq(
          'l',
          25,
          'The biggest problem for young athletes is',
          ['pressure from parents', 'lack of equipment', 'poor coaching'],
          'A',
        ),
        mcq('l', 26, 'He recommends children try', ['one sport only', 'several sports', 'team sports only'], 'B'),
        mcq('l', 27, 'His team’s next competition is in', ['Tashkent', 'Almaty', 'Istanbul'], 'B'),
      ],
    },
    {
      id: 'l5',
      index: 5,
      title: 'Art Workshop for Beginners',
      instruction: 'Complete the notes. Write',
      emphasis: 'one word or a number',
      durationSec: 0,
      questions: [
        gap('l', 28, 'Workshop room is on floor', '3|three'),
        gap('l', 29, 'Participants should bring an', 'apron'),
        gap('l', 30, 'The final work will be shown in an', 'exhibition'),
      ],
    },
    {
      id: 'l6',
      index: 6,
      instruction: 'Listen to a lecture about the history of coffee. Choose the correct answer.',
      durationSec: 0,
      questions: [
        mcq('l', 31, 'Coffee was first discovered in', ['Brazil', 'Ethiopia', 'Turkey'], 'B'),
        mcq(
          'l',
          32,
          'According to the legend, the discovery was made by',
          ['a farmer', 'a goat herder', 'a king'],
          'B',
        ),
        mcq('l', 33, 'The first coffee houses appeared in', ['Europe', 'the Middle East', 'America'], 'B'),
        mcq(
          'l',
          34,
          'Coffee houses in Europe were called “penny universities” because people',
          ['studied there', 'discussed ideas', 'paid teachers'],
          'B',
        ),
        mcq('l', 35, 'Today the largest producer of coffee is', ['Brazil', 'Vietnam', 'Colombia'], 'A'),
      ],
    },
  ],
  reading: [
    {
      id: 'r1',
      index: 1,
      title: 'Notice: Bike Sharing Scheme',
      instruction: 'Read the text and fill in the gaps. Write one word only.',
      passage: [
        {
          label: 'A',
          text: 'The city’s new bike sharing scheme starts on 1 May. More than two hundred bikes will be available at thirty stations across the centre.',
        },
        {
          label: 'B',
          text: 'To use a bike, download the CityBike app and register with your phone number. The first thirty minutes of every ride are free.',
        },
        {
          label: 'C',
          text: 'Bikes must be returned to a station, not left on the street. Riders under sixteen are not allowed to use the service.',
        },
      ],
      questions: [
        gap('r', 1, 'The scheme begins in', 'May'),
        gap('r', 2, 'Bikes can be found at thirty', 'stations'),
        gap('r', 3, 'Users must download an', 'app'),
        gap('r', 4, 'To register, you need your phone', 'number'),
        gap('r', 5, 'The first half an hour is', 'free'),
        gap('r', 6, 'Bikes must not be left on the', 'street'),
        gap('r', 7, 'The minimum age is', 'sixteen|16'),
      ],
    },
    {
      id: 'r2',
      index: 2,
      title: 'Short Messages',
      instruction: 'Read the messages and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Jasur, the plumber is coming at 10 tomorrow to fix the kitchen tap. Can you be at home? I have an early meeting.',
        },
        {
          label: 'B',
          text: 'Museum news: from Monday, entry is free for students every Wednesday afternoon. Just show your student card at the desk.',
        },
        {
          label: 'C',
          text: 'Hi everyone! Our reunion dinner is moved from the 12th to the 19th because the restaurant is closed. Hope you can still come!',
        },
      ],
      questions: [
        mcq('r', 8, 'What will the plumber fix?', ['The shower', 'The kitchen tap', 'The heating'], 'B'),
        mcq('r', 9, 'Why can’t the writer be at home?', ['She is travelling', 'She has a meeting', 'She is ill'], 'B'),
        mcq(
          'r',
          10,
          'When is museum entry free for students?',
          ['Every Monday', 'Wednesday afternoons', 'At weekends'],
          'B',
        ),
        mcq('r', 11, 'What must students show?', ['A ticket', 'A student card', 'A passport'], 'B'),
        mcq('r', 12, 'What is the new date of the dinner?', ['The 12th', 'The 19th', 'The 21st'], 'B'),
        mcq(
          'r',
          13,
          'Why was the dinner moved?',
          ['The restaurant is closed', 'People are busy', 'It is a holiday'],
          'A',
        ),
        mcq('r', 14, 'Which message gives information to the public?', ['A', 'B', 'C'], 'B'),
      ],
    },
    {
      id: 'r3',
      index: 3,
      title: 'The Rise of Audiobooks',
      instruction: 'Read the article and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Audiobooks are more popular than ever. In the last five years, the number of people listening to them has almost tripled.',
        },
        {
          label: 'B',
          text: 'Many listeners say audiobooks let them “read” while doing other things, such as driving, cooking or exercising.',
        },
        {
          label: 'C',
          text: 'Some teachers worry that listening is not the same as reading. However, studies show that people understand stories equally well in both forms.',
        },
        {
          label: 'D',
          text: 'Publishers now hire famous actors to record books, turning a simple reading into a real performance.',
        },
      ],
      questions: [
        mcq('r', 15, 'The number of audiobook listeners has', ['doubled', 'almost tripled', 'fallen'], 'B'),
        mcq(
          'r',
          16,
          'People like audiobooks because they can',
          ['learn faster', 'do other things at the same time', 'save money'],
          'B',
        ),
        mcq(
          'r',
          17,
          'Some teachers are concerned that',
          ['audiobooks are expensive', 'listening differs from reading', 'children stop studying'],
          'B',
        ),
        mcq(
          'r',
          18,
          'Studies show that understanding of stories is',
          ['better with reading', 'better with listening', 'the same'],
          'C',
        ),
        mcq('r', 19, 'Publishers now use', ['computer voices', 'famous actors', 'authors only'], 'B'),
        mcq('r', 20, 'The word “performance” refers to', ['a show', 'a test', 'a sale'], 'A'),
        mcq('r', 21, 'The writer’s attitude to audiobooks is', ['negative', 'positive', 'worried'], 'B'),
      ],
    },
    {
      id: 'r4',
      index: 4,
      title: 'Tashkent Metro: An Underground Museum',
      instruction: 'Do the following statements agree with the information in the text?',
      passage: [
        { label: 'A', text: 'Opened in 1977, the Tashkent Metro was the first underground railway in Central Asia.' },
        {
          label: 'B',
          text: 'Each station has its own design, with marble walls, chandeliers and mosaics that tell stories about the history and culture of Uzbekistan.',
        },
        {
          label: 'C',
          text: 'For many years, taking photographs in the metro was forbidden. The ban was lifted in 2018, and the stations quickly became popular on social media.',
          highlight: 'The ban was lifted in 2018',
        },
        {
          label: 'D',
          text: 'Today the network continues to grow, with new lines connecting the city centre to its outer districts.',
        },
      ],
      questions: [
        tfng(22, 'The Tashkent Metro opened in the 1970s.', 'True'),
        tfng(23, 'All metro stations look the same.', 'False'),
        tfng(24, 'Photography in the metro is still banned.', 'False', 'C paragrafi: taqiq 2018-yilda bekor qilingan.'),
        tfng(25, 'The metro carries more than a million passengers a day.', 'Not given'),
        tfng(26, 'New metro lines are being built.', 'True'),
      ],
    },
    {
      id: 'r5',
      index: 5,
      title: 'The Truth About Multitasking',
      instruction: 'Read the text and choose the correct answer.',
      passage: [
        {
          label: 'A',
          text: 'Many people are proud of their ability to multitask, answering messages while working or studying.',
        },
        {
          label: 'B',
          text: 'Research shows, however, that the brain cannot focus on two demanding tasks at once. Instead, it switches quickly between them.',
        },
        {
          label: 'C',
          text: 'Each switch costs time and energy. People who multitask make up to fifty percent more mistakes and take longer to finish.',
        },
        {
          label: 'D',
          text: 'Experts recommend “single-tasking”: working on one task for a set period, for example twenty-five minutes, before taking a short break.',
        },
      ],
      questions: [
        mcq('r', 27, 'Many people believe multitasking is', ['impossible', 'a useful skill', 'dangerous'], 'B'),
        mcq(
          'r',
          28,
          'According to research, the brain',
          ['does two tasks at once', 'switches between tasks', 'stops working'],
          'B',
        ),
        mcq('r', 29, 'Switching between tasks costs', ['money', 'time and energy', 'nothing'], 'B'),
        mcq(
          'r',
          30,
          'People who multitask make up to',
          ['15% more mistakes', '25% more mistakes', '50% more mistakes'],
          'C',
        ),
        mcq(
          'r',
          31,
          'Experts suggest working on one task for',
          ['ten minutes', 'twenty-five minutes', 'two hours'],
          'B',
        ),
        mcq('r', 32, 'The word “demanding” is closest to', ['easy', 'difficult', 'boring'], 'B'),
        mcq('r', 33, 'Paragraph D gives', ['a warning', 'a recommendation', 'a history'], 'B'),
        mcq(
          'r',
          34,
          'The text mainly shows that multitasking',
          ['is effective', 'is less effective than people think', 'is a new trend'],
          'B',
        ),
        mcq(
          'r',
          35,
          'A student preparing for an exam should',
          ['answer messages while studying', 'focus on one task at a time', 'study without breaks'],
          'B',
        ),
      ],
    },
  ],
  writing: writingTasks(
    'You live in a block of flats. You have received this notice from the building management:\n\n"From next month, the children’s playground behind the building will be replaced by a car park for residents."',
    'Write a message to a neighbour who has young children. Tell them about the notice and how you feel about it. Write about 50 words.',
    'Write a letter to the building management. Explain your opinion about the plan and suggest an alternative. Write 120–150 words.',
    'Some people believe that students should be allowed to choose all the subjects they study at school. Others think that schools should decide. Discuss both views and give your own opinion. Write at least 180 words.',
  ),
  speaking: speakingQuestions({
    personal: [
      'What is your favourite season, and why?',
      'How often do you use the internet, and what for?',
      'Tell me about your best friend.',
    ],
    pictures: 'Picture A: people shopping online at home · Picture B: people shopping in a busy shopping centre',
    compare: [
      'Compare the two pictures. What are the similarities and differences?',
      'Which way of shopping do you prefer? Why?',
      'What are the risks of shopping online?',
    ],
    monologue: {
      image: 'A woman teaching a small group of adults in a community centre',
      prompt:
        'Describe a teacher who has had a strong influence on you. Say who they were, what they taught you and why they were special.',
    },
    debate:
      'Everyone should do sport every day. For: sport keeps people healthy and reduces stress. Against: people have different interests and not enough time. Give arguments for and against this statement and say what you think.',
  }),
  scripts: [
    script('l1', [
      intro('Part one. You will hear some short conversations. For each question, choose the correct answer.'),
      ask(1, 'What will the weather be like at the weekend?'),
      say('man', "It's been raining all week. Is it going to be warm at the weekend?"),
      say('woman', "The rain will stop, but it won't be warm. The forecast says cold and sunny, so take a jacket.", 2),
      ask(2, 'Where does the man work now?'),
      say('woman', 'Are you still teaching at the school?'),
      say(
        'man',
        "No, I left last year. I worked in a bank for a few months, and now I'm a nurse at the city hospital.",
        2,
      ),
      ask(3, 'What time does the train leave?'),
      say('woman', 'Does the train leave at eight fifty?'),
      say('man', "No, it's eight fifteen. The eight oh five is the bus. We'd better hurry.", 2),
      ask(4, 'What does the woman want to drink?'),
      say('man', 'Would you like some tea? Or just water?'),
      say('woman', "It's so hot today. Have you got any lemonade? That would be perfect.", 2),
      ask(5, 'Why is the man selling his car?'),
      say('woman', "Why are you selling your car? It's almost new, and I know you don't need the money."),
      say('man', "I'm moving abroad next month for work, and I can't take it with me.", 2),
      ask(6, 'How did the woman hurt her arm?'),
      say('man', 'What happened to your arm? Was it tennis again?'),
      say('woman', 'Not this time. I fell off my bike on the way to work. A car stopped suddenly in front of me.', 2),
      ask(7, 'What will they cook tonight?'),
      say('woman', 'Shall we make plov tonight?'),
      say('man', "We had plov yesterday, and soup takes too long. Let's make pasta. It's quick and easy.", 2),
      ask(8, 'Which room is the exam in?'),
      say('man', 'Is the exam in room one-oh-four?'),
      say('woman', "That was last year. This year it's in room two-fourteen, on the second floor.", 2),
      outro('one'),
    ]),
    script('l2', [
      intro(
        'Part two. You will hear a phone call about a scholarship. Complete the notes. Write no more than two words.',
      ),
      say('woman', 'Bright Future Foundation, how can I help you?'),
      cue(9, 'man', "Hello. I'm interested in your scholarship. Is it for all students?"),
      say('woman', "No, this year it's only for students of engineering."),
      cue(10, 'man', 'When is the deadline?'),
      say('woman', 'Applications must arrive by the thirtieth of November.'),
      cue(
        11,
        'woman',
        'The programme has a budget of five thousand dollars in total, but each student receives three thousand dollars per year.',
      ),
      say('man', 'What do I need to send?'),
      cue(12, 'woman', 'Your exam results and two references, for example from your teachers.'),
      cue(13, 'woman', 'You also need to write an essay of five hundred words about your goals.'),
      cue(14, 'woman', 'The best candidates will be invited to an interview in January.'),
      cue(
        15,
        'woman',
        'And remember, winners must keep a high average during their studies, or they lose the scholarship.',
      ),
      say('man', 'If I have more questions?'),
      cue(16, 'woman', 'Please send them by email. The phone line is only open on Mondays.'),
      say('man', 'Thank you very much.', 2),
      outro('two'),
    ]),
    script('l3', [
      intro(
        'Part three. You will hear six people talking about their first job. For each speaker, choose the correct answer.',
      ),
      speaker(17, 1),
      say(
        'woman',
        'Most of my friends worked in cafés or hotels, but my first job was in a small bookshop. I read so many books during quiet afternoons.',
        2,
      ),
      speaker(18, 2),
      say(
        'man',
        "It wasn't boring at all, and the pay was OK. But it was so tiring. I delivered newspapers at five in the morning before school.",
        2,
      ),
      speaker(19, 3),
      say(
        'man2',
        "I earned my first money and met lots of customers, but the biggest lesson was teamwork. In a busy kitchen, you can't do anything alone.",
        2,
      ),
      speaker(20, 4),
      say(
        'woman2',
        'My boss was kind, and the pay was fine. I only left because I got a place at university in another city.',
        2,
      ),
      speaker(21, 5),
      say(
        'man3',
        "I didn't answer an advert, and my school didn't help. My uncle owned a garage, and he gave me a job for the summer.",
        2,
      ),
      speaker(22, 6),
      say(
        'woman3',
        "I worked as a receptionist at a dental clinic. I didn't earn much, but watching the dentists helped me choose my career. I'm a dentist now.",
        2,
      ),
      outro('three'),
    ]),
    script('l4', [
      intro('Part four. You will hear an interview with a sports coach. Choose the correct answer.'),
      say('woman', 'My guest is Rustam, who coaches young swimmers. How did you start working with children?'),
      cue(
        23,
        'man',
        "I was a professional swimmer until I had a serious shoulder injury. After that, I couldn't compete, so I started coaching children.",
      ),
      cue(
        24,
        'man',
        'Many coaches focus on winning and hard training. I believe children should first learn to enjoy sport. Winning comes later.',
      ),
      say('woman', 'What problems do young athletes face?'),
      cue(
        25,
        'man',
        'Equipment and coaching are much better now. The biggest problem is pressure from parents who expect medals too early.',
      ),
      cue(
        26,
        'man',
        'I always recommend trying several sports before choosing one. It builds a stronger, more balanced body.',
      ),
      say('woman', "What's next for your team?"),
      cue(
        27,
        'man',
        'We competed in Tashkent last month. Our next competition is in Almaty in March, and next year maybe Istanbul.',
        2,
      ),
      outro('four'),
    ]),
    script('l5', [
      intro(
        'Part five. You will hear an introduction to an art workshop. Complete the notes. Write one word or a number.',
      ),
      cue(
        28,
        'woman',
        "Welcome to the beginners' art workshop. All our sessions take place in the studio on floor three. The lift is next to the entrance.",
      ),
      cue(29, 'woman', 'We provide paints and brushes, but please bring an apron, because painting can get messy.'),
      cue(
        30,
        'woman',
        'At the end of the course, your final work will be shown in an exhibition for your family and friends.',
        2,
      ),
      outro('five'),
    ]),
    script('l6', [
      intro('Part six. You will hear a lecture about the history of coffee. Choose the correct answer.'),
      cue(
        31,
        'man',
        'Good afternoon. Today, coffee is grown in Brazil, Vietnam and many other countries, but it was first discovered in Ethiopia, more than a thousand years ago.',
      ),
      cue(
        32,
        'man',
        'According to a famous legend, a goat herder noticed that his goats became very energetic after eating red berries from a certain bush.',
      ),
      cue(
        33,
        'man',
        'From Africa, coffee travelled to the Middle East, where the first coffee houses appeared in the fifteenth century. Europe followed much later.',
      ),
      cue(
        34,
        'man',
        "In England, coffee houses were called 'penny universities'. For the price of a cup, people could listen to and discuss the latest ideas.",
      ),
      cue(
        35,
        'man',
        'And today? Vietnam and Colombia are major producers, but Brazil is still the largest producer of coffee in the world. Thank you.',
        2,
      ),
      say('narrator', 'That is the end of the listening test.'),
    ]),
  ],
};
