export type {
  AnswerKey,
  AnswerKeys,
  Choice,
  GapQuestion,
  ListeningPart,
  MapBlock,
  MapLabel,
  MapRoad,
  MapSpec,
  MatchQuestion,
  McqQuestion,
  PartTranscript,
  PassageParagraph,
  Question,
  ReadingPart,
  SectionKind,
  SectionMeta,
  SpeakingQuestion,
  TestDetail,
  TestFormat,
  TestStatus,
  TestSummary,
  TfngQuestion,
  TranscriptLine,
  WritingTask,
} from '@cefr/core';
