import type { SectionMeta, TestDetail, TestSummary } from '../model/types';
import { listeningParts, readingParts, speakingQuestions, writingTasks } from './content';

export const tests: TestSummary[] = [
  {
    id: 't13',
    number: 13,
    title: 'Mock Test #13',
    format: { month: 8, year: 2026 },
    durationLabel: '2:45',
    isNew: true,
    isFree: true,
    isPro: false,
    status: 'new',
  },
  {
    id: 't12',
    number: 12,
    title: 'Mock Test #12',
    format: { month: 8, year: 2026 },
    durationLabel: '2:45',
    isNew: false,
    isFree: true,
    isPro: false,
    status: 'in_progress',
    progress: 0.51,
    resumeSection: 'reading',
    resumeAnswered: 18,
    resumeTotal: 35,
    resumeRemainingSec: 1930,
  },
  {
    id: 't11',
    number: 11,
    title: 'Mock Test #11',
    format: { month: 8, year: 2026 },
    durationLabel: '2:45',
    isNew: false,
    isFree: true,
    isPro: false,
    status: 'completed',
    score: 58,
    level: 'B2',
    completedAt: '2026-09-22',
    resultId: 'r11',
  },
  {
    id: 't14',
    number: 14,
    title: 'Mock Test #14',
    format: { month: 9, year: 2026 },
    durationLabel: '2:45',
    isNew: false,
    isFree: false,
    isPro: true,
    status: 'locked',
  },
  {
    id: 't10',
    number: 10,
    title: 'Mock Test #10',
    format: { month: 7, year: 2026 },
    durationLabel: '2:45',
    isNew: false,
    isFree: true,
    isPro: false,
    status: 'completed',
    score: 54,
    level: 'B2',
    completedAt: '2026-09-08',
    resultId: 'r10',
  },
  {
    id: 't15',
    number: 15,
    title: 'Mock Test #15',
    format: { month: 9, year: 2026 },
    durationLabel: '2:45',
    isNew: true,
    isFree: false,
    isPro: true,
    status: 'locked',
  },
];

const sections: SectionMeta[] = [
  { kind: 'listening', title: 'Listening', parts: listeningParts.length, questions: 35, minutes: 35 },
  { kind: 'reading', title: 'Reading', parts: readingParts.length, questions: 35, minutes: 60 },
  { kind: 'writing', title: 'Writing', parts: writingTasks.length, minutes: 60 },
  { kind: 'speaking', title: 'Speaking', parts: 3, minutes: 15, approx: true },
];

export const buildTestDetail = (summary: TestSummary): TestDetail => ({
  id: summary.id,
  number: summary.number,
  title: summary.title,
  format: summary.format,
  durationLabel: summary.durationLabel,
  sectionsCount: sections.length,
  scoreRange: '0–75',
  sections,
  listening: listeningParts,
  reading: readingParts,
  writing: writingTasks,
  speaking: speakingQuestions,
});

export const delay = <T>(value: T, ms = 400) => new Promise<T>((resolve) => setTimeout(() => resolve(value), ms));
