import { palette } from './palette';

export const light = {
  bg: palette.neutral[25],
  surface: palette.neutral.white,
  surfaceMuted: palette.neutral[50],
  surfaceSubtle: palette.neutral[100],
  skeleton: palette.neutral[150],
  text: palette.neutral[900],
  textReading: palette.neutral[800],
  textStrong: palette.neutral[750],
  textSecondary: palette.neutral[600],
  textTertiary: palette.neutral[400],
  border: palette.neutral[200],
  borderStrong: palette.neutral[300],
  divider: palette.neutral[50],
  hairline: 'rgba(20,22,30,0.06)',
  hairlineSoft: 'rgba(20,22,30,0.05)',
  action: palette.primary[500],
  actionPressed: palette.primary[600],
  onAction: palette.primary.ink,
  actionGradient: [palette.primary.gradTop, palette.primary.gradBottom] as const,
  focusRing: palette.primary.ring,
  selectedBg: palette.primary[50],
  selectedBorder: palette.primary.border,
  selectedText: palette.primary.text,
  chipActiveBg: palette.primary[100],
  link: palette.primary.text,
  data: palette.secondary[500],
  dataSoft: palette.secondary[400],
  dataMuted: palette.secondary[200],
  dataTrack: palette.neutral[50],
  hero: [palette.secondary.heroTop, palette.secondary.heroBottom] as const,
  avatar: [palette.primary[100], palette.primary[200]] as const,
  aiTile: [palette.primary[100], palette.secondary[200]] as const,
  success: palette.success,
  warning: palette.warning,
  error: palette.error,
  highlight: palette.highlight,
  streak: palette.streak,
  disabledBg: palette.disabledBg,
  disabledText: palette.disabledText,
  overlay: palette.overlay,
  onHero: palette.neutral.white,
  onHeroMuted: palette.white.a72,
} as const;

export const dark = {
  ...light,
  bg: '#101113',
  surface: '#1B1C20',
  surfaceMuted: '#23242A',
  surfaceSubtle: '#2A2B31',
  text: '#ECECEF',
  textReading: '#ECECEF',
  textStrong: '#ECECEF',
  textSecondary: '#9FA1A9',
  textTertiary: '#7C7E86',
  border: '#2A2B31',
  divider: '#24252B',
  data: '#87ADE4',
} as const;

export type Colors = typeof light;
